# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: loams/approvals/v1/approvals.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import loams.approvals.v1.approvals_pb2 as loams_dot_approvals_dot_v1_dot_approvals__pb2


class ApprovalService(Protocol):
    async def list_approvals(self, request: loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsRequest, ctx: RequestContext) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_approval(self, request: loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalRequest, ctx: RequestContext) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def watch_approvals(self, request: loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsRequest, ctx: RequestContext) -> AsyncIterator[loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def decide_approval(self, request: loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalRequest, ctx: RequestContext) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ApprovalServiceASGIApplication(ConnectASGIApplication[ApprovalService]):
    def __init__(self, service: ApprovalService | AsyncGenerator[ApprovalService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/loams.approvals.v1.ApprovalService/ListApprovals": Endpoint.unary(
                    method=MethodInfo(
                        name="ListApprovals",
                        service_name="loams.approvals.v1.ApprovalService",
                        input=loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsRequest,
                        output=loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_approvals,
                ),
                "/loams.approvals.v1.ApprovalService/GetApproval": Endpoint.unary(
                    method=MethodInfo(
                        name="GetApproval",
                        service_name="loams.approvals.v1.ApprovalService",
                        input=loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalRequest,
                        output=loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_approval,
                ),
                "/loams.approvals.v1.ApprovalService/WatchApprovals": Endpoint.server_stream(
                    method=MethodInfo(
                        name="WatchApprovals",
                        service_name="loams.approvals.v1.ApprovalService",
                        input=loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsRequest,
                        output=loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch_approvals,
                ),
                "/loams.approvals.v1.ApprovalService/DecideApproval": Endpoint.unary(
                    method=MethodInfo(
                        name="DecideApproval",
                        service_name="loams.approvals.v1.ApprovalService",
                        input=loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalRequest,
                        output=loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.decide_approval,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/loams.approvals.v1.ApprovalService"


class ApprovalServiceClient(ConnectClient):
    async def list_approvals(
        self,
        request: loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListApprovals",
                service_name="loams.approvals.v1.ApprovalService",
                input=loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsRequest,
                output=loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_approval(
        self,
        request: loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetApproval",
                service_name="loams.approvals.v1.ApprovalService",
                input=loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalRequest,
                output=loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def watch_approvals(
        self,
        request: loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchApprovals",
                service_name="loams.approvals.v1.ApprovalService",
                input=loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsRequest,
                output=loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def decide_approval(
        self,
        request: loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DecideApproval",
                service_name="loams.approvals.v1.ApprovalService",
                input=loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalRequest,
                output=loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class ApprovalServiceSync(Protocol):
    def list_approvals(self, request: loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsRequest, ctx: RequestContext) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_approval(self, request: loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalRequest, ctx: RequestContext) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def watch_approvals(self, request: loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsRequest, ctx: RequestContext) -> Iterator[loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def decide_approval(self, request: loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalRequest, ctx: RequestContext) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ApprovalServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ApprovalServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/loams.approvals.v1.ApprovalService/ListApprovals": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListApprovals",
                        service_name="loams.approvals.v1.ApprovalService",
                        input=loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsRequest,
                        output=loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_approvals,
                ),
                "/loams.approvals.v1.ApprovalService/GetApproval": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetApproval",
                        service_name="loams.approvals.v1.ApprovalService",
                        input=loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalRequest,
                        output=loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_approval,
                ),
                "/loams.approvals.v1.ApprovalService/WatchApprovals": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="WatchApprovals",
                        service_name="loams.approvals.v1.ApprovalService",
                        input=loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsRequest,
                        output=loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch_approvals,
                ),
                "/loams.approvals.v1.ApprovalService/DecideApproval": EndpointSync.unary(
                    method=MethodInfo(
                        name="DecideApproval",
                        service_name="loams.approvals.v1.ApprovalService",
                        input=loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalRequest,
                        output=loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.decide_approval,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/loams.approvals.v1.ApprovalService"


class ApprovalServiceClientSync(ConnectClientSync):
    def list_approvals(
        self,
        request: loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListApprovals",
                service_name="loams.approvals.v1.ApprovalService",
                input=loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsRequest,
                output=loams_dot_approvals_dot_v1_dot_approvals__pb2.ListApprovalsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def get_approval(
        self,
        request: loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetApproval",
                service_name="loams.approvals.v1.ApprovalService",
                input=loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalRequest,
                output=loams_dot_approvals_dot_v1_dot_approvals__pb2.GetApprovalResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def watch_approvals(
        self,
        request: loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchApprovals",
                service_name="loams.approvals.v1.ApprovalService",
                input=loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsRequest,
                output=loams_dot_approvals_dot_v1_dot_approvals__pb2.WatchApprovalsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def decide_approval(
        self,
        request: loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DecideApproval",
                service_name="loams.approvals.v1.ApprovalService",
                input=loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalRequest,
                output=loams_dot_approvals_dot_v1_dot_approvals__pb2.DecideApprovalResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


