[package]
name = "loams-quickwit"
description = "Quickwit's split, directory, query and merge-policy code, vendored and adapted to crates.io Tantivy."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bitpacking.workspace = true
bytes.workspace = true
bytesize.workspace = true
fnv.workspace = true
futures.workspace = true
hex.workspace = true
humantime.workspace = true
itertools.workspace = true
postcard.workspace = true
regex.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
tantivy.workspace = true
tantivy-fst.workspace = true
thiserror.workspace = true
time.workspace = true
time-fmt.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
ulid.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
proptest.workspace = true
rand.workspace = true
tempfile.workspace = true

[lints]
workspace = true
