//! The public `loams.*.v1` packages of the unified Connect API (design §44
//! §7–§8, D600).
//!
//! Generated at build time from `proto/` (see `build.rs`): buffa messages
//! with the proto3 JSON mapping, the connect-rust service traits the server
//! implements and, with the `client` feature, their clients. The packages
//! are re-exported at the crate root as `loams_proto::loams::<pkg>::v1`, the
//! same path the generated code of every other proto crate uses
//! (`loams-apps-mock`, `loams-live-proto`), so the SDKs and the mock reach
//! for a message the same way whichever crate holds it.
//!
//! [`FILE_DESCRIPTOR_SET`] is the `FileDescriptorSet` of every generated
//! file and its imports. The server hands it to `grpc.reflection.v1`
//! (`connectrpc_reflection::Reflector`), so `grpcurl` and Postman see the
//! same contract the server was built from.
//!
//! `loams.live.v1` is generated by R1's `loams-live-proto`, not here; see
//! `build.rs`.

#[allow(missing_debug_implementations, missing_docs, unreachable_pub)]
mod generated {
    connectrpc::include_generated!();
}

pub use generated::*;

/// The well-known types the generated messages name by path, so a crate that
/// implements a service over them reaches for the *same* types the generated
/// code does instead of taking a second, possibly different, dependency on
/// `buffa-types`.
///
/// `loams.collection.v1` needs `google::protobuf::Struct`: a collection's
/// schema is carried as JSON (the proto header says why), which is what a
/// `Struct` is.
pub use buffa_types::google;

/// The wire-format `FileDescriptorSet` of every generated file and its
/// transitive imports, for `grpc.reflection.v1` (design §44 §4).
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/loams_api_descriptor.bin"));
