# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loams/options/v1/options.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'loams/options/v1/options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eloams/options/v1/options.proto\x12\x10loams.options.v1\x1a google/protobuf/descriptor.proto\"Y\n\rModuleOptions\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n\x07summary\x18\x02 \x01(\tR\x07summary\x12\x1a\n\x08unstable\x18\x03 \x01(\x08R\x08unstable\"z\n\rFacadeOptions\x12\x16\n\x06module\x18\x01 \x01(\tR\x06module\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n\nretry_safe\x18\x03 \x01(\x08R\tretrySafe\x12\x1e\n\npagination\x18\x04 \x01(\tR\npagination:Z\n\x06module\x12\x1f.google.protobuf.ServiceOptions\x18\xd1\x86\x03 \x01(\x0b\x32\x1f.loams.options.v1.ModuleOptionsR\x06module:Y\n\x06\x66\x61\x63\x61\x64\x65\x12\x1e.google.protobuf.MethodOptions\x18\xd2\x86\x03 \x03(\x0b\x32\x1f.loams.options.v1.FacadeOptionsR\x06\x66\x61\x63\x61\x64\x65\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loams.options.v1.options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODULEOPTIONS']._serialized_start=86
  _globals['_MODULEOPTIONS']._serialized_end=175
  _globals['_FACADEOPTIONS']._serialized_start=177
  _globals['_FACADEOPTIONS']._serialized_end=299
# @@protoc_insertion_point(module_scope)
