apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: loams-kafka-events
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: kafka.loams.svc.cluster.local:9092
    - name: consumerGroup
      value: loams-workflow-kafka
    - name: authType
      value: none
    - name: initialOffset
      value: oldest
scopes:
  - loams-trigger-edge
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: loams-kafka-triggers
spec:
  pubsubname: loams-kafka-events
  topic: workflow.kafka
  routes:
    default: /events/kafka
scopes:
  - loams-trigger-edge
