// @loams/proto: the Loams app protos (design §37 §8.2) as protobuf-es v2
// messages and service descriptors. Everything under ./gen is generated by
// `pnpm generate` (buf.gen.apps.yaml at the repository root) and committed;
// CI fails when it drifts from proto/.
//
// Each package is also exported on its own path (`@loams/proto/approvals`),
// which keeps a plugin's bundle to the services it uses.

export * as approvals from './gen/loams/approvals/v1/approvals_pb.js';
export * as collection from './gen/loams/collection/v1/collection_pb.js';
export * as documents from './gen/loams/collection/v1/document_pb.js';
export * as query from './gen/loams/collection/v1/query_pb.js';
export * as devices from './gen/loams/devices/v1/devices_pb.js';
export * as errors from './gen/loams/errors/v1/errors_pb.js';
export * as instance from './gen/loams/instance/v1/instance_pb.js';
export * as live from './gen/loams/live/v1/live_pb.js';
export * as liveValue from './gen/loams/live/v1/value_pb.js';
export * as notifications from './gen/loams/notifications/v1/notifications_pb.js';
export * as operations from './gen/loams/operations/v1/operations_pb.js';
// loams.options.v1 is not a wire surface: it declares no message a client
// sends. It is generated because instance.proto's service options reference
// it, and protoc-gen-es writes that import into the generated descriptor.
export * as options from './gen/loams/options/v1/options_pb.js';

/** The proto packages this module generates, as `GetInstance.api_versions` names them. */
export const APP_API_PACKAGES = [
  'loams.instance.v1',
  'loams.devices.v1',
  'loams.approvals.v1',
  'loams.operations.v1',
  'loams.notifications.v1',
] as const;

export type AppApiPackage = (typeof APP_API_PACKAGES)[number];
