export type ServerKind = "local" | "remote" | "demo";
export interface ServerEntry {
	id: string;
	name: string;
	kind: ServerKind;
	url: string;
} // url = origin
export type EngineState =
	| { phase: "stopped" }
	| { phase: "starting"; attempt: number }
	| {
			phase: "ready";
			url: string;
			esUrl: string;
			flightUrl: string;
			durableUrl: string;
			liveUrl?: string;
			pid: number;
	  }
	| { phase: "failed"; reason: string; logPath: string };
export type FactoryAppId =
	| "forgejo"
	| "zulip"
	| "plane"
	| "glitchtip"
	| "openpanel"
	| "matomo"
	| "langfuse"
	| "openobserve";
export type FactoryHealth =
	| "unconfigured"
	| "ok"
	| "auth_failed"
	| "unreachable";
export interface FactoryAppInfo {
	id: FactoryAppId;
	label: string;
	url?: string;
	health: FactoryHealth;
	hasPanels: boolean;
	credentialFields: { key: string; label: string; secret: boolean }[];
	/** Stored values of the non-secret credential fields only; never a secret. */
	fields?: Record<string, string>;
	persistent: boolean; // false when safeStorage has no backend (session-only)
}
export interface EmbedRect {
	x: number;
	y: number;
	width: number;
	height: number;
}

export interface FactoryQuery {
	app: FactoryAppId;
	op: string;
	params: Record<string, unknown>;
}
export type IpcResult<T> =
	| { ok: true; value: T }
	| { ok: false; code: string; message: string };

/** `NodeJS.Platform`, spelled out so the web packages can import this file without @types/node. */
export type DesktopPlatform =
	| "aix"
	| "android"
	| "darwin"
	| "freebsd"
	| "haiku"
	| "linux"
	| "openbsd"
	| "sunos"
	| "win32"
	| "cygwin"
	| "netbsd";

export type StackId = "postgres" | "wesql" | "tikv";
export type StackState =
	| { phase: "unavailable"; reason: "no_container_runtime" }
	| { phase: "stopped" }
	| { phase: "starting" }
	| {
			phase: "running";
			services: { name: string; state: string; ports: string[] }[];
	  }
	| { phase: "error"; message: string };
/** One row of the connector catalog (generated by scripts/connectors-catalog.mjs). */
export interface ConnectorSummary {
	id: string;
	name: string;
	category: string;
	status: string;
	runtime: { kind: string; ref: string };
	/** Enabled source modes (streaming, batch, cdc, webhook); null when the connector has no source side. */
	source: string[] | null;
	sink: string[] | null;
	modes: string[];
	auth: string[];
	licence: string;
	/** True for a generated placeholder: no config fields, no capability detail yet. */
	stub: boolean;
}
export interface ConnectorDetail {
	manifest: Record<string, unknown>;
	/** The JSON Schema (2020-12) of the instance config. */
	schema: Record<string, unknown>;
}

export interface ConnectorValidation {
	valid: boolean;
	/** `path` is a JSON Pointer into the config ("/sasl/password"); "" is the root. */
	errors: { path: string; message: string }[];
}

export interface LoamsDesktopApi {
	version: string;
	platform: DesktopPlatform;
	servers: {
		list(): Promise<{ servers: ServerEntry[]; activeId: string }>;
		add(e: Omit<ServerEntry, "id">): Promise<IpcResult<ServerEntry>>;
		remove(id: string): Promise<IpcResult<void>>;
		activate(id: string): Promise<IpcResult<void>>; // reloads the window
	};
	engine: {
		state(): Promise<EngineState>;
		start(): Promise<void>;
		stop(): Promise<void>;
		openLogs(): Promise<void>;
		onState(cb: (s: EngineState) => void): () => void;
	};
	factory: {
		list(): Promise<FactoryAppInfo[]>;
		configure(
			app: FactoryAppId,
			url: string,
			fields: Record<string, string>,
		): Promise<IpcResult<FactoryAppInfo>>;
		test(app: FactoryAppId): Promise<FactoryAppInfo>;
		remove(app: FactoryAppId): Promise<void>;
		query<T = unknown>(q: FactoryQuery): Promise<IpcResult<T>>;
		openApp(app: FactoryAppId): Promise<IpcResult<void>>;
		closeApp(app: FactoryAppId): Promise<void>;
		/** D678: place the app's embedded view over `rect` (CSS px in the console window). */
		showEmbedded(app: FactoryAppId, rect: EmbedRect): Promise<IpcResult<void>>;
		hideEmbedded(): Promise<void>;
		reloadEmbedded(app: FactoryAppId): Promise<void>;
		/** Destroy the embedded view and open the app in its own window. */
		popOut(app: FactoryAppId): Promise<IpcResult<void>>;
	};
	shell: {
		openExternal(url: string): Promise<IpcResult<void>>;
		/** `route` (a console hash route) is opened when the notification is clicked. */
		notify(title: string, body?: string, route?: string): Promise<void>;
		clipboardWrite(text: string): Promise<void>;
		onNavigate(cb: (path: string) => void): () => void; // deep links
		/** Call once after subscribing with onNavigate; returns a link received before the page was ready. */
		takePendingNavigation(): Promise<string | null>;
		setBadge(count: number): Promise<void>; // pending approvals in tray
	};
	update: {
		state(): Promise<{
			phase:
				| "disabled"
				| "idle"
				| "checking"
				| "available"
				| "downloading"
				| "ready"
				| "error";
			version?: string;
			message?: string;
			/**
			 * D677: "self" downloads and installs in place; "manual" (macOS, Linux
			 * package installs) means download() opens the release page instead.
			 */
			mode?: "self" | "manual";
			/** 0-100 while phase is "downloading". */
			percent?: number;
		}>;
		check(): Promise<void>;
		/** "self" mode: fetch the update. "manual" mode: open the release page. */
		download(): Promise<void>;
		installAndRestart(): Promise<void>;
	};
	stacks: {
		state(id: StackId): Promise<StackState>;
		start(id: StackId): Promise<IpcResult<void>>;
		stop(id: StackId): Promise<IpcResult<void>>;
		onState(cb: (id: StackId, s: StackState) => void): () => void;
	};
	connectors: {
		catalog(): Promise<ConnectorSummary[]>;
		get(id: string): Promise<IpcResult<ConnectorDetail>>;
		/** Validate an instance config (secrets as `${secret:name}` placeholders) against the connector's schema. */
		validate(id: string, config: unknown): Promise<IpcResult<ConnectorValidation>>;
		/** Save an exported YAML through the main process's save dialog; `saved` is false when cancelled. */
		saveYaml(name: string, text: string): Promise<IpcResult<{ saved: boolean }>>;
	};
	/** D675: the agent panel. The loop runs in main; keys never cross IPC. */
	chat: {
		providers(): Promise<ChatProviderInfo[]>;
		/** An empty or missing `apiKey` keeps the stored key. */
		configureProvider(
			id: ChatProviderId,
			cfg: { baseUrl?: string; model: string; apiKey?: string },
		): Promise<IpcResult<ChatProviderInfo>>;
		list(): Promise<ChatSummary[]>;
		get(chatId: string): Promise<IpcResult<ChatView>>;
		create(opts?: {
			provider?: ChatProviderId;
			model?: string;
		}): Promise<IpcResult<ChatSummary>>;
		/** Starts a turn; progress arrives through onEvent. */
		send(
			chatId: string,
			text: string,
			opts?: ChatSendOptions,
		): Promise<IpcResult<void>>;
		cancel(chatId: string): Promise<void>;
		approve(
			chatId: string,
			callId: string,
			decision: ChatApproval,
		): Promise<IpcResult<void>>;
		remove(chatId: string): Promise<IpcResult<void>>;
		onEvent(cb: (e: ChatEvent) => void): () => void;
	};
}
export const CH = {
	serversList: "servers:list",
	serversAdd: "servers:add",
	serversRemove: "servers:remove",
	serversActivate: "servers:activate",
	engineState: "engine:state",
	engineStart: "engine:start",
	engineStop: "engine:stop",
	engineLogs: "engine:logs",
	engineEvent: "engine:event",
	factoryList: "factory:list",
	factoryConfigure: "factory:configure",
	factoryTest: "factory:test",
	factoryRemove: "factory:remove",
	factoryQuery: "factory:query",
	factoryOpen: "factory:open",
	factoryClose: "factory:close",
	factoryShowEmbedded: "factory:show-embedded",
	factoryHideEmbedded: "factory:hide-embedded",
	factoryReloadEmbedded: "factory:reload-embedded",
	factoryPopOut: "factory:pop-out",
	shellOpenExternal: "shell:open-external",
	shellNotify: "shell:notify",
	shellClipboard: "shell:clipboard",
	shellNavigate: "shell:navigate",
	shellPendingNav: "shell:pending-nav",
	shellBadge: "shell:badge",
	updateState: "update:state",
	updateCheck: "update:check",
	updateDownload: "update:download",
	updateInstall: "update:install",
	stacksState: "stacks:state",
	stacksStart: "stacks:start",
	stacksStop: "stacks:stop",
	stacksEvent: "stacks:event",
	connectorsCatalog: "connectors:catalog",
	connectorsGet: "connectors:get",
	connectorsValidate: "connectors:validate",
	connectorsSaveYaml: "connectors:save-yaml",
	chatProviders: "chat:providers",
	chatConfigureProvider: "chat:configure-provider",
	chatList: "chat:list",
	chatGet: "chat:get",
	chatCreate: "chat:create",
	chatSend: "chat:send",
	chatCancel: "chat:cancel",
	chatApprove: "chat:approve",
	chatRemove: "chat:remove",
	chatEvent: "chat:event",
} as const;

// ---- D675: the agent panel ----

export type ChatStopReason =
	| "end_turn"
	| "iteration_cap"
	| "wall_clock_budget"
	| "token_budget"
	| "llm_error"
	| "cancelled";
export type ChatEvent =
	| { kind: "delta"; chatId: string; text: string }
	| { kind: "thinking"; chatId: string; text: string }
	| {
			kind: "tool_call";
			chatId: string;
			callId: string;
			tool: string;
			args: unknown;
			risk: "read" | "write";
			needsApproval: boolean;
	  }
	| {
			kind: "tool_result";
			chatId: string;
			callId: string;
			ok: boolean;
			text: string;
	  }
	| {
			kind: "done";
			chatId: string;
			stop: ChatStopReason;
			usage: { inputTokens: number; outputTokens: number };
	  }
	| { kind: "error"; chatId: string; message: string };
export type ChatProviderId = "anthropic" | "deepseek" | "openai" | "ollama";
export type ChatApproval = "once" | "always" | "deny";
export interface ChatProviderInfo {
	id: ChatProviderId;
	label: string;
	/** The wire protocol: Anthropic Messages or OpenAI-compatible chat completions. */
	kind: "anthropic" | "openai";
	baseUrl: string;
	model: string;
	defaultModel: string;
	needsKey: boolean;
	/** True when a key is stored (the key itself never leaves main). */
	hasKey: boolean;
	/** Ready to use: a key is stored, or none is needed. */
	configured: boolean;
	/** False when the vault has no encryption backend: the key lasts for this session only. */
	persistent: boolean;
}
/** One block of a stored message. Tool results are plain text, never HTML. */
export type ChatPart =
	| { type: "text"; text: string }
	| { type: "thinking"; text: string; signature?: string }
	| { type: "redacted_thinking"; data: string }
	| { type: "tool_use"; id: string; name: string; input: unknown }
	| { type: "tool_result"; toolUseId: string; text: string; isError?: boolean };
export interface ChatMessage {
	role: "user" | "assistant";
	content: ChatPart[];
	at: number;
	/** On the last assistant message of a turn. */
	stop?: ChatStopReason;
}
export interface ChatSummary {
	id: string;
	title: string;
	createdAt: number;
	updatedAt: number;
	provider: ChatProviderId;
	model: string;
}
export interface ChatRecord extends ChatSummary {
	/** Tools the user chose "Always for this chat" for. */
	alwaysAllow: string[];
	messages: ChatMessage[];
}
export interface ChatView extends ChatRecord {
	running: boolean;
	/** Write calls waiting for a decision (survives a renderer reload). */
	pending: {
		callId: string;
		tool: string;
		args: unknown;
		risk: "read" | "write";
	}[];
}
export interface ChatSendOptions {
	/** Switch this chat's provider/model before the turn. */
	provider?: ChatProviderId;
	model?: string;
	/** A short hint added to the system prompt, e.g. "The user is viewing Postgres › Branches." */
	context?: string;
}
