package dev.loams.test.Support

import dev.loams.Json
import java.io.File

/**
 * The conformance report: what the suite writes, and where.
 *
 * `sdks/conformance/required.mjs` is the authority. A suite writes
 * `sdks/fixtures/results/kotlin.json`:
 *
 *     { "tests": [...], "ran": [...], "skipped": [{ "fixture": "…", "reason": "…" }] }
 *
 * and `ran` is the only thing that counts: "a test that passes without touching a
 * required fixture has not run it." So the report here is written from what the
 * corpus driver **executed and checked**, never from a list, and a fixture that
 * could not be reached is absent from `ran` rather than skipped — because
 * `maySkip()` in `required.mjs` permits exactly one skip, a fixture marked
 * `transport: grpc-only` on the Connect-unary fallback transport, and this SDK is
 * not on that fallback: it speaks Connect and gRPC-Web over HTTP, so no fixture is
 * `grpc-only` from its point of view and `skipped` is empty by construction (D656).
 *
 * ## The report is generated, never committed
 *
 * `sdks/fixtures/.gitignore` ignores `results/`, byte-identical to the C++ and C#
 * branches. The file on disk is regenerated by every run and is deliberately not
 * in the repository, so a stale report cannot vouch for a run that never happened
 * — which is the second of `run-test.sh`'s two anti-vacuity changes (D651).
 */
object ConformanceReport {
    /**
     * The six canonical test names, in the order `REQUIRED_TESTS` states them.
     *
     * These literals are the contract: `sdks/conformance/check-languages.mjs`
     * greps this suite's **source** for them, and `kotlin_conformance_test_names_exist`
     * asserts the set cannot shrink. They are written out rather than derived from
     * the method names so a rename is a visible edit here rather than a silent
     * change in a grep's result.
     */
    val REQUIRED_TEST_NAMES: List<String> = listOf(
        "kotlin_conformance_all_required_fixtures",
        "kotlin_retry_reuses_idempotency_key",
        "kotlin_error_reason_mapping",
        "kotlin_stream_resume_with_cursor",
        "kotlin_token_source_refresh",
        "kotlin_pagination_iterator",
    )

    /** Where the report goes, relative to the repository root. */
    const val REPORT_PATH = "sdks/fixtures/results/kotlin.json"

    /**
     * `transport` is `connect` rather than `connect-unary`: the SDK is a Connect
     * client with gRPC-Web also available, and `maySkip()`'s one permitted skip is
     * conditioned on the Connect-unary **fallback** transport that D613 gives Ruby
     * and PHP. This SDK is not a fallback, so a fixture marked `grpc-only` would be
     * a real gap rather than a permitted skip — and recording the transport
     * honestly is what makes the gate say so.
     */
    const val TRANSPORT = "connect"

    /**
     * Writes the report from a run, and returns where it wrote it.
     *
     * `ran` is [CorpusRun.ran] — the fixtures the driver replayed **and** whose
     * assertions all held. A fixture that failed is absent, not folded into
     * coverage: folding a failure into coverage would let a regression buy the
     * points that would have caught it (D656).
     */
    fun write(repositoryRoot: File, run: CorpusRun, tests: List<String>): File {
        val report = Json.JsonObject(
            linkedMapOf(
                "about" to Json.JsonString(
                    "What this SDK's suite ran. `ran` is what `CorpusDriver` replayed through the SDK's " +
                        "public surface and checked against each recording's own `expect` block; a fixture " +
                        "that could not be reached, or whose assertions did not all hold, is absent from it " +
                        "rather than skipped, because sdks/conformance/required.mjs permits exactly one skip " +
                        "(a `transport: grpc-only` fixture on the Connect-unary fallback) and this SDK is not " +
                        "that fallback. GENERATED, never committed: sdks/fixtures/.gitignore ignores results/."
                ),
                "language" to Json.JsonString("kotlin"),
                "transport" to Json.JsonString(TRANSPORT),
                "live" to Json.JsonBoolean(run.live),
                "endpoint" to Json.JsonString(run.endpoint),
                "tests" to Json.JsonArray(tests.map { Json.JsonString(it) }),
                "ran" to Json.JsonArray(run.ran.map { Json.JsonString(it) }),
                "skipped" to Json.JsonArray(emptyList()),
                "failures" to Json.JsonArray(run.failures.map { Json.JsonString(it) }),
            )
        )

        val path = File(repositoryRoot, REPORT_PATH)
        path.parentFile.mkdirs()
        path.writeText(Json.writePretty(report) + "\n")
        return path
    }
}