//! The Go renderer: module `loams.dev/go`'s generated facade (design §44 §7.3,
//! D606).
//!
//! The generated surface is Go's, in the ways design §44 §7.1 names: methods and
//! exported fields are `PascalCase`, a context comes first, and a server stream
//! is a `*connect.ServerStreamForClient[T]` the caller receives from.
//!
//! Every import path and every generated name in here was read off real output.
//! Running `protoc-gen-go` 1.36.11 and `protoc-gen-connect-go` 1.21.0 over
//! `proto/` with buf's managed-mode `go_package_prefix` of `loams.dev/go/gen`
//! writes the messages to `loams/<package>/v1/*.pb.go` (Go package `v1`) and
//! the Connect stubs to `loams/<package>/v1/v1connect/*.connect.go` (Go
//! package `v1connect`), with `<Service>Client` as the client interface and
//! `New<Service>Client(httpClient, baseURL, opts...)` as its constructor. That
//! is what `sdks/go/buf.gen.proto.yaml` configures.
//!
//! Two modules can be facade names for one service (`loams.live` and
//! `loams.tables` are both `loams.live.v1.LiveService`), so the descriptors are
//! listed once.

use std::fmt::Write as _;

use crate::{Call, Model, Module, PackageMap, naming};

/// Renders `facade.go`.
pub fn render(model: &Model, packages: &PackageMap, proto_rev: &str) -> Result<String, String> {
    let mut out = String::new();
    header(&mut out, model, packages, proto_rev)?;
    enums(&mut out);
    reasons(&mut out, model);
    bindings(&mut out, model);
    for module in &model.modules {
        module_interface(&mut out, module, packages)?;
    }
    service_constructors(&mut out, model, packages)?;
    Ok(out)
}

/// The package clause and the imports. The message and client packages are both
/// named after the proto package's last segment (`v1`, `v1connect`), so every
/// one of them needs an alias; the alias is derived from the proto package
/// (`loams.instance.v1` is `instancev1`).
fn header(
    out: &mut String,
    model: &Model,
    packages: &PackageMap,
    proto_rev: &str,
) -> Result<(), String> {
    out.push_str(
        "// @generated by protoc-gen-loams-facade from proto/. DO NOT EDIT.\n\
         //\n\
         // Module: loams.dev/go\n\
         //\n\
         // The SDK facade of design §44 §7.3: one interface per service annotated\n\
         // with `loams.options.v1.module`, one method per `loams.options.v1.facade`\n\
         // call, and the binding table the hand-written runtime dispatches through.\n\
         // Regenerate with `scripts/sdk/gen.sh go`; the drift check in CI fails if\n\
         // this file is stale.\n\
         \n\
         package facade\n\
         \n\
         import (\n\
         \t\"context\"\n\
         \n\
         \t\"connectrpc.com/connect\"\n",
    );
    let mut imports: Vec<(String, String)> = Vec::new();
    for module in &model.modules {
        let path = packages.get(&module.package).ok_or_else(|| {
            format!(
                "{} is not in the package map, so the SDK cannot import its message types",
                module.package
            )
        })?;
        for (alias, import_path) in [
            (alias(&module.package), path.to_owned()),
            (
                format!("{}connect", alias(&module.package)),
                format!("{path}/v1connect"),
            ),
        ] {
            if !imports.iter().any(|(existing, _)| *existing == alias) {
                imports.push((alias, import_path));
            }
        }
    }
    imports.sort();
    for (alias, path) in imports {
        writeln!(out, "\t{alias} \"{path}\"").ok();
    }
    out.push_str(")\n\n");
    writeln!(
        out,
        "// PROTO_REV is the proto revision this SDK was generated from\n\
         // (LOAMS_PROTO_REV, design §44 §10.3). loams.Version() checks it against the\n\
         // server's GetInstance.api_versions.\n\
         const PROTO_REV = \"{proto_rev}\"\n",
    )
    .ok();
    Ok(())
}

/// The three closed sets the binding table is typed with, so a caller
/// switching on one is exhaustive.
fn enums(out: &mut String) {
    out.push_str(
        "// Idempotency is the RPC's `google.protobuf.MethodOptions.idempotency_level`,\n\
         // read out of the descriptor rather than guessed (design §44 §7.4, D610).\n\
         type Idempotency string\n\
         \n\
         const (\n\
         \tIdempotencyNoSideEffects Idempotency = \"no_side_effects\"\n\
         \tIdempotencyIdempotent    Idempotency = \"idempotent\"\n\
         \tIdempotencyNone          Idempotency = \"none\"\n\
         )\n\
         \n\
         // Retry is whether the SDK retries the call on its own: a read and an\n\
         // idempotent RPC do, a mutation only when it carries an idempotency key.\n\
         type Retry string\n\
         \n\
         const (\n\
         \tRetrySafe   Retry = \"safe\"\n\
         \tRetryManual Retry = \"manual\"\n\
         )\n\
         \n\
         // Streaming is the direction a call streams in. The API has no\n\
         // client-streaming and no bidi (D420).\n\
         type Streaming string\n\
         \n\
         const (\n\
         \tStreamingUnary  Streaming = \"unary\"\n\
         \tStreamingServer Streaming = \"server\"\n\
         )\n\
         \n",
    );
}

/// The reason registry, as a type and a table (design §44 §7.4, D611).
fn reasons(out: &mut String, model: &Model) {
    out.push_str(
        "// Reason is a stable, machine-readable cause of a failed RPC: the thing\n\
         // callers branch on, never the message. Within an API major version a\n\
         // reason is never renamed and never removed, so this type only grows.\n\
         type Reason string\n\
         \n",
    );
    out.push_str("// Reasons is every reason in docs/api/reasons.md.\nvar Reasons = []Reason{\n");
    for reason in &model.reasons {
        writeln!(out, "\t\"{}\",", reason.reason).ok();
    }
    out.push_str("}\n\n");
    out.push_str(
        "// ReasonCodes is the Connect code each reason is raised under, from the same\n\
         // registry.\nvar ReasonCodes = map[Reason]string{\n",
    );
    // The values are aligned the way `gofmt` aligns them, so the generated file
    // is already formatted and CI's `gofmt -l` has nothing to say about it.
    let width = model
        .reasons
        .iter()
        .map(|reason| reason.reason.len())
        .max()
        .unwrap_or(0);
    for reason in &model.reasons {
        writeln!(
            out,
            "\t\"{}\": {}\"{}\",",
            reason.reason,
            " ".repeat(width - reason.reason.len()),
            reason.code
        )
        .ok();
    }
    out.push_str("}\n\n");
    out.push_str(
        "// FeatureNotInVariant is the reason a package the build variant does not\n\
        // carry answers with (design §44 §4, D600). Every RPC of such a package\n\
        // refuses with it and names the variant in metadata.variant; the runtime\n\
        // turns that refusal into a FeatureNotInVariantError, and\n\
        // loams.System.Available answers the same question from\n\
        // GetInstance.services[] without a failing call.\n\
        const FeatureNotInVariant Reason = \"feature_not_in_variant\"\n\
        \n\
        // ProtoPackages is every proto package this SDK speaks, as\n\
        // GetInstance.api_versions names them.\n\
        var ProtoPackages = []string{\n",
    );
    for package in &model.packages {
        writeln!(out, "\t\"{package}\",").ok();
    }
    out.push_str("}\n\n");
}

/// The binding table: the runtime's whole view of what the SDK can call.
fn bindings(out: &mut String, model: &Model) {
    out.push_str(
        "// Pagination is AIP-158 paging, named by FacadeOptions.pagination.\n\
         type Pagination struct {\n\
         \t// Items is the repeated field the iterator yields.\n\
         \tItems string\n\
         \t// NextPageToken goes in on the next call and comes out on this one.\n\
         \tNextPageToken string\n\
         }\n\
         \n\
         // CallBinding is one facade call, as the runtime dispatches it.\n\
         type CallBinding struct {\n\
         \t// Module is the module the call is exposed on.\n\
         \tModule string\n\
         \t// Name is the call's name in Go case.\n\
         \tName string\n\
         \t// ProtoName is the name FacadeOptions gave it, in snake_case.\n\
         \tProtoName string\n\
         \t// Method is the method that backs the call.\n\
         \tMethod string\n\
         \t// RPC is the RPC as package.Service/Method, which is the path curl and\n\
         \t// grpcurl use.\n\
         \tRPC     string\n\
         \tService string\n\
         \tPackage string\n\
         \t// Idempotency, Retry and Streaming come from the proto, not from a guess.\n\
         \tIdempotency Idempotency\n\
         \tRetry       Retry\n\
         \tStreaming   Streaming\n\
         \tPagination  *Pagination\n\
         }\n\
         \n\
         // ModuleBinding is one SDK module and its calls.\n\
         type ModuleBinding struct {\n\
         \tName    string\n\
         \tSummary string\n\
         \tService string\n\
         \tPackage string\n\
         \t// Unstable reports that the package's wire contract may still change.\n\
         \tUnstable bool\n\
         \t// Derived is true for a second facade name for the same RPCs, which\n\
         \t// has no summary of its own.\n\
         \tDerived bool\n\
         \tCalls   []CallBinding\n\
         }\n\
         \n\
         // Modules is every annotated service, as the module catalogue. Order is by\n\
         // module name.\n\
         var Modules = []ModuleBinding{\n",
    );
    for module in &model.modules {
        writeln!(
            out,
            "\t{{\n\t\tName:     \"{name}\",\n\t\tSummary:  \"{summary}\",\n\t\tService:  \"{service}\",\n\t\tPackage:  \"{package}\",\n\t\tUnstable: {unstable},\n\t\tDerived:  {derived},\n\t\tCalls: []CallBinding{{",
            name = escape(&module.name),
            summary = escape(&module.summary),
            service = module.service,
            package = module.package,
            unstable = module.unstable,
            derived = module.derived,
        )
        .ok();
        for call in &module.calls {
            let pagination = match &call.pagination {
                Some(paging) => format!(
                    "&Pagination{{Items: \"{items}\", NextPageToken: \"{token}\"}}",
                    items = escape(&paging.items),
                    token = escape(&paging.next_page_token),
                ),
                None => "nil".to_owned(),
            };
            writeln!(
                out,
                "\t\t\t{{Module: \"{module}\", Name: \"{name}\", ProtoName: \"{proto}\", Method: \"{method}\", RPC: \"{rpc}\", Service: \"{service}\", Package: \"{package}\", Idempotency: {idempotency}, Retry: {retry}, Streaming: {streaming}, Pagination: {pagination}}},",
                module = escape(&call.module),
                name = go_name(&call.name),
                proto = escape(&call.name),
                method = call.method,
                rpc = call.rpc(),
                service = call.service,
                package = call.package,
                idempotency = go_idempotency(call.idempotency),
                retry = go_retry(call.retry),
                streaming = go_streaming(call.streaming),
            )
            .ok();
        }
        out.push_str("\t\t},\n\t},\n");
    }
    out.push_str("}\n\n");
}

/// One module's interface: its constants and one method per facade call.
fn module_interface(
    out: &mut String,
    module: &Module,
    packages: &PackageMap,
) -> Result<(), String> {
    let name = naming::type_name(&module.name);
    let unstable_note = if module.unstable {
        " Its wire contract may still change, so buf breaking skips it and an SDK marks it experimental (§44 §10.3)."
    } else {
        ""
    };
    let about = if module.derived {
        format!(
            "is a second facade name for the same RPCs, exposed as loams.{name}.",
            name = module.name
        )
    } else {
        format!(
            "is loams.{name} — {summary}",
            name = module.name,
            summary = module.summary
        )
    };
    writeln!(
        out,
        "// {name}Module {about}\n//\n// It wraps {service}.{unstable}\ntype {name}Module interface {{\n\t// Module is the SDK module, as it appears on loams.{module}.\n\tModule() string\n\t// Service is the service behind the module.\n\tService() string\n\t// Unstable reports that the package's wire contract may still change.\n\tUnstable() bool\n",
        name = name,
        about = about,
        service = module.service,
        unstable = unstable_note,
        module = module.name,
    )
    .ok();
    for call in &module.calls {
        out.push_str(&call_signature(call, packages)?);
    }
    out.push_str("}\n\n");
    Ok(())
}

/// One call's Go signature, as it appears in the generated file.
pub fn call_signature(call: &Call, packages: &PackageMap) -> Result<String, String> {
    let name = go_name(&call.name);
    let input = qualified(&call.input, packages)?;
    let output = qualified(&call.output, packages)?;
    let returns = if call.streaming == crate::Streaming::Server {
        format!("(*connect.ServerStreamForClient[{output}], error)")
    } else {
        format!("(*connect.Response[{output}], error)")
    };
    Ok(format!(
        "\t// {name} calls {rpc}, retried: {retry}.{paging}\n\t{name}(ctx context.Context, req *connect.Request[{input}], opts *CallOptions) {returns}\n",
        name = name,
        rpc = call.rpc(),
        retry = call.retry.as_str(),
        paging = match &call.pagination {
            Some(paging) => format!(
                " AIP-158: page with {items} and follow {token} through loams.Paginate.",
                items = naming::exported(&paging.items),
                token = naming::exported(&paging.next_page_token),
            ),
            None => String::new(),
        },
    ))
}

/// The constructor of each generated Connect client, by fully qualified
/// service name, so the runtime builds a module's client without a hand-written
/// switch per language module.
///
/// A Go map cannot hold the constructors: each returns its own generated
/// interface type, and `any` would lose the type. A switch returns the
/// interface value, which is exactly what the runtime stores, and the compiler
/// checks every constructor's signature at generation time.
fn service_constructors(
    out: &mut String,
    model: &Model,
    packages: &PackageMap,
) -> Result<(), String> {
    let mut services: Vec<&str> = model
        .modules
        .iter()
        .map(|module| module.service.as_str())
        .collect();
    services.sort();
    services.dedup();
    out.push_str(
        "// NewServiceClient builds the Connect client for a service, by fully\n\
         // qualified name, and returns it as the generated <Service>Client interface.\n\
         // It returns nil for a service this SDK does not speak.\n\
         func NewServiceClient(name string, httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) any {\n\
         \tswitch name {\n",
    );
    for service in services {
        let package = naming::package_of(service);
        if packages.get(package).is_none() {
            // A service whose package is not in the map cannot be constructed,
            // and `module_interface` has already failed for it.
            continue;
        }
        let base = naming::pascal(naming::leaf(service));
        writeln!(
            out,
            "\tcase \"{service}\":\n\t\treturn {alias}connect.New{base}Client(httpClient, baseURL, opts...)\n",
            service = service,
            alias = alias(package),
            base = base,
        )
        .ok();
    }
    out.push_str(
        "\tdefault:\n\t\treturn nil\n\t}\n}\n",
    );
    Ok(())
}

/// A fully qualified proto message as the Go path for it: the aliased import
/// and the leaf, e.g. `instancev1.GetInstanceRequest`.
fn qualified(full: &str, packages: &PackageMap) -> Result<String, String> {
    if full.is_empty() {
        return Err("a method has no message type".to_owned());
    }
    let package = naming::package_of(full);
    if !packages
        .get(package)
        .is_some_and(|path| path.starts_with("loams.dev/go/"))
    {
        return Err(format!("{package} is not in the package map"));
    }
    Ok(format!("{}.{}", alias(package), naming::leaf(full)))
}

/// The import alias for a proto package: `loams.instance.v1` is `instancev1`,
/// `loams.live.v1` is `livev1`. The generated Go packages are both called `v1`,
/// so without this every import would collide. The alias is the package's own
/// path without its leading `loams`, which is also what a reader expects to see
/// in `instancev1.GetInstanceRequest`.
fn alias(package: &str) -> String {
    let rest: Vec<&str> = package.split('.').skip(1).collect();
    if rest.is_empty() {
        return naming::pascal(package);
    }
    rest.concat().to_lowercase()
}

/// A call's name in Go case: `get_instance` is `GetInstance`.
fn go_name(name: &str) -> String {
    naming::pascal(name)
}

fn go_idempotency(idempotency: crate::Idempotency) -> &'static str {
    match idempotency {
        crate::Idempotency::NoSideEffects => "IdempotencyNoSideEffects",
        crate::Idempotency::Idempotent => "IdempotencyIdempotent",
        crate::Idempotency::None => "IdempotencyNone",
    }
}

fn go_retry(retry: crate::Retry) -> &'static str {
    match retry {
        crate::Retry::Safe => "RetrySafe",
        crate::Retry::Manual => "RetryManual",
    }
}

fn go_streaming(streaming: crate::Streaming) -> &'static str {
    match streaming {
        crate::Streaming::Unary => "StreamingUnary",
        crate::Streaming::Server => "StreamingServer",
    }
}

/// A string literal body: quotes and backslashes escaped, so a summary with a
/// quote cannot break the generated file.
fn escape(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_import_alias_comes_from_the_package() {
        assert_eq!(alias("loams.instance.v1"), "instancev1");
        assert_eq!(alias("loams.live.v1"), "livev1");
        assert_eq!(alias("loams.admin.v1"), "adminv1");
        // A package with more segments still gets one collision-free alias.
        assert_eq!(alias("loams.admin.org.v1"), "adminorgv1");
    }

    #[test]
    fn a_call_name_is_pascal_case() {
        assert_eq!(go_name("get_instance"), "GetInstance");
        assert_eq!(go_name("who_am_i"), "WhoAmI");
    }

    #[test]
    fn escapes_a_summary_with_a_quote() {
        assert_eq!(escape("say \"hi\""), "say \\\"hi\\\"");
    }
}