//! The Python renderer: the `loams` SDK's generated facade (design §44 §7.3,
//! D606).
//!
//! The split §44 §7.3 draws is the same here as in the TypeScript renderer: the
//! **facade** is generated (one `Protocol` per annotated service, one method
//! per `FacadeOptions` call, the binding table the runtime dispatches through,
//! and the reason union), and the **runtime** is hand-written once (transport,
//! token sources, retry, error mapping, token store, pagination, streams).
//!
//! Two shapes are generated for every module because the Python SDK has both a
//! sync and an async client (SDK2 Task 1): `<Name>Module` for
//! `ConnectClient` and `<Name>ModuleSync` for `ConnectClientSync`. They differ
//! only in whether a call is awaited and whether a stream is an
//! `AsyncIterator` or an `Iterator` — design §44 §7.1's rule that a stream is
//! the language's native iteration, twice.
//!
//! Everything in the generated file's imports is what the pinned generators
//! actually write. Running `protoc --python_out --connectrpc_out` over `proto/`
//! with `protoc-gen-connectrpc` 0.12.1 produces
//! `loams/<package path>/<file>_pb2.py` for the messages and
//! `loams/<package path>/<file>_connect.py` for the clients, and the client
//! classes are `<Service>Client` and `<Service>ClientSync`. That was checked by
//! running the plugins, not inferred.

use std::fmt::Write as _;

use crate::{Call, Model, Module, PackageMap, naming};

/// The hand-written runtime module the generated surface names, imported
/// absolutely so the generated file reads the same wherever it is placed inside
/// the `loams` package. §44 §7.3 splits the SDK into the generated facade and
/// the hand-written runtime; these are the runtime's types.
///
/// `CallOptions` is named from where it is *defined*, not where it happens to be
/// re-exported. `loams.runtime.call` only re-exports it, and importing through
/// the re-export means the facade appears to depend on the whole call machinery
/// -- which imports the facade, so that dependency has to stay type-only, and
/// mypy rejects importing a name a module does not explicitly export.
const OPTIONS: &str = "loams.runtime.options";

/// Renders `facade.py`.
pub fn render(model: &Model, packages: &PackageMap, rev: &str) -> Result<String, String> {
    let mut out = String::new();
    header(&mut out);
    imports(&mut out, model, packages)?;
    proto_rev(&mut out, rev);
    reasons(&mut out, model);
    bindings(&mut out, model);
    for module in &model.modules {
        module_protocols(&mut out, module, packages)?;
    }
    Ok(out)
}

/// The file header: a generated-code marker, the module docstring, the imports
/// and the proto revision (`LOAMS_PROTO_REV`, design §44 §10.3).
///
/// Emitted statement by statement rather than as one literal: Python's ordering
/// rules are strict — the docstring must precede `from __future__ import`, and
/// every import must precede the first assignment — so a single block would be
/// easy to break by moving one line.
fn header(out: &mut String) {
    out.push_str(
        "# @generated by protoc-gen-loams-facade from proto/. Do not edit.\n\
         #\n\
         # The SDK facade of design §44 §7.3: one Protocol per service annotated\n\
         # with `loams.options.v1.module`, one method per `loams.options.v1.facade`\n\
         # call, and the binding table the hand-written runtime dispatches through.\n\
         # Regenerate with `scripts/sdk/gen.sh python`; the drift check in CI fails\n\
         # if this file is stale.\n\
         # ruff: noqa\n\
         # fmt: off\n\
         \n\
         \"\"\"The `loams` Python SDK's generated facade.\"\"\"\n\
         \n\
         from __future__ import annotations\n\
         \n\
         from collections.abc import AsyncIterator, Iterator\n\
         from dataclasses import dataclass\n\
         from typing import TYPE_CHECKING, ClassVar, Final, Literal, Protocol\n\
         \n\
         import loams\n",
    );
    // Type-only: the runtime imports *this* module's binding table, so a
    // module-level import back into it is a cycle. Every use of CallOptions is
    // an annotation, which `from __future__ import annotations` leaves as a
    // string, so nothing is resolved at import time. LoamsError and
    // ResponseStream were imported here and never referenced.
    writeln!(out, "if TYPE_CHECKING:\n    from {OPTIONS} import CallOptions").ok();
    // Runtime, not type-only: `IDEMPOTENCY_LEVELS` binds `IdempotencyLevel`
    // members at import time, and `Message` is the protobuf base the
    // `MethodInfo` type parameters are declared over.
    writeln!(
        out,
        "from connectrpc.method import IdempotencyLevel, MethodInfo"
    )
    .ok();
    writeln!(out, "from google.protobuf.message import Message").ok();
}

/// The proto revision, which is what `loams.system.version()` checks against the
/// server's `GetInstance.api_versions` (design §44 §10.3).
fn proto_rev(out: &mut String, proto_rev: &str) {
    writeln!(out, "PROTO_REV: Final[str] = \"{proto_rev}\"").ok();
    out.push_str(
        "\"\"\"The proto revision this SDK was generated from (`LOAMS_PROTO_REV`,\n\
         design §44 §10.3). `loams.system.version()` checks it against the server's\n\
         `GetInstance.api_versions`.\"\"\"\n\
         \n",
    );
}

/// One import per proto package: the message types the signatures name and
/// the client classes the runtime builds. Grouped per package and in the order
/// the modules use them, so the file does not churn when a proto is reordered.
fn imports(out: &mut String, model: &Model, packages: &PackageMap) -> Result<(), String> {
    let mut seen: Vec<&str> = Vec::new();
    for module in &model.modules {
        let specifier = packages.get(&module.package).ok_or_else(|| {
            format!(
                "{} is not in the package map, so the SDK cannot import its message types",
                module.package
            )
        })?;
        if seen.contains(&specifier) {
            continue;
        }
        seen.push(specifier);
        writeln!(
            out,
            "from {module} import {names}",
            module = specifier,
            names = package_types(model, &module.package).join(", "),
        )
        .ok();
        // The client module sits beside the messages: protoc-gen-connectrpc
        // writes `<file>_connect.py` next to `<file>_pb2.py`, in the same
        // package directory.
        writeln!(
            out,
            "from {module} import {clients}",
            module = client_module(specifier),
            clients = package_clients(model, &module.package).join(", "),
        )
        .ok();
    }
    out.push('\n');
    Ok(())
}

/// The client module of a message module: `loams.instance.v1.instance_pb2`
/// is `loams.instance.v1.instance_connect`.
fn client_module(messages: &str) -> String {
    match messages.strip_suffix("_pb2") {
        Some(stem) => format!("{stem}_connect"),
        None => messages.to_owned(),
    }
}

/// The message types the facade's signatures name in one package, sorted.
/// `protoc-gen-python` exports every message of a file from that file's `_pb2`
/// module, so the leaf name is the Python name.
fn package_types(model: &Model, package: &str) -> Vec<String> {
    let mut names: Vec<String> = model
        .calls()
        .filter(|call| call.package == package)
        .flat_map(|call| {
            [
                naming::leaf(&call.input).to_owned(),
                naming::leaf(&call.output).to_owned(),
            ]
        })
        .filter(|name| !name.is_empty())
        .collect();
    names.sort();
    names.dedup();
    names
}

/// The Connect client classes one package's services generate. Two modules can
/// be facade names for one service (`loams.live` and `loams.tables` are both
/// `loams.live.v1.LiveService`), so the same pair is listed once.
fn package_clients(model: &Model, package: &str) -> Vec<String> {
    let mut services: Vec<&str> = model
        .modules
        .iter()
        .filter(|module| module.package == package)
        .map(|module| module.service.as_str())
        .collect();
    services.sort();
    services.dedup();
    let mut names = Vec::new();
    for service in services {
        let base = naming::pascal(naming::leaf(service));
        names.push(format!("{base}Client"));
        names.push(format!("{base}ClientSync"));
    }
    names
}

/// The reason registry as a `Literal`, so a caller branching on a reason is
/// exhaustive and a reason the registry has lost stops typechecking
/// (design §44 §7.4, D611).
fn reasons(out: &mut String, model: &Model) {
    out.push_str("Reason = Literal[\n");
    for reason in &model.reasons {
        writeln!(out, "    \"{}\",", reason.reason).ok();
    }
    out.push_str(
        "]\n\
         \"\"\"A stable, machine-readable cause of a failed RPC.\n\
         \n\
         Within an API major version a reason is never renamed and never removed, so\n\
         this literal only grows.\n\
         \"\"\"\n\n\
         REASONS: Final[tuple[Reason, ...]] = (\n",
    );
    for reason in &model.reasons {
        writeln!(out, "    \"{}\",", reason.reason).ok();
    }
    out.push_str(
        ")\n\n\
         #: The Connect code each reason is raised under, from the same registry.\n\
         REASON_CODES: Final[dict[Reason, str]] = {\n",
    );
    for reason in &model.reasons {
        writeln!(out, "    \"{}\": \"{}\",", reason.reason, reason.code).ok();
    }
    out.push_str(
        "}\n\n\
         #: The reason a package the build variant does not carry answers with\n\
         #: (design §44 §4, D600). Every RPC of such a package refuses with it and\n\
         #: names the variant in `metadata.variant`; the runtime turns that refusal\n\
         #: into a `FeatureNotInVariantError`, so `loams.system.available()` answers\n\
         #: the same question from `GetInstance.services[]` without a failing call.\n\
         FEATURE_NOT_IN_VARIANT: Final[Reason] = \"feature_not_in_variant\"\n\
         \n\
         #: The reason a rejected access token answers with. Named for the same\n\
         #: reason as `FEATURE_NOT_IN_VARIANT`: `REASONS` carries every reason, but\n\
         #: the runtime compares against this one on the token path, and\n\
         #: `runtime/errors.py` imports it by name.\n\
         TOKEN_EXPIRED: Final[Reason] = \"token_expired\"\n\
         \n\
         Idempotency = Literal[\"no_side_effects\", \"idempotent\", \"none\"]\n\
         Retry = Literal[\"safe\", \"manual\"]\n\
         Streaming = Literal[\"unary\", \"server\"]\n\
         \n",
    );
    out.push_str("PROTO_PACKAGES: Final[tuple[str, ...]] = (\n");
    for package in &model.packages {
        writeln!(out, "    \"{package}\",").ok();
    }
    out.push_str(")\n\n");
}

/// The binding table: the runtime's whole view of what the SDK can call.
fn bindings(out: &mut String, model: &Model) {
    out.push_str(
        "@dataclass(frozen=True, slots=True)\n\
         class Pagination:\n\
         \x20\x20\x20\x20\"\"\"AIP-158 paging, named by `FacadeOptions.pagination`.\"\"\"\n\
         \n\
         \x20\x20\x20\x20items: str\n\
         \x20\x20\x20\x20next_page_token: str\n\
         \n\
         \n",
    );
    out.push_str(
        "@dataclass(frozen=True, slots=True)\n\
         class CallBinding:\n\
         \x20\x20\x20\x20\"\"\"One facade call, as the runtime dispatches it.\"\"\"\n\
         \n\
         \x20\x20\x20\x20#: The module the call is exposed on.\n\
         \x20\x20\x20\x20module: str\n\
         \x20\x20\x20\x20#: The call's name, in `snake_case`.\n\
         \x20\x20\x20\x20name: str\n\
         \x20\x20\x20\x20#: The name `FacadeOptions` gave it, in `snake_case`.\n\
         \x20\x20\x20\x20proto_name: str\n\
         \x20\x20\x20\x20#: The method that backs the call.\n\
         \x20\x20\x20\x20method: str\n\
         \x20\x20\x20\x20#: The RPC, as `package.Service/Method`, which is the path curl and grpcurl use.\n\
         \x20\x20\x20\x20rpc: str\n\
         \x20\x20\x20\x20service: str\n\
         \x20\x20\x20\x20package: str\n\
         \x20\x20\x20\x20idempotency: Idempotency\n\
         \x20\x20\x20\x20retry: Retry\n\
         \x20\x20\x20\x20streaming: Streaming\n\
         \x20\x20\x20\x20pagination: Pagination | None\n\
         \n\
         \n",
    );
    out.push_str(
        "@dataclass(frozen=True, slots=True)\n\
         class ModuleBinding:\n\
         \x20\x20\x20\x20\"\"\"One SDK module and its calls.\"\"\"\n\
         \n\
         \x20\x20\x20\x20name: str\n\
         \x20\x20\x20\x20summary: str\n\
         \x20\x20\x20\x20service: str\n\
         \x20\x20\x20\x20package: str\n\
         \x20\x20\x20\x20unstable: bool\n\
         \x20\x20\x20\x20#: True for a second facade name for the same RPCs, which has no summary of its own.\n\
         \x20\x20\x20\x20derived: bool\n\
         \x20\x20\x20\x20calls: tuple[CallBinding, ...]\n\
         \n\
         \n",
    );
    out.push_str(
        "#: Every annotated service, as the module catalogue. Order is by module name.\n\
         MODULES: Final[tuple[ModuleBinding, ...]] = (\n",
    );
    for module in &model.modules {
        writeln!(
            out,
            "    ModuleBinding(\n        name=\"{name}\",\n        summary=\"{summary}\",\n        service=\"{service}\",\n        package=\"{package}\",\n        unstable={unstable},\n        derived={derived},\n        calls=(",
            name = escape(&module.name),
            summary = escape(&module.summary),
            service = module.service,
            package = module.package,
            unstable = python_bool(module.unstable),
            derived = python_bool(module.derived),
        )
        .ok();
        for call in &module.calls {
            let pagination = match &call.pagination {
                Some(paging) => format!(
                    "Pagination(items=\"{items}\", next_page_token=\"{token}\")",
                    items = escape(&paging.items),
                    token = escape(&paging.next_page_token),
                ),
                None => "None".to_owned(),
            };
            writeln!(
                out,
                "            CallBinding(\n                module=\"{module}\",\n                name=\"{name}\",\n                proto_name=\"{proto}\",\n                method=\"{method}\",\n                rpc=\"{rpc}\",\n                service=\"{service}\",\n                package=\"{package}\",\n                idempotency=\"{idempotency}\",\n                retry=\"{retry}\",\n                streaming=\"{streaming}\",\n                pagination={pagination},\n            ),",
                module = escape(&call.module),
                name = escape(&naming::snake(&call.name)),
                proto = escape(&call.name),
                method = call.method,
                rpc = call.rpc(),
                service = call.service,
                package = call.package,
                idempotency = call.idempotency.as_str(),
                retry = call.retry.as_str(),
                streaming = call.streaming.as_str(),
            )
            .ok();
        }
        out.push_str("        ),\n    ),\n");
    }
    out.push_str(")\n\n");
    methods_table(out, model).ok();
}

/// ``IDEMPOTENCY_LEVELS`` and ``METHODS``.
///
/// `connect-python` dispatches on a `MethodInfo` rather than on a generated
/// client class, so this table is the whole of the generated stub surface the
/// runtime needs -- no `_pb2_grpc.py` is generated or imported. The hand-written
/// runtime imports `METHODS` and `IDEMPOTENCY_LEVELS` by name, so without them
/// the package does not import at all.
fn methods_table(out: &mut String, model: &Model) -> Result<(), String> {
    out.push_str(
        "#: The Connect idempotency level each declared idempotency maps to, so a\n\
         #: binding can become a `MethodInfo` without the runtime guessing.\n\
         IDEMPOTENCY_LEVELS: Final[dict[str, IdempotencyLevel]] = {\n\
         \x20   \"no_side_effects\": IdempotencyLevel.NO_SIDE_EFFECTS,\n\
         \x20   \"idempotent\": IdempotencyLevel.IDEMPOTENT,\n\
         \x20   \"none\": IdempotencyLevel.UNKNOWN,\n\
         }\n\n\
         #: One ``MethodInfo`` per call, keyed by ``package.Service/Method``.\n\
         METHODS: Final[dict[str, MethodInfo[Message, Message]]] = {\n",
    );
    for module in &model.modules {
        for call in &module.calls {
            let input = message_ref(&call.package, &call.input);
            let output = message_ref(&call.package, &call.output);
            writeln!(
                out,
                "    \"{rpc}\": MethodInfo(\n\
                 \x20       name=\"{method}\",\n\
                 \x20       service_name=\"{service}\",\n\
                 \x20       input={input},\n\
                 \x20       output={output},\n\
                 \x20       idempotency_level=IDEMPOTENCY_LEVELS[\"{idempotency}\"],\n\
                 \x20   ),",
                rpc = escape(&call.rpc()),
                method = escape(&call.method),
                service = escape(&call.service),
                input = input,
                output = output,
                idempotency = escape(call.idempotency.as_str()),
            )
            .ok();
        }
    }
    out.push_str("}\n");
    Ok(())
}

/// A generated message class as Python writes it: the bare name, because the
/// header already imports every message the protocols name from the `_pb2`
/// module protoc emitted for its proto file. Spelling out the module would mean
/// deriving the proto file's stem here, and the package's version segment is
/// not it — `loams.instance.v1` is emitted as `instance_pb2`, not `v1_pb2`.
fn message_ref(_package: &str, message: &str) -> String {
    message.rsplit('.').next().unwrap_or(message).to_string()
}

/// One module's two protocols: the async client and the sync one.
fn module_protocols(
    out: &mut String,
    module: &Module,
    packages: &PackageMap,
) -> Result<(), String> {
    let module_name = naming::type_name(&module.name);
    let service = module.service.clone();
    let unstable_note = if module.unstable {
        " Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3)."
    } else {
        ""
    };
    let about = if module.derived {
        format!(
            "A second facade name for the same RPCs, exposed as `loams.{name}`.",
            name = module.name
        )
    } else {
        format!(
            "`loams.{name}` — {summary}",
            name = module.name,
            summary = module.summary
        )
    };
    for sync in [false, true] {
        let suffix = if sync { "Sync" } else { "" };
        writeln!(
            out,
            "class {module_name}Module{suffix}(Protocol):\n    \"\"\"{about}\n\n    Wraps `{service}`.{unstable}\n    \"\"\"\n",
            about = about,
            service = service,
            unstable = unstable_note,
        )
        .ok();
        writeln!(
            out,
            "    module: ClassVar[Literal[\"{name}\"]]\n    service: ClassVar[Literal[\"{service}\"]]\n    unstable: ClassVar[Literal[{unstable}]]",
            name = module.name,
            service = service,
            unstable = python_bool(module.unstable),
        )
        .ok();
        for call in &module.calls {
            let signature = if sync {
                call_signature_sync(call, packages)?
            } else {
                call_signature(call, packages)?
            };
            out.push_str(&signature);
        }
        out.push_str("\n\n");
    }
    Ok(())
}

/// One call's async signature, as it appears in the generated file.
///
/// A server stream is *not* a coroutine: `LiveServiceClient.watch` returns an
/// `AsyncIterator` directly, so the method that wraps it is a plain `def`.
pub fn call_signature(call: &Call, packages: &PackageMap) -> Result<String, String> {
    signature(call, packages, false)
}

/// One call's sync-client signature.
pub fn call_signature_sync(call: &Call, packages: &PackageMap) -> Result<String, String> {
    signature(call, packages, true)
}

fn signature(call: &Call, packages: &PackageMap, sync: bool) -> Result<String, String> {
    let input = qualified(&call.input, packages)?;
    let output = qualified(&call.output, packages)?;
    let streaming = call.streaming == crate::Streaming::Server;
    let (prefix, iterator) = if sync {
        ("", "Iterator")
    } else {
        ("async ", "AsyncIterator")
    };
    let returns = if streaming {
        format!("{iterator}[{output}]")
    } else {
        output
    };
    let doc = call_doc(call);
    let keyword = if streaming { "" } else { "await " };
    let head = if streaming {
        format!("    def {name}(\n", name = naming::snake(&call.name))
    } else {
        format!(
            "    {prefix}def {name}(\n",
            name = naming::snake(&call.name)
        )
    };
    let _ = keyword;
    Ok(format!(
        "    \"\"\"{doc}\n    \"\"\"\n{head}        self,\n        request: {input},\n        *,\n        options: CallOptions | None = None,\n    ) -> {returns}:\n        ...\n\n",
    ))
}

/// The doc comment of one call: the RPC it is, whether the SDK retries it, and
/// how it pages. The retry class comes from the proto's idempotency level, not
/// from a guess (design §44 §7.4, D610).
fn call_doc(call: &Call) -> String {
    let mut doc = format!(
        "`{service}/{method}`, retried: {retry}.",
        service = call.service,
        method = call.method,
        retry = call.retry.as_str(),
    );
    if let Some(paging) = &call.pagination {
        doc.push_str(&format!(
            " AIP-158: page with `{}` and follow `{}` through `loams.paginate`.",
            paging.items, paging.next_page_token
        ));
    }
    doc
}

/// A fully qualified proto message as the Python name for it: the module the
/// generated messages live in, and the leaf.
fn qualified(full: &str, packages: &PackageMap) -> Result<String, String> {
    if full.is_empty() {
        return Err("a method has no message type".to_owned());
    }
    let package = naming::package_of(full);
    let Some(module) = packages.get(package) else {
        return Err(format!("{package} is not in the package map"));
    };
    Ok(format!("{}.{}", module, naming::leaf(full)))
}

/// A Rust-style `true`/`false`, which Python spells the same way but a
/// generated file must not inherit a language's default.
fn python_bool(value: bool) -> &'static str {
    if value { "True" } else { "False" }
}

/// A string literal body: quotes and backslashes escaped, so a summary with an
/// apostrophe cannot break the generated file.
fn escape(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_a_summary_with_a_quote() {
        assert_eq!(escape("say \"hi\""), "say \\\"hi\\\"");
        assert_eq!(escape("a \\ backslash"), "a \\\\ backslash");
    }

    #[test]
    fn a_bool_is_python_spelled() {
        assert_eq!(python_bool(true), "True");
        assert_eq!(python_bool(false), "False");
    }
}
