//! The Rust renderer: crate `loams`'s generated facade (design §44 §7.3, D606).
//!
//! Rust is the one language here whose stubs are **not** made by a buf remote
//! plugin. D128 made the Rust SDK the server's stack: `crates/loams-proto/build.rs`
//! already generates the `loams.*.v1` types, the service traits and the clients
//! with `connectrpc-build` 0.9.0 from `proto/`, in a `build.rs`, so
//! `sdks/rust/buf.gen.yaml` runs the facade plugin alone and there is no
//! `buf.build/connectrpc/rust` to pin. `tonic` is not used anywhere in the Rust
//! SDK's surface (`golden_rust` checks that).
//!
//! Because the generated types come from the SDK's own build, the facade names
//! them by their crate path — `loams_proto::loams::instance::v1::GetInstanceRequest` —
//! which is what `crates/loams-live-proto/tests/roundtrip.rs` imports today.
//!
//! Three types are named in the generated traits that the generator does not
//! emit, because they are the runtime's and not the wire's: `CallOptions`,
//! `LoamsError` and `ResponseStream<T>`. They are the hand-written half of
//! §44 §7.3's split, and the SDK crate provides them next to this file.

use std::fmt::Write as _;

use crate::{Call, Model, Module, PackageMap, naming};

/// Renders `facade.rs`.
pub fn render(model: &Model, packages: &PackageMap, proto_rev: &str) -> Result<String, String> {
    let mut out = String::new();
    header(&mut out, proto_rev);
    enums(&mut out);
    reasons(&mut out, model);
    bindings(&mut out, model);
    for module in &model.modules {
        module_trait(&mut out, module, packages)?;
    }
    Ok(out)
}

/// The file header, the proto revision and the runtime types the generated
/// surface names.
fn header(out: &mut String, proto_rev: &str) {
    out.push_str(
        "// @generated by protoc-gen-loams-facade from proto/. Do not edit.\n\
         //\n\
         // The SDK facade of design §44 §7.3: one trait per service annotated with\n\
         // `loams.options.v1.module`, one method per `loams.options.v1.facade` call,\n\
         // and the binding table the hand-written runtime dispatches through.\n\
         // Regenerate with `scripts/sdk/gen.sh rust`; the drift check in CI fails if\n\
         // this file is stale.\n\
         //\n\
         // The message types are generated by the SDK crate's own build.rs with\n\
         // connectrpc-build (D128); this file only names them. The three types it\n\
         // names but does not define — CallOptions, LoamsError and ResponseStream —\n\
         // belong to the runtime beside it.\n\
         \n",
    );
    writeln!(
        out,
        "/// The proto revision this SDK was generated from (`LOAMS_PROTO_REV`,\n\
         /// design §44 §10.3). `loams::version()` checks it against the server's\n\
         /// `GetInstance.api_versions`.\n\
         pub const PROTO_REV: &str = \"{proto_rev}\";\n"
    )
    .ok();
}

/// The three closed sets the binding table is typed with, so a caller matching
/// on one is exhaustive.
///
/// Emitted with `writeln!` rather than one long literal: Rust's string
/// continuation strips the indentation of the line after a `\`, so a literal
/// cannot express a nested indent without escaping every space.
fn enums(out: &mut String) {
    out.push_str(
        "/// `google.protobuf.MethodOptions.idempotency_level`, read out of the\n\
         /// descriptor rather than guessed (design §44 §7.4, D610).\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum Idempotency {\n",
    );
    variants(
        out,
        "Idempotency",
        &[
            (
                "NoSideEffects",
                "A read that may be a cacheable `GET`, and that the SDK always retries.",
            ),
            (
                "Idempotent",
                "Repeating it changes nothing beyond the first call.",
            ),
            ("None", "Nothing declared: repeating it may do the work twice."),
        ],
        &[
            ("NoSideEffects", "no_side_effects"),
            ("Idempotent", "idempotent"),
            ("None", "none"),
        ],
    );
    out.push_str(
        "/// Whether the SDK retries the call on its own: a read and an idempotent\n\
         /// RPC do, a mutation only when it carries an idempotency key.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum Retry {\n",
    );
    variants(
        out,
        "Retry",
        &[
            ("Safe", "The SDK retries on its own."),
            (
                "Manual",
                "The SDK does not: a mutating RPC retries only when the caller\n    /// supplied an `idempotency_key`, which the SDK then reuses.",
            ),
        ],
        &[("Safe", "safe"), ("Manual", "manual")],
    );
    out.push_str(
        "/// Whether a method streams, and in which direction. The API has no\n\
         /// client-streaming and no bidi (D420).\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum Streaming {\n",
    );
    variants(
        out,
        "Streaming",
        &[("Unary", "One request, one response."), ("Server", "One request, a stream of responses.")],
        &[("Unary", "unary"), ("Server", "server")],
    );
}

/// One generated enum: its variants with their doc comments, and the
/// `as_str` that gives each the `snake_case` name the other SDKs use.
fn variants(
    out: &mut String,
    name: &str,
    variants: &[(&str, &str)],
    names: &[(&str, &str)],
) {
    for (variant, doc) in variants {
        writeln!(out, "    /// {doc}").ok();
        writeln!(out, "    {variant},").ok();
    }
    writeln!(out, "}}").ok();
    writeln!(out).ok();
    writeln!(out, "impl {name} {{").ok();
    writeln!(out, "    /// The `snake_case` name the generated SDKs use.").ok();
    writeln!(out, "    pub const fn as_str(self) -> &'static str {{").ok();
    writeln!(out, "        match self {{").ok();
    for (variant, wire) in names {
        writeln!(out, "            Self::{variant} => \"{wire}\",").ok();
    }
    writeln!(out, "        }}").ok();
    writeln!(out, "    }}").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();
}

/// The reason registry, as constants and tables (design §44 §7.4, D611).
fn reasons(out: &mut String, model: &Model) {
    out.push_str(
        "/// A stable, machine-readable cause of a failed RPC: the thing callers\n\
         /// branch on, never the message. Within an API major version a reason is\n\
         /// never renamed and never removed, so this type only grows.\n\
         pub type Reason = &'static str;\n\
         \n\
         /// Every reason in `docs/api/reasons.md`.\n\
         pub const REASONS: &[Reason] = &[\n",
    );
    for reason in &model.reasons {
        writeln!(out, "    \"{}\",", reason.reason).ok();
    }
    out.push_str("];\n\n");
    out.push_str(
        "/// Each reason and the Connect code it is raised under, from the same\n\
         /// registry.\n\
         pub const REASON_CODES: &[(Reason, &str)] = &[\n",
    );
    for reason in &model.reasons {
        writeln!(out, "    (\"{}\", \"{}\"),", reason.reason, reason.code).ok();
    }
    out.push_str("];\n\n");
    out.push_str(
        "/// The reason a package the build variant does not carry answers with\n\
         /// (design §44 §4, D600). Every RPC of such a package refuses with it and\n\
         /// names the variant in `metadata.variant`; the runtime turns that refusal\n\
         /// into a `FeatureNotInVariantError`, and `loams::system::available()`\n\
         /// answers the same question from `GetInstance.services[]` without a failing\n\
         /// call.\n\
         pub const FEATURE_NOT_IN_VARIANT: Reason = \"feature_not_in_variant\";\n\
         \n\
         /// Every proto package this SDK speaks, as `GetInstance.api_versions`\n\
         /// names them.\n\
         pub const PROTO_PACKAGES: &[&str] = &[\n",
    );
    for package in &model.packages {
        writeln!(out, "    \"{package}\",").ok();
    }
    out.push_str("];\n\n");
}

/// The binding table: the runtime's whole view of what the SDK can call.
fn bindings(out: &mut String, model: &Model) {
    out.push_str(
        "/// AIP-158 paging, named by `FacadeOptions.pagination`.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct Pagination {\n\
         \x20/// The repeated field on the response the iterator yields.\n\
             pub items: &'static str,\n\
         \x20/// The token field: in on the next call, out on this one.\n\
             pub next_page_token: &'static str,\n\
         }\n\
         \n\
         /// One facade call, as the runtime dispatches it.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct CallBinding {\n\
         \x20/// The module the call is exposed on.\n\
             pub module: &'static str,\n\
         \x20/// The call's name, in `snake_case`.\n\
             pub name: &'static str,\n\
         \x20/// The name `FacadeOptions` gave it, in `snake_case`.\n\
             pub proto_name: &'static str,\n\
         \x20/// The method that backs the call.\n\
             pub method: &'static str,\n\
         \x20/// The RPC, as `package.Service/Method`, which is the path curl and\n\
         \x20/// grpcurl use.\n\
             pub rpc: &'static str,\n\
             pub service: &'static str,\n\
             pub package: &'static str,\n\
             pub idempotency: Idempotency,\n\
             pub retry: Retry,\n\
             pub streaming: Streaming,\n\
             pub pagination: Option<Pagination>,\n\
         }\n\
         \n\
         /// One SDK module and its calls.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct ModuleBinding {\n\
             pub name: &'static str,\n\
             pub summary: &'static str,\n\
             pub service: &'static str,\n\
             pub package: &'static str,\n\
         \x20/// Whether the package's wire contract may still change.\n\
             pub unstable: bool,\n\
         \x20/// True for a second facade name for the same RPCs, which has no summary\n\
         \x20/// of its own.\n\
             pub derived: bool,\n\
             pub calls: &'static [CallBinding],\n\
         }\n\
         \n\
         /// Every annotated service, as the module catalogue. Order is by module\n\
         /// name.\n\
         pub static MODULES: &[ModuleBinding] = &[\n",
    );
    for module in &model.modules {
        writeln!(
            out,
            "    ModuleBinding {{\n        name: \"{name}\",\n        summary: \"{summary}\",\n        service: \"{service}\",\n        package: \"{package}\",\n        unstable: {unstable},\n        derived: {derived},\n        calls: &[",
            name = escape(&module.name),
            summary = escape(&module.summary),
            service = module.service,
            package = module.package,
            unstable = module.unstable,
            derived = module.derived,
        )
        .ok();
        for call in &module.calls {
            let pagination = match &call.pagination {
                Some(paging) => format!(
                    "Some(Pagination {{ items: \"{items}\", next_page_token: \"{token}\" }})",
                    items = escape(&paging.items),
                    token = escape(&paging.next_page_token),
                ),
                None => "None".to_owned(),
            };
            writeln!(
                out,
                "            CallBinding {{ module: \"{module}\", name: \"{name}\", proto_name: \"{proto}\", method: \"{method}\", rpc: \"{rpc}\", service: \"{service}\", package: \"{package}\", idempotency: Idempotency::{idempotency}, retry: Retry::{retry}, streaming: Streaming::{streaming}, pagination: {pagination} }},",
                module = escape(&call.module),
                name = escape(&naming::snake(&call.name)),
                proto = escape(&call.name),
                method = call.method,
                rpc = call.rpc(),
                service = call.service,
                package = call.package,
                idempotency = rust_idempotency(call.idempotency),
                retry = rust_retry(call.retry),
                streaming = rust_streaming(call.streaming),
            )
            .ok();
        }
        out.push_str("        ],\n    },\n");
    }
    out.push_str("];\n\n");
}

/// One module's trait: its three constants and one method per facade call. The
/// hand-written runtime implements it once over the generated Connect client.
fn module_trait(out: &mut String, module: &Module, packages: &PackageMap) -> Result<(), String> {
    let name = naming::type_name(&module.name);
    let unstable_note = if module.unstable {
        " Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3)."
    } else {
        ""
    };
    let about = if module.derived {
        format!(
            "is a second facade name for the same RPCs, exposed as `loams.{name}`.",
            name = module.name
        )
    } else {
        format!(
            "is `loams.{name}` — {summary}",
            name = module.name,
            summary = module.summary
        )
    };
    writeln!(
        out,
        "/// `{name}Module` {about}\n///\n/// Wraps `{service}`.{unstable}\npub trait {name}Module {{\n    /// The SDK module, as it appears on `loams.{module}`.\n    const MODULE: &'static str = \"{module}\";\n    /// The service behind the module.\n    const SERVICE: &'static str = \"{service}\";\n    /// Whether the package's wire contract may still change.\n    const UNSTABLE: bool = {is_unstable};\n",
        name = name,
        about = about,
        service = module.service,
        unstable = unstable_note,
        module = module.name,
        is_unstable = module.unstable,
    )
    .ok();
    for (index, call) in module.calls.iter().enumerate() {
        // A blank line between methods, and not one before the closing brace.
        if index > 0 {
            out.push('\n');
        }
        out.push_str(&call_signature(call, packages)?);
    }
    out.push_str("}\n\n");
    Ok(())
}

/// One call's Rust signature, as it appears in the generated file.
///
/// The call returns `impl Future + Send` rather than being an `async fn` in the
/// trait: `async fn` in a public trait cannot carry a `Send` bound, which every
/// caller of a Connect client needs and which this repository's clippy gate
/// (`-D warnings`) refuses to let slide. It is also the shape
/// `connectrpc-build` generates for the server's own traits, so the SDK's
/// surface and the crate it sits on read the same way.
pub fn call_signature(call: &Call, packages: &PackageMap) -> Result<String, String> {
    let input = qualified(&call.input, packages)?;
    let output = qualified(&call.output, packages)?;
    let returns = if call.streaming == crate::Streaming::Server {
        format!("Result<ResponseStream<{output}>, LoamsError>")
    } else {
        format!("Result<{output}, LoamsError>")
    };
    let mut doc = format!(
        "    /// `{rpc}`, retried: {retry}.",
        rpc = call.rpc(),
        retry = call.retry.as_str(),
    );
    if let Some(paging) = &call.pagination {
        doc.push_str(&format!(
            " AIP-158: page with `{}` and follow `{}` through `loams::paginate`.",
            paging.items, paging.next_page_token
        ));
    }
    // Rust's method names are `snake_case` (design §44 §7.1), and the annotations
    // carry the camelCase name the TypeScript surface uses.
    Ok(format!(
        "{doc}\n    fn {name}(\n        &self,\n        request: {input},\n        options: Option<&CallOptions>,\n    ) -> impl std::future::Future<Output = {returns}> + Send;\n",
        name = naming::snake(&call.name),
    ))
}

/// A fully qualified proto message as the Rust path for it: the crate path the
/// SDK's build.rs generated and the leaf.
fn qualified(full: &str, packages: &PackageMap) -> Result<String, String> {
    if full.is_empty() {
        return Err("a method has no message type".to_owned());
    }
    let package = naming::package_of(full);
    let Some(crate_path) = packages.get(package) else {
        return Err(format!("{package} is not in the package map"));
    };
    Ok(format!("{crate_path}::{}", naming::leaf(full)))
}

fn rust_idempotency(idempotency: crate::Idempotency) -> &'static str {
    match idempotency {
        crate::Idempotency::NoSideEffects => "NoSideEffects",
        crate::Idempotency::Idempotent => "Idempotent",
        crate::Idempotency::None => "None",
    }
}

fn rust_retry(retry: crate::Retry) -> &'static str {
    match retry {
        crate::Retry::Safe => "Safe",
        crate::Retry::Manual => "Manual",
    }
}

fn rust_streaming(streaming: crate::Streaming) -> &'static str {
    match streaming {
        crate::Streaming::Unary => "Unary",
        crate::Streaming::Server => "Server",
    }
}

/// A string literal body: quotes and backslashes escaped, so a summary with a
/// quote cannot break the generated file.
fn escape(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_a_summary_with_a_quote() {
        assert_eq!(escape("say \"hi\""), "say \\\"hi\\\"");
        assert_eq!(escape("a \\ backslash"), "a \\\\ backslash");
    }
}