//! The TypeScript renderer: the `@loams/client` facade, generated from the
//! annotations (design §44 §7.3, D606).
//!
//! What is generated and what is hand-written is the split §44 §7.3 draws. The
//! **facade** is generated: one typed interface per annotated service, its
//! method signatures in the language's case, and the binding table the runtime
//! dispatches through — including each call's retry class and its pagination,
//! read out of `loams.options.v1` rather than guessed. The **runtime** is hand
//! written, once: the transport, the token sources, the retry loop, the error
//! mapping, the token store, the pagination iterator and the streams.
//!
//! Adding an RPC to the SDK is therefore a proto edit: annotate the service
//! with a module and the method with a facade call, run `buf generate`, and the
//! method exists in thirteen SDKs with the right types and the right retry
//! behaviour. That is what SDK1 Task 3's spike is deciding (Q604); this is the
//! TypeScript half.

use std::fmt::Write as _;

use crate::{Call, Model, Module, PackageMap};

/// The hand-written runtime's module specifier, relative to this file. Part of
/// the TypeScript template: SDK1 Task 3 moves templates into
/// `sdks/templates/<lang>/` (design §44 §10.2).
const RUNTIME: &str = "../runtime/call.js";

/// Renders `facade.ts`.
pub fn render(model: &Model, packages: &PackageMap, proto_rev: &str) -> Result<String, String> {
    let mut out = String::new();
    header(&mut out, proto_rev);

    // One import per proto package, in the order the modules use them.
    let mut specifiers: Vec<&str> = Vec::new();
    for module in &model.modules {
        let specifier = packages.get(&module.package).ok_or_else(|| {
            format!(
                "{} is not in the package map, so the SDK cannot import its message types",
                module.package
            )
        })?;
        if !specifiers.contains(&specifier) {
            specifiers.push(specifier);
        }
    }
    writeln!(
        out,
        "import type {{ MessageInitShape }} from '@bufbuild/protobuf';"
    )
    .ok();
    writeln!(
        out,
        "import type {{ DescService }} from '@bufbuild/protobuf';"
    )
    .ok();
    writeln!(out, "import type {{ CallOptions }} from '{RUNTIME}';").ok();
    for specifier in &specifiers {
        let names = type_names(model, packages, specifier);
        let mut value_names: Vec<String> = Vec::new();
        for module in &model.modules {
            if packages.get(&module.package) != Some(*specifier) {
                continue;
            }
            value_names.push(leaf(&module.service).to_owned());
        }
        value_names.sort();
        value_names.dedup();
        if !value_names.is_empty() {
            writeln!(
                out,
                "import {{ {} }} from '{specifier}';",
                value_names.join(", ")
            )
            .ok();
        }
        if !names.is_empty() {
            writeln!(
                out,
                "import type {{ {} }} from '{specifier}';",
                names.join(", ")
            )
            .ok();
        }
    }

    for module in &model.modules {
        module_interface(&mut out, module)?;
    }
    bindings(&mut out, model, packages)?;
    reasons(&mut out, model);
    Ok(out)
}

/// The file header and the imports that do not depend on the package map.
fn header(out: &mut String, proto_rev: &str) {
    out.push_str(
        "// @generated by protoc-gen-loams-facade from proto/. Do not edit.\n\
         //\n\
         // The SDK facade of design §44 §7.3: one typed interface per service\n\
         // annotated with `loams.options.v1.module`, one method per\n\
         // `loams.options.v1.facade` call, and the binding table the hand-written\n\
         // runtime dispatches through. Regenerate with `pnpm --filter @loams/client\n\
         // generate`; the drift check in CI fails if this file is stale.\n\
         /* eslint-disable */\n\n",
    );
    out.push_str(
        "/**\n\
         *  The proto revision this SDK was generated from (`LOAMS_PROTO_REV`,\n\
         *  design §44 §10.3). `loams.system.version()` checks it against the\n\
         *  server's `GetInstance.api_versions`.\n\
         */\n",
    );
    writeln!(out, "export const PROTO_REV = '{proto_rev}';").ok();
    out.push('\n');
}

/// The interface of one module: its summary, its service, and one method per
/// facade call with the generated message types.
fn module_interface(out: &mut String, module: &Module) -> Result<(), String> {
    let unstable = if module.unstable {
        " Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3)."
    } else {
        ""
    };
    let about = if module.derived {
        format!(
            "A second facade name for the same RPCs, exposed as `loams.{name}`.",
            name = module.name
        )
    } else {
        format!(
            "`loams.{name}` — {summary}",
            name = module.name,
            summary = module.summary
        )
    };
    writeln!(
        out,
        "/**\n *  {about}\n *\n *  Wraps `{service}`.{unstable}\n */",
        about = about,
        service = module.service,
    )
    .ok();
    writeln!(
        out,
        "export interface {name}Module {{",
        name = type_name(&module.name)
    )
    .ok();
    writeln!(
        out,
        "  /** The SDK module, as it appears on `loams.{name}`. */",
        name = module.name
    )
    .ok();
    writeln!(out, "  readonly module: '{name}';", name = module.name).ok();
    writeln!(out, "  /** The service behind the module. */").ok();
    writeln!(
        out,
        "  readonly service: '{service}';",
        service = module.service
    )
    .ok();
    writeln!(
        out,
        "  /** Whether the package's wire contract may still change. */"
    )
    .ok();
    writeln!(
        out,
        "  readonly unstable: {unstable};",
        unstable = module.unstable
    )
    .ok();
    for call in &module.calls {
        call_signature(out, call)?;
    }
    out.push_str("}\n\n");
    Ok(())
}

/// One call's TypeScript signature. A server stream returns an
/// `AsyncIterable` of the element message, which is the language's native
/// async iteration (design §44 §7.1).
fn call_signature(out: &mut String, call: &Call) -> Result<(), String> {
    let input = schema_name(&call.input)?;
    let output = message_name(&call.output)?;
    let name = camel(&call.name);
    let paging = match &call.pagination {
        Some(paging) => format!(
            " AIP-158: page with `{}` and follow `{}` through `loams.paginate`.",
            paging.items, paging.next_page_token
        ),
        None => String::new(),
    };
    writeln!(
        out,
        "  /**\n   *  `{service}/{method}`, retried: {retry}.{paging}\n   */",
        service = call.service,
        method = call.method,
        retry = call.retry.as_str(),
    )
    .ok();
    let returns = if call.streaming == crate::Streaming::Server {
        format!("AsyncIterable<{output}>")
    } else {
        format!("Promise<{output}>")
    };
    writeln!(
        out,
        "  {name}(\n    request: MessageInitShape<typeof {input}>,\n    options?: CallOptions,\n  ): {returns};"
    )
    .ok();
    Ok(())
}

/// The binding table and the service descriptors: the runtime's whole view of
/// what the SDK can call.
fn bindings(out: &mut String, model: &Model, _packages: &PackageMap) -> Result<(), String> {
    out.push_str(
        "/** One facade call, as the runtime dispatches it. */\n\
         export interface CallBinding {\n\
         \x20 /** The module the call is exposed on. */\n\
         \x20 readonly module: string;\n\
         \x20 /** The call's name in TypeScript case. */\n\
         \x20 readonly name: string;\n\
         \x20 /** The name `FacadeOptions` gave it, in `snake_case`. */\n\
         \x20 readonly protoName: string;\n\
         \x20 /** The method that backs the call. */\n\
         \x20 readonly method: string;\n\
         \x20 /** The RPC, as `package.Service/Method`, which is the path curl and grpcurl use. */\n\
         \x20 readonly rpc: string;\n\
         \x20 readonly service: string;\n\
         \x20 readonly package: string;\n\
         \x20 readonly idempotency: 'no_side_effects' | 'idempotent' | 'none';\n\
         \x20 readonly retry: 'safe' | 'manual';\n\
         \x20 readonly streaming: 'unary' | 'server';\n\
         \x20 readonly pagination: { readonly items: string; readonly nextPageToken: string } | null;\n\
         }\n\n\
         /** One SDK module and its calls. */\n\
         export interface ModuleBinding {\n\
         \x20 readonly name: string;\n\
         \x20 readonly summary: string;\n\
         \x20 readonly service: string;\n\
         \x20 readonly package: string;\n\
         \x20 readonly unstable: boolean;\n\
         \x20 /** True for a second facade name for the same RPCs, which has no summary of its own. */\n\
         \x20 readonly derived: boolean;\n\
         \x20 readonly calls: readonly CallBinding[];\n\
         }\n\n",
    );
    writeln!(
        out,
        "/** Every annotated service, as the module catalogue. Order is by module name. */"
    )
    .ok();
    writeln!(out, "export const MODULES: readonly ModuleBinding[] = [").ok();
    for module in &model.modules {
        writeln!(
            out,
            "  {{\n    name: '{name}',\n    summary: '{summary}',\n    service: '{service}',\n    package: '{package}',\n    unstable: {unstable},\n    derived: {derived},\n    calls: [",
            name = escape(&module.name),
            summary = escape(&module.summary),
            service = module.service,
            package = module.package,
            unstable = module.unstable,
            derived = module.derived,
        )
        .ok();
        for call in &module.calls {
            let pagination = match &call.pagination {
                Some(paging) => format!(
                    "{{ items: '{items}', nextPageToken: '{token}' }}",
                    items = escape(&paging.items),
                    token = camel(&paging.next_page_token),
                ),
                None => "null".to_owned(),
            };
            writeln!(
                out,
                "      {{ module: '{module}', name: '{name}', protoName: '{proto}', method: '{method}', rpc: '{rpc}', service: '{service}', package: '{package}', idempotency: '{idempotency}', retry: '{retry}', streaming: '{streaming}', pagination: {pagination} }},",
                module = escape(&call.module),
                name = camel(&call.name),
                proto = escape(&call.name),
                method = call.method,
                rpc = call.rpc(),
                service = call.service,
                package = call.package,
                idempotency = call.idempotency.as_str(),
                retry = call.retry.as_str(),
                streaming = call.streaming.as_str(),
            )
            .ok();
        }
        writeln!(out, "    ],\n  }},").ok();
    }
    writeln!(out, "];").ok();
    out.push('\n');

    out.push_str(
        "/**\n\
          *  The generated service descriptors, by fully qualified name. The runtime\n\
          *  turns each into a Connect client with `createClient`, so a module is\n\
          *  backed by the stubs `protoc-gen-es` wrote from the same protos rather\n\
          *  than by a hand-written client.\n\
          */\n",
    );
    writeln!(
        out,
        "export const SERVICE_DESCRIPTORS: Readonly<Record<string, DescService>> = {{"
    )
    .ok();
    // Two modules can be facade names for one service (`loams.live` and
    // `loams.tables` are both `loams.live.v1.LiveService`), so the same
    // descriptor is listed once.
    let mut descriptors: Vec<(&str, &str)> = Vec::new();
    for module in &model.modules {
        descriptors.push((module.service.as_str(), leaf(&module.service)));
    }
    descriptors.sort();
    descriptors.dedup();
    for (service, name) in descriptors {
        writeln!(out, "  '{service}': {name},").ok();
    }
    writeln!(out, "}};").ok();
    out.push('\n');

    out.push_str(
        "/** The proto packages this SDK speaks, as `GetInstance.api_versions` names them. */\n",
    );
    writeln!(out, "export const PROTO_PACKAGES = [").ok();
    for package in &model.packages {
        writeln!(out, "  '{package}',").ok();
    }
    writeln!(out, "] as const;").ok();
    out.push('\n');
    Ok(())
}

/// The reason registry as a type: the union, and the code each is raised
/// under.
fn reasons(out: &mut String, model: &Model) {
    out.push_str(
        "/**\n\
          *  Every `reason` in `docs/api/reasons.md` (design §44 §7.4, D611). Within\n\
          *  an API major version a reason is never renamed and never removed, so\n\
          *  this union only grows; a caller switching on it is exhaustive.\n\
          */\n\
         export const REASONS = [\n",
    );
    for reason in &model.reasons {
        writeln!(out, "  '{}',", reason.reason).ok();
    }
    out.push_str("] as const;\n\n");
    out.push_str("/** A stable, machine-readable cause of a failed RPC. */\n");
    out.push_str("export type Reason = (typeof REASONS)[number];\n\n");
    out.push_str(
        "/** The Connect code each reason is raised under, from the same registry. */\n\
         export const REASON_CODES: Readonly<Record<Reason, string>> = {\n",
    );
    for reason in &model.reasons {
        writeln!(out, "  {}: '{}',", reason.reason, reason.code).ok();
    }
    out.push_str("};\n\n");
    out.push_str(
        "/**\n\
          *  The reason a package the build variant does not carry answers with\n\
          *  (design §44 §4, D600). Every RPC of such a package refuses with it and\n\
          *  names the variant in `metadata.variant`; the runtime turns that refusal\n\
          *  into `FeatureNotInVariantError` so a caller can branch on it without\n\
          *  calling first — `loams.system.available()` answers the same question from\n\
          *  `GetInstance.services[]` without a failing call at all.\n\
          */\n\
         export const FEATURE_NOT_IN_VARIANT = 'feature_not_in_variant' as const satisfies Reason;\n",
    );
}

/// The identifiers of one package's messages that the facade's signatures
/// name, as `XSchema` (for a request) or `X` (for a response).
fn type_names(model: &Model, packages: &PackageMap, specifier: &str) -> Vec<String> {
    let mut names = Vec::new();
    for call in model.calls() {
        if packages.get(call.package.as_str()) != Some(specifier) {
            continue;
        }
        for name in [
            schema_name(&call.input).unwrap_or_default(),
            message_name(&call.output).unwrap_or_default(),
        ] {
            if !name.is_empty() && !names.contains(&name) {
                names.push(name);
            }
        }
    }
    names.sort();
    names
}

/// `loams.instance.v1.GetInstanceRequest` → `GetInstanceRequestSchema`.
fn schema_name(full: &str) -> Result<String, String> {
    if full.is_empty() {
        return Err("a method has no input type".to_owned());
    }
    Ok(format!("{}Schema", leaf(full)))
}

/// `loams.instance.v1.GetInstanceResponse` → `GetInstanceResponse`.
fn message_name(full: &str) -> Result<String, String> {
    if full.is_empty() {
        return Err("a method has no output type".to_owned());
    }
    Ok(leaf(full).to_owned())
}

/// The last segment of a fully qualified proto name.
fn leaf(full: &str) -> &str {
    full.rsplit('.').next().unwrap_or(full)
}

/// A module or package name as a TypeScript type name: `admin.org` →
/// `AdminOrg`, `instance` → `Instance`.
fn type_name(name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for character in name.chars() {
        if character == '.' || character == '_' || character == '-' {
            upper = true;
            continue;
        }
        if upper {
            out.extend(character.to_uppercase());
            upper = false;
        } else {
            out.push(character);
        }
    }
    out
}

/// `snake_case` → `camelCase`, which is what TypeScript calls the methods
/// (design §44 §7.1).
fn camel(name: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for character in name.chars() {
        if character == '_' || character == '-' {
            upper = true;
            continue;
        }
        if upper {
            out.extend(character.to_uppercase());
            upper = false;
        } else {
            out.push(character);
        }
    }
    out
}

/// A string literal body: quotes and backslashes escaped, so a summary with
/// an apostrophe cannot break the generated file.
fn escape(text: &str) -> String {
    text.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn converts_names_to_typescript_case() {
        assert_eq!(camel("get_instance"), "getInstance");
        assert_eq!(camel("who_am_i"), "whoAmI");
        assert_eq!(camel("search"), "search");
        assert_eq!(camel("next_page_token"), "nextPageToken");
        assert_eq!(type_name("admin.org"), "AdminOrg");
        assert_eq!(type_name("instance"), "Instance");
    }

    #[test]
    fn escapes_a_summary_with_an_apostrophe() {
        assert_eq!(escape("the caller's key"), "the caller\\'s key");
    }
}
