#!/usr/bin/env bash
# Generate crates/loams-sqlrouter/tests/fixtures/pg_hash_vectors.json from real Postgres
# hash partitioning (RT0 plan, ruling 4): for each key type and modulus, create a table
# PARTITION BY HASH, insert the keys and read which partition (remainder) each landed in.
# Needs docker or podman. Usage: scripts/router/gen-pg-hash-vectors.sh [image]
set -euo pipefail
image="${1:-docker.io/library/postgres:17.11}"
engine="$(command -v docker || command -v podman)"
root="$(cd "$(dirname "$0")/../.." && pwd)"
out="$root/crates/loams-sqlrouter/tests/fixtures/pg_hash_vectors.json"
name="loams-pghash-$$"
"$engine" run -d --rm --name "$name" -e POSTGRES_PASSWORD=pw "$image" >/dev/null
trap '"$engine" stop "$name" >/dev/null 2>&1 || true' EXIT
for _ in $(seq 60); do "$engine" exec "$name" pg_isready -U postgres >/dev/null 2>&1 && break; sleep 1; done
sleep 2
psql() { "$engine" exec -i "$name" psql -U postgres -v ON_ERROR_STOP=1 -qAt "$@"; }
version="$(psql -c 'show server_version')"
moduli=(2 3 4 8 16)
# 2000 keys per type: extremes, small values, and a spread; text covers lengths 0..40 (every tail case of hash_bytes_extended).
psql <<'SQL'
create table keys_int8 as select k from (
  select unnest(array[0, 1, -1, 2, -2, 9223372036854775807, -9223372036854775808, 2147483647, -2147483648, 4294967296]::int8[]) k
  union all select ((i::numeric * 2654435761 * 40503) % 18446744073709551616 - 9223372036854775808)::int8 from generate_series(1, 1990) i) s;
create table keys_int4 as select k from (
  select unnest(array[0, 1, -1, 2147483647, -2147483648]::int4[]) k
  union all select ((i::int8 * 2654435761) % 4294967296 - 2147483648)::int4 from generate_series(1, 1995) i) s;
create table keys_text as select left(md5(i::text) || md5((i + 7)::text), i % 41) k from generate_series(0, 1999) i;
create table keys_uuid as select md5(i::text || 'loams')::uuid k from generate_series(1, 2000) i;
SQL
for t in int8 int4 text uuid; do
  for m in "${moduli[@]}"; do
    psql -c "create table p_${t}_${m} (k ${t}) partition by hash (k);"
    for r in $(seq 0 $((m - 1))); do
      psql -c "create table p_${t}_${m}_${r} partition of p_${t}_${m} for values with (modulus ${m}, remainder ${r});"
    done
    psql -c "insert into p_${t}_${m} select k from keys_${t};"
  done
done
# One row per key: the remainder for each modulus, read from the partition the row landed in.
json="$(psql <<'SQL'
with r as (
  select 'int8' t, k::text key, 2 m, split_part(tableoid::regclass::text, '_', 4)::int rem from p_int8_2
  union all select 'int8', k::text, 3, split_part(tableoid::regclass::text, '_', 4)::int from p_int8_3
  union all select 'int8', k::text, 4, split_part(tableoid::regclass::text, '_', 4)::int from p_int8_4
  union all select 'int8', k::text, 8, split_part(tableoid::regclass::text, '_', 4)::int from p_int8_8
  union all select 'int8', k::text, 16, split_part(tableoid::regclass::text, '_', 4)::int from p_int8_16
  union all select 'int4', k::text, 2, split_part(tableoid::regclass::text, '_', 4)::int from p_int4_2
  union all select 'int4', k::text, 3, split_part(tableoid::regclass::text, '_', 4)::int from p_int4_3
  union all select 'int4', k::text, 4, split_part(tableoid::regclass::text, '_', 4)::int from p_int4_4
  union all select 'int4', k::text, 8, split_part(tableoid::regclass::text, '_', 4)::int from p_int4_8
  union all select 'int4', k::text, 16, split_part(tableoid::regclass::text, '_', 4)::int from p_int4_16
  union all select 'text', k, 2, split_part(tableoid::regclass::text, '_', 4)::int from p_text_2
  union all select 'text', k, 3, split_part(tableoid::regclass::text, '_', 4)::int from p_text_3
  union all select 'text', k, 4, split_part(tableoid::regclass::text, '_', 4)::int from p_text_4
  union all select 'text', k, 8, split_part(tableoid::regclass::text, '_', 4)::int from p_text_8
  union all select 'text', k, 16, split_part(tableoid::regclass::text, '_', 4)::int from p_text_16
  union all select 'uuid', k::text, 2, split_part(tableoid::regclass::text, '_', 4)::int from p_uuid_2
  union all select 'uuid', k::text, 3, split_part(tableoid::regclass::text, '_', 4)::int from p_uuid_3
  union all select 'uuid', k::text, 4, split_part(tableoid::regclass::text, '_', 4)::int from p_uuid_4
  union all select 'uuid', k::text, 8, split_part(tableoid::regclass::text, '_', 4)::int from p_uuid_8
  union all select 'uuid', k::text, 16, split_part(tableoid::regclass::text, '_', 4)::int from p_uuid_16
), per_key as (
  select t, key, jsonb_object_agg(m::text, rem) rems from r group by t, key
)
select jsonb_object_agg(t, rows) from (
  select t, jsonb_agg(jsonb_build_object('key', key, 'remainders', rems) order by key) rows from per_key group by t
) s;
SQL
)"
python3 - "$out" "$version" "$image" <<PY
import json, sys
data = json.loads('''$json''')
doc = {"_source": f"Generated by scripts/router/gen-pg-hash-vectors.sh from {sys.argv[3]} (server {sys.argv[2]}): the partition each key lands in under PARTITION BY HASH, per modulus.",
       "moduli": [2, 3, 4, 8, 16], **data}
open(sys.argv[1], "w").write(json.dumps(doc, indent=1, sort_keys=True) + "\n")
print({k: len(v) for k, v in data.items()})
PY
