//! @generated by protoc-gen-loams-facade from proto/. Do not edit.
//!
//! The SDK facade of design §44 §7.3: one trait per service annotated with
//! `loams.options.v1.module`, one method per `loams.options.v1.facade` call,
//! and the binding table the hand-written runtime dispatches through.
//! Regenerate with `scripts/sdk/gen.sh rust`; the drift check in CI fails if
//! this file is stale.
//!
//! This file is **data and traits only** (D641). The message types are
//! generated by the proto crates with connectrpc-build (D128) and named by
//! their crate path; the three types imported below — CallOptions,
//! LoamsError and ResponseStream — are the hand-written runtime's, and the
//! runtime is what implements these traits. Lookups over the binding table
//! (`binding_of`, `module_of`) live in the runtime too, so that every
//! `@generated` file in this repository stays free of hand-written code.

/// The proto revision this SDK was generated from (`LOAMS_PROTO_REV`,
/// design §44 §10.3). `loams::version()` checks it against the server's
/// `GetInstance.api_versions`.
pub const PROTO_REV: &str = "v1";

use connectrpc::client::CallOptions;

use crate::error::LoamsError;
use crate::streams::ResponseStream;

/// `google.protobuf.MethodOptions.idempotency_level`, read out of the
/// descriptor rather than guessed (design §44 §7.4, D610).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub enum Idempotency {
    /// A read that may be a cacheable `GET`, and that the SDK always retries.
    NoSideEffects,
    /// Repeating it changes nothing beyond the first call.
    Idempotent,
    /// Nothing declared: repeating it may do the work twice.
    None,
}

impl Idempotency {
    /// The `snake_case` name the generated SDKs use.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::NoSideEffects => "no_side_effects",
            Self::Idempotent => "idempotent",
            Self::None => "none",
        }
    }
}

/// Whether the SDK retries the call on its own: a read and an idempotent
/// RPC do, a mutation only when it carries an idempotency key.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub enum Retry {
    /// The SDK retries on its own.
    Safe,
    /// The SDK does not: a mutating RPC retries only when the caller
    /// supplied an `idempotency_key`, which the SDK then reuses.
    Manual,
}

impl Retry {
    /// The `snake_case` name the generated SDKs use.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Safe => "safe",
            Self::Manual => "manual",
        }
    }
}

/// Whether a method streams, and in which direction. The API has no
/// client-streaming and no bidi (D420).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub enum Streaming {
    /// One request, one response.
    Unary,
    /// One request, a stream of responses.
    Server,
}

impl Streaming {
    /// The `snake_case` name the generated SDKs use.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Unary => "unary",
            Self::Server => "server",
        }
    }
}

/// A stable, machine-readable cause of a failed RPC: the thing callers
/// branch on, never the message. Within an API major version a reason is
/// never renamed and never removed, so this type only grows.
pub type Reason = &'static str;

/// Every reason in `docs/api/reasons.md`.
pub const REASONS: &[Reason] = &[
    "approval_expired",
    "approval_already_decided",
    "approval_stale_revision",
    "requester_cannot_approve",
    "decision_proof_invalid",
    "step_up_required",
    "reason_required",
    "invalid_decision",
    "pairing_expired",
    "pairing_used",
    "device_revoked",
    "push_target_unknown",
    "not_implemented",
    "feature_not_in_variant",
    "invalid_argument",
    "not_found",
    "already_exists",
    "permission_denied",
    "token_expired",
    "unauthenticated",
    "failed_precondition",
    "resource_exhausted",
    "unavailable",
    "deadline_exceeded",
    "aborted",
    "internal",
];

/// Each reason and the Connect code it is raised under, from the same
/// registry.
pub const REASON_CODES: &[(Reason, &str)] = &[
    ("approval_expired", "failed_precondition"),
    ("approval_already_decided", "failed_precondition"),
    ("approval_stale_revision", "failed_precondition"),
    ("requester_cannot_approve", "permission_denied"),
    ("decision_proof_invalid", "permission_denied"),
    ("step_up_required", "unauthenticated"),
    ("reason_required", "invalid_argument"),
    ("invalid_decision", "invalid_argument"),
    ("pairing_expired", "failed_precondition"),
    ("pairing_used", "failed_precondition"),
    ("device_revoked", "unauthenticated"),
    ("push_target_unknown", "not_found"),
    ("not_implemented", "unimplemented"),
    ("feature_not_in_variant", "unimplemented"),
    ("invalid_argument", "invalid_argument"),
    ("not_found", "not_found"),
    ("already_exists", "already_exists"),
    ("permission_denied", "permission_denied"),
    ("token_expired", "unauthenticated"),
    ("unauthenticated", "unauthenticated"),
    ("failed_precondition", "failed_precondition"),
    ("resource_exhausted", "resource_exhausted"),
    ("unavailable", "unavailable"),
    ("deadline_exceeded", "deadline_exceeded"),
    ("aborted", "aborted"),
    ("internal", "internal"),
];

/// The reason a package the build variant does not carry answers with
/// (design §44 §4, D600). Every RPC of such a package refuses with it and
/// names the variant in `metadata.variant`; the runtime turns that refusal
/// into a `FeatureNotInVariantError`, and `loams::system::available()`
/// answers the same question from `GetInstance.services[]` without a failing
/// call.
pub const FEATURE_NOT_IN_VARIANT: Reason = "feature_not_in_variant";

/// Every proto package this SDK speaks, as `GetInstance.api_versions`
/// names them.
pub const PROTO_PACKAGES: &[&str] = &[
    "google.protobuf",
    "loams.approvals.v1",
    "loams.devices.v1",
    "loams.errors.v1",
    "loams.instance.v1",
    "loams.live.v1",
    "loams.notifications.v1",
    "loams.operations.v1",
    "loams.options.v1",
];

/// AIP-158 paging, named by `FacadeOptions.pagination`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub struct Pagination {
 /// The repeated field on the response the iterator yields.
pub items: &'static str,
 /// The token field: in on the next call, out on this one.
pub next_page_token: &'static str,
}

/// One facade call, as the runtime dispatches it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub struct CallBinding {
 /// The module the call is exposed on.
pub module: &'static str,
 /// The call's name, in `snake_case`.
pub name: &'static str,
 /// The name `FacadeOptions` gave it, in `snake_case`.
pub proto_name: &'static str,
 /// The method that backs the call.
pub method: &'static str,
 /// The RPC, as `package.Service/Method`, which is the path curl and
 /// grpcurl use.
pub rpc: &'static str,
 /// The service that declares the method, fully qualified.
pub service: &'static str,
 /// The proto package the service is declared in.
pub package: &'static str,
 /// Whether the request message declares an `idempotency_key` field,
 /// read out of the descriptor. A keyed call may be retried, because a
 /// repeat returns the first call's recorded result rather than doing
 /// the work twice (R3, D610).
pub keyed: bool,
 /// What the proto says about repeating the call, as
 /// `FacadeOptions.idempotency_level` recorded it.
pub idempotency: Idempotency,
 /// Whether the SDK retries this call on its own, as
 /// `FacadeOptions.retry_safe` recorded it. Distinct from
 /// [`CallBinding::idempotency`]: a proto may declare a call
 /// idempotent and still ask for no automatic retry.
pub retry: Retry,
 /// Whether the call streams server messages.
pub streaming: Streaming,
 /// The paging fields, when `FacadeOptions.pagination` declared any.
pub pagination: Option<Pagination>,
}

/// One SDK module and its calls.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub struct ModuleBinding {
 /// The SDK module name, as it appears on `loams.<name>`.
pub name: &'static str,
 /// The module's one-line summary, empty for a derived module.
pub summary: &'static str,
 /// The service the module wraps, fully qualified.
pub service: &'static str,
 /// The proto package that service is declared in.
pub package: &'static str,
 /// Whether the package's wire contract may still change.
pub unstable: bool,
 /// True for a second facade name for the same RPCs, which has no summary
 /// of its own.
pub derived: bool,
 /// The module's calls, in declaration order.
pub calls: &'static [CallBinding],
}

/// Every annotated service, as the module catalogue. Order is by module
/// name.
///
/// `rustfmt::skip` because this table is emitted one row per line and
/// rustfmt would reflow it. `scripts/sdk/gen.sh rust` overwrites this
/// file wholesale, so a `cargo fmt` that rewrapped the table would make
/// the next regeneration differ from what is committed and the drift
/// check in CI would report a stale facade forever (D641).
#[rustfmt::skip]
pub static MODULES: &[ModuleBinding] = &[
    ModuleBinding {
        name: "instance",
        summary: "What this instance is, and who the caller is on it.",
        service: "loams.instance.v1.InstanceService",
        package: "loams.instance.v1",
        unstable: false,
        derived: false,
        calls: &[
            CallBinding { module: "instance", name: "get_instance", proto_name: "getInstance", method: "GetInstance", rpc: "loams.instance.v1.InstanceService/GetInstance", service: "loams.instance.v1.InstanceService", package: "loams.instance.v1", keyed: false, idempotency: Idempotency::NoSideEffects, retry: Retry::Safe, streaming: Streaming::Unary, pagination: None },
            CallBinding { module: "instance", name: "who_am_i", proto_name: "whoAmI", method: "WhoAmI", rpc: "loams.instance.v1.InstanceService/WhoAmI", service: "loams.instance.v1.InstanceService", package: "loams.instance.v1", keyed: false, idempotency: Idempotency::NoSideEffects, retry: Retry::Safe, streaming: Streaming::Unary, pagination: None },
        ],
    },
    ModuleBinding {
        name: "live",
        summary: "Live sync: watch a query set over a server stream.",
        service: "loams.live.v1.LiveService",
        package: "loams.live.v1",
        unstable: true,
        derived: false,
        calls: &[
            CallBinding { module: "live", name: "modify_query_set", proto_name: "modifyQuerySet", method: "ModifyQuerySet", rpc: "loams.live.v1.LiveService/ModifyQuerySet", service: "loams.live.v1.LiveService", package: "loams.live.v1", keyed: false, idempotency: Idempotency::None, retry: Retry::Manual, streaming: Streaming::Unary, pagination: None },
            CallBinding { module: "live", name: "watch", proto_name: "watch", method: "Watch", rpc: "loams.live.v1.LiveService/Watch", service: "loams.live.v1.LiveService", package: "loams.live.v1", keyed: false, idempotency: Idempotency::None, retry: Retry::Manual, streaming: Streaming::Server, pagination: None },
        ],
    },
    ModuleBinding {
        name: "tables",
        summary: "",
        service: "loams.live.v1.LiveService",
        package: "loams.live.v1",
        unstable: true,
        derived: true,
        calls: &[
            CallBinding { module: "tables", name: "deploy", proto_name: "deploy", method: "Deploy", rpc: "loams.live.v1.LiveService/Deploy", service: "loams.live.v1.LiveService", package: "loams.live.v1", keyed: false, idempotency: Idempotency::None, retry: Retry::Manual, streaming: Streaming::Unary, pagination: None },
            CallBinding { module: "tables", name: "mutate", proto_name: "mutate", method: "Mutate", rpc: "loams.live.v1.LiveService/Mutate", service: "loams.live.v1.LiveService", package: "loams.live.v1", keyed: true, idempotency: Idempotency::None, retry: Retry::Manual, streaming: Streaming::Unary, pagination: None },
            CallBinding { module: "tables", name: "query", proto_name: "query", method: "Query", rpc: "loams.live.v1.LiveService/Query", service: "loams.live.v1.LiveService", package: "loams.live.v1", keyed: false, idempotency: Idempotency::None, retry: Retry::Manual, streaming: Streaming::Unary, pagination: None },
        ],
    },
];

/// `InstanceModule` is `loams.instance` — What this instance is, and who the caller is on it.
///
/// Wraps `loams.instance.v1.InstanceService`.
#[rustfmt::skip]
pub trait InstanceModule {
    /// The SDK module, as it appears on `loams.instance`.
    const MODULE: &'static str = "instance";
    /// The service behind the module.
    const SERVICE: &'static str = "loams.instance.v1.InstanceService";
    /// Whether the package's wire contract may still change.
    const UNSTABLE: bool = false;

    /// `loams.instance.v1.InstanceService/GetInstance`, retried: safe.
    fn get_instance(
        &self,
        request: loams_proto::loams::instance::v1::GetInstanceRequest,
        options: Option<&CallOptions>,
    ) -> impl std::future::Future<Output = Result<loams_proto::loams::instance::v1::GetInstanceResponse, LoamsError>> + Send;

    /// `loams.instance.v1.InstanceService/WhoAmI`, retried: safe.
    fn who_am_i(
        &self,
        request: loams_proto::loams::instance::v1::WhoAmIRequest,
        options: Option<&CallOptions>,
    ) -> impl std::future::Future<Output = Result<loams_proto::loams::instance::v1::WhoAmIResponse, LoamsError>> + Send;
}

/// `LiveModule` is `loams.live` — Live sync: watch a query set over a server stream.
///
/// Wraps `loams.live.v1.LiveService`. Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3).
#[rustfmt::skip]
pub trait LiveModule {
    /// The SDK module, as it appears on `loams.live`.
    const MODULE: &'static str = "live";
    /// The service behind the module.
    const SERVICE: &'static str = "loams.live.v1.LiveService";
    /// Whether the package's wire contract may still change.
    const UNSTABLE: bool = true;

    /// `loams.live.v1.LiveService/ModifyQuerySet`, retried: manual.
    fn modify_query_set(
        &self,
        request: loams_live_proto::loams::live::v1::ModifyQuerySetRequest,
        options: Option<&CallOptions>,
    ) -> impl std::future::Future<Output = Result<loams_live_proto::loams::live::v1::ModifyQuerySetResponse, LoamsError>> + Send;

    /// `loams.live.v1.LiveService/Watch`, retried: manual.
    fn watch(
        &self,
        request: loams_live_proto::loams::live::v1::WatchRequest,
        options: Option<&CallOptions>,
    ) -> impl std::future::Future<Output = Result<ResponseStream<loams_live_proto::loams::live::v1::Transition>, LoamsError>> + Send;
}

/// `TablesModule` is a second facade name for the same RPCs, exposed as `loams.tables`.
///
/// Wraps `loams.live.v1.LiveService`. Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3).
#[rustfmt::skip]
pub trait TablesModule {
    /// The SDK module, as it appears on `loams.tables`.
    const MODULE: &'static str = "tables";
    /// The service behind the module.
    const SERVICE: &'static str = "loams.live.v1.LiveService";
    /// Whether the package's wire contract may still change.
    const UNSTABLE: bool = true;

    /// `loams.live.v1.LiveService/Deploy`, retried: manual.
    fn deploy(
        &self,
        request: loams_live_proto::loams::live::v1::DeployRequest,
        options: Option<&CallOptions>,
    ) -> impl std::future::Future<Output = Result<loams_live_proto::loams::live::v1::DeployResponse, LoamsError>> + Send;

    /// `loams.live.v1.LiveService/Mutate`, retried: manual.
    fn mutate(
        &self,
        request: loams_live_proto::loams::live::v1::MutateRequest,
        options: Option<&CallOptions>,
    ) -> impl std::future::Future<Output = Result<loams_live_proto::loams::live::v1::MutateResponse, LoamsError>> + Send;

    /// `loams.live.v1.LiveService/Query`, retried: manual.
    fn query(
        &self,
        request: loams_live_proto::loams::live::v1::QueryRequest,
        options: Option<&CallOptions>,
    ) -> impl std::future::Future<Output = Result<loams_live_proto::loams::live::v1::QueryResponse, LoamsError>> + Send;
}
