//! The `reason` registry (design §44 §7.4, D611; runtime contract R8).
//!
//! A `reason` is the stable, `snake_case` cause of a failed RPC, registered in
//! `docs/api/reasons.md`. It is what a caller branches on; the `message` is for
//! a person and may change. The registry's rule is that a reason may be **added**
//! but never renamed or removed within an API major version, so this list only
//! grows.
//!
//! The TypeScript SDK's copy of this table is generated by
//! `protoc-gen-loams-facade` into `src/gen/facade.ts`, and the Rust SDK's copy
//! is generated into `src/facade.rs` (`facade::REASONS` and
//! `facade::REASON_CODES`, D641).
//!
//! This enum is the runtime's own, and stays hand-written: the generated table
//! carries the reasons as `&'static str` constants, which is what a caller
//! matches on and what keeps a reason from becoming an enum variant that a
//! server the SDK has never spoken to could not name. `rust_error_reason_mapping`
//! walks every row here and fails if the registry page, this enum and the
//! generated table drift apart, so a reason added to `docs/api/reasons.md`
//! without a row here cannot pass unnoticed.

use connectrpc::ErrorCode as Code;

/// A stable, machine-readable cause of a failed RPC.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[non_exhaustive]
pub enum Reason {
    /// The approval this call needed is past its deadline.
    ApprovalExpired,
    /// The approval was already decided, so there is nothing to decide again.
    ApprovalAlreadyDecided,
    /// The approval was written against an older revision of what it approves.
    ApprovalStaleRevision,
    /// The caller is the requester, and a requester cannot approve their own request.
    RequesterCannotApprove,
    /// The decision proof does not verify against the instance key.
    DecisionProofInvalid,
    /// The call needs a fresh authentication step before it can proceed.
    StepUpRequired,
    /// A free-text reason is required and none was given.
    ReasonRequired,
    /// The decision is not one of approve, deny or request changes.
    InvalidDecision,
    /// The pairing grant is past its deadline.
    PairingExpired,
    /// The pairing grant was already used; a grant is single use.
    PairingUsed,
    /// The device was revoked, by its owner or by the instance.
    DeviceRevoked,
    /// The push target is not registered with the instance.
    PushTargetUnknown,
    /// This build does not implement the call.
    NotImplemented,
    /// This build variant does not carry the package the call belongs to.
    FeatureNotInVariant,
    /// An argument is missing, malformed or out of range.
    InvalidArgument,
    /// The thing the call names does not exist.
    NotFound,
    /// The thing the call would create already exists.
    AlreadyExists,
    /// The caller is authenticated but not allowed to do this.
    PermissionDenied,
    /// The bearer the call carried has expired; refresh and retry once.
    TokenExpired,
    /// The call carried no usable credential.
    Unauthenticated,
    /// The system is not in a state where the call can be made.
    FailedPrecondition,
    /// A quota or a rate limit was reached.
    ResourceExhausted,
    /// The service is temporarily unavailable; a retry may succeed.
    Unavailable,
    /// The call ran out of time.
    DeadlineExceeded,
    /// The call was aborted; a retry may succeed.
    Aborted,
    /// A fault on the server.
    Internal,
}

impl Reason {
    /// Every reason in the registry, in `docs/api/reasons.md` order.
    pub const ALL: &'static [Reason] = &[
        Reason::ApprovalExpired,
        Reason::ApprovalAlreadyDecided,
        Reason::ApprovalStaleRevision,
        Reason::RequesterCannotApprove,
        Reason::DecisionProofInvalid,
        Reason::StepUpRequired,
        Reason::ReasonRequired,
        Reason::InvalidDecision,
        Reason::PairingExpired,
        Reason::PairingUsed,
        Reason::DeviceRevoked,
        Reason::PushTargetUnknown,
        Reason::NotImplemented,
        Reason::FeatureNotInVariant,
        Reason::InvalidArgument,
        Reason::NotFound,
        Reason::AlreadyExists,
        Reason::PermissionDenied,
        Reason::TokenExpired,
        Reason::Unauthenticated,
        Reason::FailedPrecondition,
        Reason::ResourceExhausted,
        Reason::Unavailable,
        Reason::DeadlineExceeded,
        Reason::Aborted,
        Reason::Internal,
    ];

    /// The registry's spelling, which is also the wire form.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Reason::ApprovalExpired => "approval_expired",
            Reason::ApprovalAlreadyDecided => "approval_already_decided",
            Reason::ApprovalStaleRevision => "approval_stale_revision",
            Reason::RequesterCannotApprove => "requester_cannot_approve",
            Reason::DecisionProofInvalid => "decision_proof_invalid",
            Reason::StepUpRequired => "step_up_required",
            Reason::ReasonRequired => "reason_required",
            Reason::InvalidDecision => "invalid_decision",
            Reason::PairingExpired => "pairing_expired",
            Reason::PairingUsed => "pairing_used",
            Reason::DeviceRevoked => "device_revoked",
            Reason::PushTargetUnknown => "push_target_unknown",
            Reason::NotImplemented => "not_implemented",
            Reason::FeatureNotInVariant => "feature_not_in_variant",
            Reason::InvalidArgument => "invalid_argument",
            Reason::NotFound => "not_found",
            Reason::AlreadyExists => "already_exists",
            Reason::PermissionDenied => "permission_denied",
            Reason::TokenExpired => "token_expired",
            Reason::Unauthenticated => "unauthenticated",
            Reason::FailedPrecondition => "failed_precondition",
            Reason::ResourceExhausted => "resource_exhausted",
            Reason::Unavailable => "unavailable",
            Reason::DeadlineExceeded => "deadline_exceeded",
            Reason::Aborted => "aborted",
            Reason::Internal => "internal",
        }
    }

    /// The reason a wire string names, or `None` for a reason this SDK's
    /// registry does not have — which means a **newer server**, not a bad
    /// message. [`crate::LoamsError::unknown_reason`] carries it as text so a
    /// caller can still tell "not supported here" from "not supported at all".
    #[must_use]
    pub fn parse(text: &str) -> Option<Reason> {
        Reason::ALL
            .iter()
            .copied()
            .find(|reason| reason.as_str() == text)
    }

    /// The Connect code the registry says this reason is raised under.
    #[must_use]
    pub fn code(self) -> Code {
        match self {
            Reason::ApprovalExpired
            | Reason::ApprovalAlreadyDecided
            | Reason::ApprovalStaleRevision
            | Reason::PairingExpired
            | Reason::PairingUsed
            | Reason::FailedPrecondition => Code::FailedPrecondition,
            Reason::RequesterCannotApprove
            | Reason::DecisionProofInvalid
            | Reason::PermissionDenied => Code::PermissionDenied,
            Reason::StepUpRequired
            | Reason::DeviceRevoked
            | Reason::TokenExpired
            | Reason::Unauthenticated => Code::Unauthenticated,
            Reason::ReasonRequired | Reason::InvalidDecision | Reason::InvalidArgument => {
                Code::InvalidArgument
            }
            Reason::PushTargetUnknown | Reason::NotFound => Code::NotFound,
            Reason::NotImplemented | Reason::FeatureNotInVariant => Code::Unimplemented,
            Reason::AlreadyExists => Code::AlreadyExists,
            Reason::ResourceExhausted => Code::ResourceExhausted,
            Reason::Unavailable => Code::Unavailable,
            Reason::DeadlineExceeded => Code::DeadlineExceeded,
            Reason::Aborted => Code::Aborted,
            Reason::Internal => Code::Internal,
        }
    }
}

impl std::fmt::Display for Reason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for Reason {
    type Err = UnknownReason;

    fn from_str(text: &str) -> Result<Self, Self::Err> {
        Reason::parse(text).ok_or_else(|| UnknownReason(text.to_owned()))
    }
}

/// A `reason` string this SDK's registry does not have.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownReason(pub String);

impl std::fmt::Display for UnknownReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "`{}` is not a reason in this SDK's registry", self.0)
    }
}

impl std::error::Error for UnknownReason {}

/// The reason a package this build variant does not carry answers with
/// (design §44 §4, D600).
pub const FEATURE_NOT_IN_VARIANT: Reason = Reason::FeatureNotInVariant;

/// The reason a token the server rejected as expired answers with (R1).
pub const TOKEN_EXPIRED: Reason = Reason::TokenExpired;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_reason_round_trips_through_its_wire_form() {
        assert!(Reason::ALL.len() >= 25, "the registry has 26 rows");
        for reason in Reason::ALL {
            assert_eq!(Reason::parse(reason.as_str()), Some(*reason));
        }
    }

    #[test]
    fn no_two_reasons_share_a_name() {
        let mut names: Vec<&str> = Reason::ALL.iter().map(|r| r.as_str()).collect();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(before, names.len(), "two reasons share a registry name");
    }

    #[test]
    fn a_reason_off_the_registry_is_an_unknown_reason_not_a_panic() {
        assert_eq!(Reason::parse("from_the_future"), None);
        assert!("from_the_future".parse::<Reason>().is_err());
    }
}
