//! Every `package=<pkg>=<crate path>` in a language's `buf.gen.yaml` names a
//! crate path that **exists**: the language's own dependency list, and the proto
//! crate's real module layout.
//!
//! This is a guard for a defect that shipped. `sdks/rust/buf.gen.yaml` mapped
//! `loams.live.v1` to `loams_proto::loams::live::v1`, but `loams.live.v1` is
//! generated by the **separate** `crates/loams-live-proto` crate — `loams-proto`
//! says so in its own `lib.rs`, and `crates/loams-proto/build.rs` does not list
//! any `loams/live/v1` file. The mapping was wrong, the generator was faithful
//! (it errors on a package missing from the map), and nothing caught it: the
//! renderer happily emitted a path that resolves to nothing.
//!
//! Two things are checked, and the second is the one that failed:
//!
//! 1. **The crate is a dependency.** Every crate path's first segment must be a
//!    dependency in that SDK's manifest, in its own spelling. A name that is not
//!    a dependency cannot be imported.
//! 2. **The crate generates that package.** The path after the crate must be the
//!    proto package's own segments as nested modules, *and* the crate must be
//!    one that actually compiles that package's protos. This is what catches a
//!    map that names the wrong crate for a package that exists: both
//!    `loams_proto::loams::live::v1` and `loams_live_proto::loams::live::v1`
//!    pass check 1, because the SDK depends on both crates.
//!
//! Check 2's crate-ownership half is derived from the `build.rs` of each proto
//! crate — the file that says which protos become that crate's modules — rather
//! than from a hand-written table, so adding a proto package to a `build.rs` and
//! forgetting the map fails here.
//!
//! It runs over **every** language's `buf.gen.yaml`, not just Rust's. The Go,
//! Python and TypeScript maps name their own ecosystems' module paths, so the
//! crate-ownership check is Rust-specific, but the shape check and the
//! "is this package in the map at all" check apply to all of them.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

mod protoreq;

/// One `package=<pkg>=<value>` line, with the language it came from.
#[derive(Debug, Clone, PartialEq, Eq)]
struct Mapping {
    language: String,
    package: String,
    value: String,
}

/// Every mapping in every `sdks/*/buf.gen.yaml`, read as text.
///
/// Parsed as text rather than as YAML because these files are `buf` templates
/// with a `${LOAMS_FACADE_PLUGIN}` placeholder in them, which is not valid YAML
/// until `scripts/sdk/gen.sh` substitutes it. The `opt:` lines the plugin reads
/// are a flat list of `key=value`, so a line-oriented read is both sufficient
/// and the thing that cannot break on a template edit.
fn mappings() -> Vec<Mapping> {
    let mut found = Vec::new();
    for template in buf_templates() {
        let language = template
            .parent()
            .and_then(Path::file_name)
            .expect("sdks/<lang>/buf.gen.yaml")
            .to_string_lossy()
            .into_owned();
        let text = std::fs::read_to_string(&template)
            .unwrap_or_else(|err| panic!("{}: {err}", template.display()));
        for line in text.lines() {
            let line = line.trim();
            let Some(rest) = line
                .strip_prefix("- package=")
                .or_else(|| line.strip_prefix("package="))
            else {
                continue;
            };
            let (package, value) = rest
                .split_once('=')
                .unwrap_or_else(|| panic!("{}: a package= line with no value: {line}", template.display()));
            found.push(Mapping {
                language: language.clone(),
                package: package.trim().to_owned(),
                value: value.trim().to_owned(),
            });
        }
    }
    assert!(
        found.len() >= 4,
        "only found {} package= mappings across every buf.gen.yaml; the read is broken, not the maps",
        found.len()
    );
    found
}

fn buf_templates() -> Vec<PathBuf> {
    let sdks = root().join("sdks");
    let mut templates: Vec<PathBuf> = std::fs::read_dir(&sdks)
        .unwrap_or_else(|err| panic!("{}: {err}", sdks.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .map(|path| path.join("buf.gen.yaml"))
        .filter(|path| path.is_file())
        .collect();
    templates.sort();
    templates
}

/// Which proto crate generates which proto package, read off each crate's
/// `build.rs` — the file that lists the protos it compiles into that crate's
/// modules.
///
/// `crates/loams-proto/build.rs` lists `loams/instance/v1/instance.proto` and
/// friends; `crates/loams-live-proto/build.rs` lists `loams/live/v1/*.proto`.
/// Neither is a hand-maintained list here: it is read from the crate, so a proto
/// package added to a `build.rs` without a matching map entry fails.
fn owners() -> BTreeMap<String, Vec<String>> {
    let mut owners: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let crates = root().join("crates");
    let mut entries: Vec<PathBuf> = std::fs::read_dir(&crates)
        .unwrap_or_else(|err| panic!("{}: {err}", crates.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.join("build.rs").is_file())
        .collect();
    entries.sort();
    for crate_dir in entries {
        let name = crate_dir
            .file_name()
            .expect("a crate directory")
            .to_string_lossy()
            .replace('-', "_");
        let text = std::fs::read_to_string(crate_dir.join("build.rs"))
            .unwrap_or_else(|err| panic!("{}/build.rs: {err}", crate_dir.display()));
        for package in proto_packages_named_in(&text) {
            owners.entry(package).or_default().push(name.clone());
        }
    }
    assert!(
        owners.contains_key("loams.live.v1"),
        "no crate's build.rs mentions loams/live/v1, so the owner table is broken"
    );
    owners
}

/// The proto packages a `build.rs` names, from paths like
/// `loams/live/v1/live.proto` or `{root}/loams/instance/v1/…`.
fn proto_packages_named_in(build_rs: &str) -> Vec<String> {
    let mut packages = Vec::new();
    let mut rest = build_rs;
    while let Some(at) = rest.find("loams/") {
        let tail = &rest[at + "loams/".len()..];
        // `loams/<segment>/v1/…` is a package path; anything else that merely
        // starts with `loams/` is not one.
        let Some((segments, _)) = tail.split_once("/v1/") else {
            rest = &rest[at + "loams/".len()..];
            continue;
        };
        let segment = segments
            .rsplit('/')
            .next()
            .expect("a segment before /v1/")
            .trim_matches(|c: char| !c.is_ascii_alphanumeric());
        if segment.is_empty() || segment.contains(['{', '}', '"', '\'']) {
            rest = &rest[at + "loams/".len()..];
            continue;
        }
        let package = format!("loams.{segment}.v1");
        if !packages.contains(&package) {
            packages.push(package);
        }
        rest = &rest[at + "loams/".len()..];
    }
    packages
}

/// The dependency names a manifest declares, in Rust spelling (`-` and `_`
/// interchangeable, as cargo requires).
fn rust_dependencies(manifest: &Path) -> Vec<String> {
    let text = std::fs::read_to_string(manifest)
        .unwrap_or_else(|err| panic!("{}: {err}", manifest.display()));
    text.lines()
        .filter_map(|line| {
            let line = line.trim();
            // A dependency table row: `name = …` or `name.workspace = true`.
            let name = line.split(['=', '.', ' ']).next()?;
            if name.is_empty()
                || !name
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
            {
                return None;
            }
            if name.starts_with('[') || name.chars().next().is_some_and(char::is_numeric) {
                return None;
            }
            Some(name.replace('-', "_"))
        })
        .collect()
}

/// Every proto package's distinguishing segment: `loams.live.v1` is `live`,
/// `loams.instance.v1` is `instance`.
fn segment_of(package: &str) -> &str {
    package
        .split('.')
        .find(|part| *part != "loams" && *part != "v1")
        .unwrap_or(package)
}

/// The shape check, shared by every language: a mapping's value must name **its
/// own** package's segment and **no other** package's.
///
/// This is the invariant all four languages actually satisfy, which a stricter
/// "the value must contain the whole package path" is not: TypeScript's map
/// drops `v1` on purpose, because the published packages are `@loams/proto/
/// instance` and `@loams/live/live` — one npm package per proto package, named
/// for the package rather than mirroring its path. Go keeps the whole path,
/// Python appends `_pb2`, and Rust keeps the whole path as nested modules. So
/// the check is "this package's segment is in there, and no sibling's is",
/// which is what a mis-pointed map breaks and which a name choice does not.
fn value_matches_package(package: &str, value: &str, all_packages: &[String]) -> bool {
    let own = segment_of(package);
    if !value.contains(own) {
        return false;
    }
    !all_packages
        .iter()
        .filter(|other| *other != package)
        .any(|other| value.contains(segment_of(other)))
}

/// **Check 1.** Every crate path's first segment is a dependency of the SDK that
/// will import it.
///
/// The shipped defect passes this — `loams-proto` *is* a dependency, which is
/// why it went unnoticed — so this check is here to catch the other direction: a
/// map naming a crate the SDK never depends on, which no build could resolve.
#[test]
fn every_mapped_crate_is_a_dependency_of_its_sdk() {
    let dependencies = rust_dependencies(&root().join("sdks/rust/Cargo.toml"));
    assert!(
        dependencies.contains(&"loams_proto".to_owned()),
        "sdks/rust/Cargo.toml no longer declares loams-proto, so this guard is reading the wrong manifest"
    );
    for mapping in mappings() {
        let Some((crate_name, _)) = mapping.value.split_once("::") else {
            // Not a crate path. Go, Python and TypeScript name their own
            // ecosystems' module paths, so only the Rust map is checked here.
            assert_ne!(
                mapping.language, "rust",
                "the Rust map must name crate paths, but it maps {} to {}",
                mapping.package, mapping.value
            );
            continue;
        };
        assert!(
            dependencies.contains(&crate_name.replace('-', "_")),
            "{} maps {} to {}, but {crate_name} is not a dependency of \
             sdks/rust/Cargo.toml, so the SDK cannot import it",
            mapping.language,
            mapping.package,
            mapping.value
        );
    }
}

/// **Check 2.** The crate a package is mapped to is the crate that actually
/// generates it. This is the check the shipped defect failed.
///
/// Both `loams_proto::loams::live::v1` and `loams_live_proto::loams::live::v1`
/// satisfy check 1, because the SDK depends on both. Only the second names the
/// crate whose `build.rs` compiles `loams/live/v1/*.proto`.
#[test]
fn every_mapped_package_is_generated_by_the_crate_it_names() {
    let owners = owners();
    let mut checked = 0;
    for mapping in mappings() {
        let Some((crate_name, module_path)) = mapping.value.split_once("::") else {
            continue;
        };
        let crate_name = crate_name.replace('-', "_");
        let Some(claiming) = owners.get(&mapping.package) else {
            // No crate compiles this package's protos yet. A map entry for a
            // package nothing generates is not this check's business — the
            // package simply is not on the wire.
            continue;
        };
        assert!(
            claiming.contains(&crate_name),
            "{} maps {} to {}, but no crate compiles that package's protos into \
             {crate_name}: {}",
            mapping.language,
            mapping.package,
            mapping.value,
            if claiming.is_empty() {
                "no crate claims it".to_owned()
            } else {
                format!("{} does", claiming.join(", "))
            }
        );
        // And the module path after the crate must be the package's own nested
        // modules, so `loams_live_proto::wrong::v1` cannot pass by naming the
        // right crate.
        assert_eq!(
            module_path,
            mapping.package.replace('.', "::"),
            "{} maps {} to {}, whose module path is not the package's segments",
            mapping.language,
            mapping.package,
            mapping.value
        );
        checked += 1;
    }
    assert!(
        checked >= 6,
        "only {checked} Rust mappings were checked against crate ownership; \
         the read is broken, not the maps"
    );
}

/// A mapping's value must not name a different package's path. Applies to every
/// language, since it is about the shape of the value rather than about crates.
#[test]
fn a_mapping_never_points_at_another_package() {
    let all = mappings();
    let packages: Vec<String> = {
        let mut packages: Vec<String> = all.iter().map(|m| m.package.clone()).collect();
        packages.sort();
        packages.dedup();
        packages
    };
    assert!(
        packages.len() >= 7,
        "only {} distinct packages are mapped; the read is broken, not the maps",
        packages.len()
    );
    for mapping in &all {
        assert!(
            value_matches_package(&mapping.package, &mapping.value, &packages),
            "{} maps {} to {}, which does not name its own package's segment \
             ({}) and no other",
            mapping.language,
            mapping.package,
            mapping.value,
            segment_of(&mapping.package)
        );
    }
}

/// Every proto package that has an annotated service is in the map. A package
/// the generator needs but the map omits fails generation, so this catches it
/// at the map rather than at the build.
#[test]
fn every_annotated_package_is_in_every_map() {
    let annotated: Vec<String> = model_packages();
    assert!(
        annotated.contains(&"loams.live.v1".to_owned()),
        "the descriptor set no longer carries loams.live.v1, so this test reads the wrong input"
    );
    let by_language: BTreeMap<String, Vec<String>> = mappings()
        .into_iter()
        .fold(BTreeMap::new(), |mut acc, mapping| {
            acc.entry(mapping.language)
                .or_default()
                .push(mapping.package);
            acc
        });
    for (language, packages) in &by_language {
        // TypeScript's map carries `loams.errors.v1`, which no annotated service
        // needs; every other language maps exactly the annotated set.
        for package in &annotated {
            assert!(
                packages.contains(package),
                "{language} does not map {package}, which has an annotated service"
            );
        }
    }
}

/// Anti-vacuity: the two checks above must actually reject the defect they were
/// written for. If this test passes with a *correct* map it proves nothing, so it
/// re-runs both checks against the mapping that shipped and requires each to
/// reject it.
///
/// The check functions take their inputs rather than reading the repository, so
/// the same code that guards the real maps is the code exercised here.
#[test]
fn the_crate_ownership_check_rejects_the_defect_it_was_written_for() {
    let shipped = Mapping {
        language: "rust".to_owned(),
        package: "loams.live.v1".to_owned(),
        value: "loams_proto::loams::live::v1".to_owned(),
    };
    let correct = Mapping {
        value: "loams_live_proto::loams::live::v1".to_owned(),
        ..shipped.clone()
    };
    let owners = owners();
    let dependencies = rust_dependencies(&root().join("sdks/rust/Cargo.toml"));

    // The shipped defect satisfies the dependency check, which is why it shipped.
    assert!(
        crate_is_a_dependency(&dependencies, "loams_proto"),
        "the dependency check rejects loams_proto, so it would not have caught the \
         shipped defect and is testing the wrong thing"
    );
    // And it must fail crate ownership, naming the crate that does own it.
    let error = crate_ownership_error(&owners, &shipped).unwrap_or_else(|| {
        panic!("crate ownership accepted {} — the guard cannot fail", shipped.value)
    });
    assert!(
        error.contains("loams_live_proto"),
        "the error must name the crate that does generate loams.live.v1, got: {error}"
    );
    // And the corrected mapping passes both.
    assert!(crate_is_a_dependency(&dependencies, "loams_live_proto"));
    assert_eq!(crate_ownership_error(&owners, &correct), None);

    // The cross-language shape check must reject a map that points a package at
    // a sibling's module, in a language whose maps are not crate paths at all —
    // otherwise the defect class is only guarded for Rust.
    let packages = vec![
        "loams.instance.v1".to_owned(),
        "loams.live.v1".to_owned(),
        "loams.devices.v1".to_owned(),
    ];
    assert!(
        value_matches_package("loams.live.v1", "@loams/live/live", &packages),
        "the real TypeScript mapping must satisfy the shape check, or this test's \
         premise is wrong"
    );
    assert!(
        !value_matches_package("loams.live.v1", "@loams/proto/instance", &packages),
        "a TypeScript map pointing loams.live.v1 at the instance package was accepted; \
         the guard cannot fail, so it is worth nothing"
    );
}

/// Whether a crate path's first segment is a declared dependency.
fn crate_is_a_dependency(dependencies: &[String], crate_name: &str) -> bool {
    dependencies.contains(&crate_name.replace('-', "_"))
}

/// The crate-ownership check as a function, so the anti-vacuity test can drive
/// it with a planted defect. `None` is clean.
fn crate_ownership_error(owners: &BTreeMap<String, Vec<String>>, mapping: &Mapping) -> Option<String> {
    let (crate_name, module_path) = mapping.value.split_once("::")?;
    let crate_name = crate_name.replace('-', "_");
    let claiming = owners.get(&mapping.package)?;
    if !claiming.contains(&crate_name) {
        return Some(format!(
            "{} maps {} to {}, but {} does",
            mapping.language, mapping.package, mapping.value, claiming.join(", ")
        ));
    }
    if module_path != mapping.package.replace('.', "::") {
        return Some(format!(
            "{} maps {} to {}, whose module path is wrong",
            mapping.language, mapping.package, mapping.value
        ));
    }
    None
}

/// The proto packages the real descriptors carry an annotated service in.
fn model_packages() -> Vec<String> {
    let reasons = loams_facade_gen::reasons::read(&root().join("docs/api/reasons.md"))
        .expect("the reason registry");
    let model = loams_facade_gen::model_from_request(protoreq::code_generator_request(), reasons)
        .expect("the descriptors");
    let mut packages: Vec<String> = model.modules.iter().map(|m| m.package.clone()).collect();
    packages.sort();
    packages.dedup();
    packages
}

fn root() -> PathBuf {
    protoreq::root()
}
