#!/usr/bin/env python3
"""Generate ``sdks/python/src/loams/gen/facade.py``, and the protobuf stubs beside it.

This is the **bootstrap** generator for the Python SDK (design §44 §7.3, D606).

The real one is ``protoc-gen-loams-facade`` with ``opt: lang=python``, owned by
SDK1 Task 3 and rendered from ``sdks/templates/python/``. **It does not exist
yet**, so this script stands in for it: it reads the same two inputs the Rust
plugin reads — a descriptor set built from ``proto/`` and the reason registry in
``docs/api/reasons.md`` — applies the same model
(``crates/loams-facade-gen/src/lib.rs``), and writes the same table the
hand-written runtime dispatches through.

Two things come out of it:

``sdks/python/src/loams/<proto package>/**/*_pb2.py``
    the ``protoc-gen-python`` stubs. protoc's Python plugin does not emit
    ``__init__.py`` files and a wheel needs them for the subpackages to be
    importable, so this script writes them. That is packaging scaffolding, not
    generated code: no generated file is edited.

``sdks/python/src/loams/gen/facade.py``
    the binding table: ``PROTO_REV``, ``MODULES``, ``PROTO_PACKAGES``,
    ``REASONS``, ``REASON_CODES``, ``FEATURE_NOT_IN_VARIANT``, and the typed
    module classes.

Run it with the repository root as the working directory::

    python sdks/python/tools/bootstrap_facade.py

**When ``lang=python`` lands, delete this script and run
``scripts/sdk/gen.sh python`` instead.** Nothing in ``src/loams/runtime`` reads
this file's provenance; it reads the same table either way, so the swap is a
regeneration and a diff.

Why the stubs land inside the ``loams`` package rather than beside it: protoc
writes imports that are absolute in the proto tree (``from loams.live.v1 import
value_pb2``), because the proto package *is* called ``loams``. Emitting into
``src/`` therefore puts them at ``loams.<proto package>``, which is both what
the generated code imports and the package name design §44 §9 row 2 reserves.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from google.protobuf import descriptor_pb2

# The proto tree and the SDK's generated output, from the repository root.
PROTO_DIR = "proto"
STUB_ROOT = "sdks/python/src"
REASONS_PAGE = "docs/api/reasons.md"
FACADE_OUT = "sdks/python/src/loams/gen/facade.py"

# `google.protobuf.MethodOptions.idempotency_level`, and its two values that mean
# something. Anything else is "not declared", which D610 reads as a mutation.
IDEMPOTENCY_NAMES = {
    0: "none",
    1: "no_side_effects",
    2: "idempotent",
}
RETRY_SAFE_BY_IDEMPOTENCY = {
    "no_side_effects": "safe",
    "idempotent": "safe",
    "none": "manual",
}

PROTO_REV = "v1"

STUB_MARKER = "# Generated by protoc (protoc-gen-python). Do not edit.\n"
INIT_MARKER = (
    '"""Marks {path} as a package for the wheel.\n\n'
    "protoc's Python plugin does not emit __init__.py files, and these\n"
    "directories are written by sdks/python/tools/bootstrap_facade.py, which is\n"
    "the Python facade's generator until protoc-gen-loams-facade grows a\n"
    "`lang=python` renderer.\n\"\"\"\n"
)


@dataclass(frozen=True)
class Pagination:
    """AIP-158 pagination, named by ``FacadeOptions.pagination``."""

    items: str
    next_page_token: str


@dataclass(frozen=True)
class Call:
    """One facade call: a method of a service, exposed under one name."""

    module: str
    name: str
    method: str
    input: str
    output: str
    service: str
    package: str
    idempotency: str
    retry: str
    streaming: str
    pagination: Pagination | None

    @property
    def rpc(self) -> str:
        """The RPC that backs the call, ``package.Service/Method``."""
        return f"{self.service}/{self.method}"


@dataclass(frozen=True)
class Module:
    """One SDK module: a service, its summary, and the calls on it."""

    name: str
    summary: str
    unstable: bool
    service: str
    package: str
    derived: bool
    calls: tuple[Call, ...] = ()


@dataclass(frozen=True)
class Reason:
    """One row of ``docs/api/reasons.md``."""

    reason: str
    code: str


@dataclass(frozen=True)
class Model:
    """Everything the renderer needs, as ``loams_facade_gen::Model``."""

    modules: tuple[Module, ...]
    reasons: tuple[Reason, ...]
    packages: tuple[str, ...]


# ---------------------------------------------------------------------------
# Reading the inputs.
# ---------------------------------------------------------------------------


def parse_reasons(text: str, path: Path) -> tuple[Reason, ...]:
    """The registry page, with the same row shape ``reasons.rs`` validates."""
    out: list[Reason] = []
    seen: set[str] = set()
    for number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        cells = [cell.strip() for cell in stripped.strip("|").split("|")]
        if len(cells) < 2:
            continue
        # `reasons.rs` only accepts a row whose first cell is a backticked
        # reason, which is what skips the header and the `|---|` separator.
        if not cells[0].startswith("`"):
            continue
        reason = cells[0].strip("`")
        code = cells[1].strip("`")
        if not reason or not code:
            continue
        if not all(character.islower() or character.isdigit() or character == "_" for character in reason):
            raise SystemExit(f"{path}:{number}: {reason!r} is not lower_snake_case")
        if reason in seen:
            raise SystemExit(f"{path}:{number}: {reason!r} is registered twice")
        seen.add(reason)
        out.append(Reason(reason=reason, code=code))
    if not out:
        raise SystemExit(f"{path}: no registry rows found")
    return tuple(out)


def build_model(descriptor_set: Any, reasons: tuple[Reason, ...]) -> Model:
    """The modules and the reason registry, from the two inputs as Rust reads them."""
    from loams.options.v1 import options_pb2

    module_option = options_pb2.module
    facade_option = options_pb2.facade

    modules: dict[str, dict[str, Any]] = {}
    packages: list[str] = []
    for file_proto in descriptor_set.file:
        package = file_proto.package
        if not package:
            continue
        packages.append(package)
        for service in file_proto.service:
            if not service.options.HasExtension(module_option):
                continue
            declared = service.options.Extensions[module_option]
            for method in service.method:
                for facade in method.options.Extensions[facade_option]:
                    name = facade.module or declared.name
                    derived = name != declared.name
                    entry = modules.get(name)
                    if entry is None:
                        entry = {
                            "name": name,
                            "summary": "" if derived else declared.summary,
                            "unstable": declared.unstable,
                            "service": f"{package}.{service.name}",
                            "package": package,
                            "derived": derived,
                            "calls": [],
                        }
                        modules[name] = entry
                    entry["calls"].append(
                        _call(package, service.name, method, facade, name)
                    )

    ordered: list[Module] = []
    for name in sorted(modules):
        entry = modules[name]
        calls = sorted(entry["calls"], key=lambda call: call.name)
        ordered.append(
            Module(
                name=entry["name"],
                summary=entry["summary"],
                unstable=entry["unstable"],
                service=entry["service"],
                package=entry["package"],
                derived=entry["derived"],
                calls=tuple(calls),
            )
        )
    return Model(
        modules=tuple(ordered),
        reasons=reasons,
        packages=tuple(sorted(set(packages))),
    )


def _is_set(message: Any, number: int) -> bool:
    """Whether a proto3 scalar was written at all.

    `FacadeOptions.retry_safe` is a proto3 `bool` with no presence, so Python's
    `HasField` refuses it. `ListFields` is the same answer `lib.rs` gets by
    finding field 3 in the wire bytes, and it is the distinction that matters:
    an *unset* `retry_safe` must not read as "false, so never retry".
    """
    return any(field.number == number for field, _ in message.ListFields())


def _call(
    package: str,
    service_name: str,
    method: Any,
    facade: Any,
    module_name: str,
) -> Call:
    idempotency = IDEMPOTENCY_NAMES.get(method.options.idempotency_level, "none")
    # D610: reads and idempotent RPCs retry on their own; a mutation retries only
    # when the caller gave it an idempotency key. `retry_safe` overrides both
    # ways, which is why an unset option must not read as "false".
    if _is_set(facade, 3):
        retry = "safe" if facade.retry_safe else "manual"
    else:
        retry = RETRY_SAFE_BY_IDEMPOTENCY[idempotency]
    return Call(
        module=module_name,
        name=facade.name or method.name,
        method=method.name,
        input=method.input_type.lstrip("."),
        output=method.output_type.lstrip("."),
        service=f"{package}.{service_name}",
        package=package,
        idempotency=idempotency,
        retry=retry,
        streaming="server" if method.server_streaming else "unary",
        pagination=_pagination(package, service_name, facade.pagination),
    )


def _pagination(package: str, service: str, raw: str) -> Pagination | None:
    if not raw:
        return None
    where = f"{package}.{service}"
    if ":" not in raw:
        raise SystemExit(f'{where}: expected "<items field>:<next page token field>"')
    items, token = raw.split(":", 1)
    if not items or not token:
        raise SystemExit(f"{where}: one of the two field names is empty")
    return Pagination(items=items, next_page_token=token)


def load_extensions(root: Path) -> None:
    """Imports ``loams.options.v1``, which is what defines the two extensions.

    **This must happen before the descriptor set is parsed.** upb decides an
    unknown field's meaning while it parses, from the extension registry the pool
    holds *at that moment*; an extension whose file has not been added yet is not
    recognised and the field stays in unknown fields, so ``HasExtension`` answers
    False forever after and every module silently disappears. Importing first is
    the whole fix; the order is load-bearing, so it is a function with a name
    rather than an incidental import.
    """
    from loams.options.v1 import options_pb2  # noqa: F401


def read_descriptor_set(root: Path, protoc: str) -> Any:
    """The descriptor set of ``proto/``, which is what ``buf`` hands the plugin."""
    import tempfile

    protos = sorted(str(path.relative_to(root)) for path in (root / PROTO_DIR).rglob("*.proto"))
    if not protos:
        raise SystemExit(f"{PROTO_DIR}/ has no .proto files")
    with tempfile.TemporaryDirectory() as directory:
        out = Path(directory) / "descriptor.bin"
        subprocess.run(  # noqa: S603
            [
                protoc,
                f"-I{PROTO_DIR}",
                f"--include_imports",
                f"--descriptor_set_out={out}",
                *protos,
            ],
            cwd=root,
            check=True,
        )
        descriptor_set = descriptor_pb2.FileDescriptorSet()
        descriptor_set.ParseFromString(out.read_bytes())
    return descriptor_set


# ---------------------------------------------------------------------------
# Rendering. The output is the Python twin of `typescript.rs`'s facade.ts.
# ---------------------------------------------------------------------------

HEADER = '''\
# @generated by sdks/python/tools/bootstrap_facade.py from proto/. Do not edit.
#
# The SDK facade of design §44 §7.3 (D606): one typed module per service
# annotated with `loams.options.v1.module`, one method per
# `loams.options.v1.facade` call, and the binding table the hand-written
# runtime dispatches through, plus the `reason` enum generated from
# `docs/api/reasons.md`.
#
# **Provenance.** The real generator is `protoc-gen-loams-facade --lang=python`
# (SDK1 Task 3), which is not written yet. This file was produced from the same
# two inputs it reads — a descriptor set of `proto/` and `docs/api/reasons.md` —
# by the bootstrap script named above, and the hand-written runtime in
# `loams/runtime/` reads the same table either way. When the renderer lands,
# regenerate and the diff should be empty; then delete the script.
#
# Regenerate with:
#     python sdks/python/tools/bootstrap_facade.py
"""  # noqa: E501

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from dataclasses import dataclass
from typing import Final, Literal, Protocol

from connectrpc.method import IdempotencyLevel, MethodInfo
from google.protobuf.message import Message

from loams.runtime.options import CallOptions

@@IMPORTS@@

#: The proto revision this SDK was generated from (`LOAMS_PROTO_REV`,
#: design §44 §10.3). `loams.system.version()` checks it against the server's
#: `GetInstance.api_versions`.
PROTO_REV: Final[str] = "@@PROTO_REV@@"

#: How a call may be retried (design §44 §7.4, D610).
RetryClass = Literal["safe", "manual"]

#: Whether an RPC streams, and in which direction. The API has server streams
#: only: no client streaming and no bidi (D420).
Streaming = Literal["unary", "server"]

#: What a mutation's idempotency was declared as in the proto.
Idempotency = Literal["no_side_effects", "idempotent", "none"]


@dataclass(frozen=True, slots=True)
class Pagination:
    """AIP-158 pagination, named by ``FacadeOptions.pagination`` as
    ``"<items field>:<next page token field>"``."""

    items: str
    next_page_token: str


@dataclass(frozen=True, slots=True)
class CallBinding:
    """One facade call, as the runtime dispatches it."""

    #: The module the call is exposed on.
    module: str
    #: The call's name in ``snake_case``, which is the proto name in Python's case.
    name: str
    #: The name ``FacadeOptions`` gave it, verbatim.
    proto_name: str
    #: The method that backs the call, in ``PascalCase``.
    method: str
    #: The RPC, as ``package.Service/Method``: the path curl and grpcurl use.
    rpc: str
    #: The service, fully qualified.
    service: str
    #: The proto package the service is in.
    package: str
    idempotency: Idempotency
    retry: RetryClass
    streaming: Streaming
    pagination: Pagination | None


@dataclass(frozen=True, slots=True)
class ModuleBinding:
    """One SDK module and its calls."""

    name: str
    summary: str
    service: str
    package: str
    unstable: bool
    #: True for a second facade name for the same RPCs, which has no summary of
    #: its own (``loams.tables`` on ``loams.live.v1.LiveService``, §44 §7.2).
    derived: bool
    calls: tuple[CallBinding, ...]


#: Every annotated service, as the module catalogue, ordered by module name.
MODULES: Final[tuple[ModuleBinding, ...]] = (
@@MODULES@@
)

#: The proto packages this SDK speaks, as ``GetInstance.api_versions`` names them.
PROTO_PACKAGES: Final[tuple[str, ...]] = (
@@PACKAGES@@
)

#: Every ``reason`` in ``docs/api/reasons.md`` (design §44 §7.4, D611). Within
#: an API major version a reason is never renamed and never removed, so this
#: enum only grows, and a caller switching on it is exhaustive.
REASONS: Final[tuple[str, ...]] = (
@@REASONS@@
)

#: A stable, machine-readable cause of a failed RPC: the thing callers branch on,
#: never the message, which is for a person and may change.
Reason = Literal[
@@REASON_LITERALS@@
]

#: The Connect code each reason is raised under, from the same registry.
REASON_CODES: Final[dict[str, str]] = {
@@CODES@@
}

#: The reason a package the build variant does not carry answers with (design
#: §44 §4, D600). Every RPC of such a package refuses with it and names the
#: variant in ``metadata.variant``; the runtime turns that refusal into
#: ``FeatureNotInVariantError`` so a caller can branch on it without calling
#: first — ``loams.system.available()`` answers the same question from
#: ``GetInstance.services[]`` without a failing call at all.
FEATURE_NOT_IN_VARIANT: Final[str] = "feature_not_in_variant"

#: The reason a rejected access token answers with (D608, runtime contract R1).
TOKEN_EXPIRED: Final[str] = "token_expired"


def _binding(
    module: str,
    proto_name: str,
    method: str,
    rpc: str,
    service: str,
    package: str,
    idempotency: Idempotency,
    retry: RetryClass,
    streaming: Streaming,
    pagination: Pagination | None,
) -> CallBinding:
    return CallBinding(
        module=module,
        name=proto_name,
        proto_name=proto_name,
        method=method,
        rpc=rpc,
        service=service,
        package=package,
        idempotency=idempotency,
        retry=retry,
        streaming=streaming,
        pagination=pagination,
    )


#: The ``IdempotencyLevel`` each declared idempotency maps to, so a binding can
#: become a ``MethodInfo`` without the runtime guessing.
IDEMPOTENCY_LEVELS: Final[dict[str, IdempotencyLevel]] = {
    "no_side_effects": IdempotencyLevel.NO_SIDE_EFFECTS,
    "idempotent": IdempotencyLevel.IDEMPOTENT,
    "none": IdempotencyLevel.UNKNOWN,
}

@@MODULES_TYPED@@

#: One ``MethodInfo`` per call, keyed by ``package.Service/Method``.
#:
#: ``connect-python`` dispatches on a ``MethodInfo`` rather than on a generated
#: client class, so this table is the whole of the generated stub surface the
#: runtime needs: no ``_pb2_grpc.py`` is generated or imported.
METHODS: Final[dict[str, MethodInfo[Message, Message]]] = {
@@METHODS@@
}}

__all__ = [
    "FEATURE_NOT_IN_VARIANT",
    "IDEMPOTENCY_LEVELS",
    "METHODS",
    "MODULES",
    "PROTO_PACKAGES",
    "PROTO_REV",
    "REASONS",
    "REASON_CODES",
    "TOKEN_EXPIRED",
    "CallBinding",
    "Idempotency",
    "ModuleBinding",
    "Pagination",
    "Reason",
    "RetryClass",
    "Streaming",
    *@@MODULE_NAMES@@,
]
'''  # noqa: E501


def python_path(proto_name: str) -> str:
    """``loams.instance.v1.GetInstanceRequest`` → ``loams.instance.v1.instance_pb2``."""
    package, _, message = proto_name.rpartition(".")
    return f"{package}.{package.rsplit('.', 1)[-1]}_pb2.{message}"


def stub_module(proto_name: str) -> str:
    """The module a message type is imported from."""
    package = proto_name.rpartition(".")[0]
    return f"{package}.{package.rsplit('.', 1)[-1]}_pb2"


def render(model: Model) -> str:
    imports: set[str] = set()
    for module in model.modules:
        for call in module.calls:
            imports.add(python_path(call.input))
            imports.add(python_path(call.output))

    render_modules: list[str] = []
    typed: list[str] = []
    methods: list[str] = []
    module_names: list[str] = []

    for module in model.modules:
        class_name = "".join(part.title() for part in module.name.split(".")) + "Module"
        module_names.append(f'"{class_name}"')
        render_modules.append(_render_module(module))
        typed.append(_render_typed_module(module, class_name))
        for call in module.calls:
            methods.append(
                f'    "{call.rpc}": MethodInfo(\n'
                f'        name="{call.method}",\n'
                f'        service_name="{call.service}",\n'
                f'        input={python_path(call.input)},\n'
                f'        output={python_path(call.output)},\n'
                f'        idempotency_level=IDEMPOTENCY_LEVELS["{call.idempotency}"],\n'
                f"    ),"
            )

    values = {
        "IMPORTS": "\n".join(
            "from {} import {}".format(path.rsplit(".", 1)[0], path.rsplit(".", 1)[1])
            for path in sorted(imports)
        ),
        "PROTO_REV": PROTO_REV,
        "MODULES": "\n".join(render_modules),
        "PACKAGES": "\n".join(f'    "{name}",' for name in model.packages),
        "REASONS": "\n".join(f'    "{reason.reason}",' for reason in model.reasons),
        "REASON_LITERALS": "\n".join(f'    "{reason.reason}",' for reason in model.reasons),
        "CODES": "\n".join(f'    "{reason.reason}": "{reason.code}",' for reason in model.reasons),
        "MODULES_TYPED": "\n\n".join(typed),
        "METHODS": "\n".join(methods),
        "MODULE_NAMES": ", ".join(module_names),
    }
    out = HEADER
    for name, value in values.items():
        out = out.replace(f"@@{name}@@", value)
    return out


def _render_module(module: Module) -> str:
    lines = ["    ModuleBinding(", f'        name="{module.name}",', f'        summary="{module.summary}",', f'        service="{module.service}",', f'        package="{module.package}",', f"        unstable={module.unstable!r},", f"        derived={module.derived!r},", "        calls=("]
    for call in module.calls:
        pagination = (
            "None"
            if call.pagination is None
            else f"Pagination(items=\"{call.pagination.items}\", "
            f"next_page_token=\"{call.pagination.next_page_token}\")"
        )
        lines.append(
            "            _binding(\n"
            f'                "{call.module}",\n'
            f'                "{call.name}",\n'
            f'                "{call.method}",\n'
            f'                "{call.rpc}",\n'
            f'                "{call.service}",\n'
            f'                "{call.package}",\n'
            f'                "{call.idempotency}",\n'
            f'                "{call.retry}",\n'
            f'                "{call.streaming}",\n'
            f"                {pagination},\n"
            "            ),"
        )
    lines.append("        ),")
    lines.append("    ),")
    return "\n".join(lines)


def _render_typed_module(module: Module, class_name: str) -> str:
    """One typed module, as a ``Protocol``.

    A ``Protocol`` is the Python translation of what ``typescript.rs`` emits as an
    ``interface``: the *shape* of a module, with the generated message types on
    every signature, and no implementation. Both clients satisfy it structurally,
    so the same description types the sync and the async client and neither has to
    be written twice.

    A server-streaming call is declared as returning either iterator type, because
    which one you get is decided by the client you built rather than by the proto:
    a narrower return on the implementation is still a valid implementation.
    """
    lines = [
        f"class {class_name}(Protocol):",
        f'    """``loams.{module.name}`` — {module.summary or module.service}',
        "",
        f'    Wraps ``{module.service}``.'
        + (
            " Its wire contract may still change, so `buf breaking` skips it and the"
            " SDK marks it experimental (§44 §10.3)."
            if module.unstable
            else ""
        ),
        '    """',
        "",
        "    #: The SDK module, as it appears on the client object.",
        "    module: str",
        "    #: The service behind the module.",
        "    service: str",
        "    #: Whether the package's wire contract may still change.",
        "    unstable: bool",
    ]
    for call in module.calls:
        lines.append("")
        lines.extend(_render_typed_call(call))
    lines.append("")
    lines.append("")
    lines.append("")
    return "\n".join(lines).rstrip()


def _render_typed_call(call: Call) -> list[str]:
    request = python_path(call.input)
    response = python_path(call.output)
    returns = f"Iterator[{response}] | AsyncIterator[{response}]"
    if call.streaming != "server":
        returns = response
    return [
        "    def " + call.name + "(",
        "        self,",
        f"        request: {request},",
        "        options: CallOptions | None = None,",
        f"    ) -> {returns}:",
        f'        """``{call.rpc}``, retried: {call.retry}."""',
        "        ...",
    ]


# ---------------------------------------------------------------------------
# The stubs.
# ---------------------------------------------------------------------------


def write_stubs(root: Path, protoc: str) -> int:
    """Runs protoc into ``src/`` and writes the ``__init__.py`` files it omits."""
    destination = root / STUB_ROOT
    subprocess.run(  # noqa: S603
        [
            protoc,
            f"-I{PROTO_DIR}",
            f"--python_out={STUB_ROOT}",
            f"--pyi_out={STUB_ROOT}",
            *sorted(str(path.relative_to(root)) for path in (root / PROTO_DIR).rglob("*.proto")),
        ],
        cwd=root,
        check=True,
    )
    written = 0
    for path in sorted((destination / "loams").rglob("*_pb2.py")):
        directory = path.parent
        init = directory / "__init__.py"
        if init.exists():
            continue
        dotted = ".".join(directory.relative_to(destination).parts)
        init.write_text(INIT_MARKER.format(path=dotted), encoding="utf-8")
        written += 1
    for path in sorted((destination / "loams").rglob("*_pb2.pyi")):
        directory = path.parent
        init = directory / "__init__.pyi"
        if not init.exists():
            init.write_text("", encoding="utf-8")
            written += 1
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="the repository root")
    parser.add_argument("--protoc", default="protoc", help="the protoc to run")
    parser.add_argument(
        "--skip-stubs",
        action="store_true",
        help="render facade.py without regenerating the protobuf stubs",
    )
    arguments = parser.parse_args(argv)

    root = Path(arguments.root).resolve()
    sys.path.insert(0, str(root / STUB_ROOT))
    load_extensions(root)

    if not arguments.skip_stubs:
        count = write_stubs(root, arguments.protoc)
        print(f"wrote the protobuf stubs and {count} __init__ files under {STUB_ROOT}/loams")

    descriptor_set = read_descriptor_set(root, arguments.protoc)
    reasons = parse_reasons(
        (root / REASONS_PAGE).read_text(encoding="utf-8"), root / REASONS_PAGE
    )
    model = build_model(descriptor_set, reasons)
    out = root / FACADE_OUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(model), encoding="utf-8")
    print(f"wrote {FACADE_OUT}: {len(model.modules)} modules, {len(model.reasons)} reasons")
    for module in model.modules:
        print(f"  {module.name}: " + ", ".join(f"{call.name}({call.retry})" for call in module.calls))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
