# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: loams/devices/v1/devices.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import loams.devices.v1.devices_pb2 as loams_dot_devices_dot_v1_dot_devices__pb2


class DeviceService(Protocol):
    async def create_pairing(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_devices(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def rename_device(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def revoke_device(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def register_push_target(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def unregister_push_target(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_notification_preferences(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def set_notification_preferences(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def send_test_notification(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DeviceServiceASGIApplication(ConnectASGIApplication[DeviceService]):
    def __init__(self, service: DeviceService | AsyncGenerator[DeviceService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/loams.devices.v1.DeviceService/CreatePairing": Endpoint.unary(
                    method=MethodInfo(
                        name="CreatePairing",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_pairing,
                ),
                "/loams.devices.v1.DeviceService/ListDevices": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDevices",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_devices,
                ),
                "/loams.devices.v1.DeviceService/RenameDevice": Endpoint.unary(
                    method=MethodInfo(
                        name="RenameDevice",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.rename_device,
                ),
                "/loams.devices.v1.DeviceService/RevokeDevice": Endpoint.unary(
                    method=MethodInfo(
                        name="RevokeDevice",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.revoke_device,
                ),
                "/loams.devices.v1.DeviceService/RegisterPushTarget": Endpoint.unary(
                    method=MethodInfo(
                        name="RegisterPushTarget",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.register_push_target,
                ),
                "/loams.devices.v1.DeviceService/UnregisterPushTarget": Endpoint.unary(
                    method=MethodInfo(
                        name="UnregisterPushTarget",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.unregister_push_target,
                ),
                "/loams.devices.v1.DeviceService/GetNotificationPreferences": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNotificationPreferences",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_notification_preferences,
                ),
                "/loams.devices.v1.DeviceService/SetNotificationPreferences": Endpoint.unary(
                    method=MethodInfo(
                        name="SetNotificationPreferences",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.set_notification_preferences,
                ),
                "/loams.devices.v1.DeviceService/SendTestNotification": Endpoint.unary(
                    method=MethodInfo(
                        name="SendTestNotification",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.send_test_notification,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/loams.devices.v1.DeviceService"


class DeviceServiceClient(ConnectClient):
    async def create_pairing(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePairing",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_devices(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDevices",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def rename_device(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RenameDevice",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def revoke_device(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeDevice",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def register_push_target(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RegisterPushTarget",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def unregister_push_target(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnregisterPushTarget",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_notification_preferences(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationPreferences",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def set_notification_preferences(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetNotificationPreferences",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def send_test_notification(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendTestNotification",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class DeviceServiceSync(Protocol):
    def create_pairing(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_devices(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def rename_device(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def revoke_device(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def register_push_target(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def unregister_push_target(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_notification_preferences(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def set_notification_preferences(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def send_test_notification(self, request: loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationRequest, ctx: RequestContext) -> loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DeviceServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: DeviceServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/loams.devices.v1.DeviceService/CreatePairing": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreatePairing",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_pairing,
                ),
                "/loams.devices.v1.DeviceService/ListDevices": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDevices",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_devices,
                ),
                "/loams.devices.v1.DeviceService/RenameDevice": EndpointSync.unary(
                    method=MethodInfo(
                        name="RenameDevice",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.rename_device,
                ),
                "/loams.devices.v1.DeviceService/RevokeDevice": EndpointSync.unary(
                    method=MethodInfo(
                        name="RevokeDevice",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.revoke_device,
                ),
                "/loams.devices.v1.DeviceService/RegisterPushTarget": EndpointSync.unary(
                    method=MethodInfo(
                        name="RegisterPushTarget",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.register_push_target,
                ),
                "/loams.devices.v1.DeviceService/UnregisterPushTarget": EndpointSync.unary(
                    method=MethodInfo(
                        name="UnregisterPushTarget",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.unregister_push_target,
                ),
                "/loams.devices.v1.DeviceService/GetNotificationPreferences": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNotificationPreferences",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_notification_preferences,
                ),
                "/loams.devices.v1.DeviceService/SetNotificationPreferences": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetNotificationPreferences",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.set_notification_preferences,
                ),
                "/loams.devices.v1.DeviceService/SendTestNotification": EndpointSync.unary(
                    method=MethodInfo(
                        name="SendTestNotification",
                        service_name="loams.devices.v1.DeviceService",
                        input=loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationRequest,
                        output=loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.send_test_notification,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/loams.devices.v1.DeviceService"


class DeviceServiceClientSync(ConnectClientSync):
    def create_pairing(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePairing",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.CreatePairingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_devices(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDevices",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.ListDevicesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def rename_device(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RenameDevice",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.RenameDeviceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def revoke_device(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeDevice",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.RevokeDeviceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def register_push_target(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RegisterPushTarget",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.RegisterPushTargetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def unregister_push_target(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnregisterPushTarget",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.UnregisterPushTargetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_notification_preferences(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationPreferences",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.GetNotificationPreferencesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def set_notification_preferences(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetNotificationPreferences",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.SetNotificationPreferencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def send_test_notification(
        self,
        request: loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendTestNotification",
                service_name="loams.devices.v1.DeviceService",
                input=loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationRequest,
                output=loams_dot_devices_dot_v1_dot_devices__pb2.SendTestNotificationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


