#!/usr/bin/env bash
# Render docs/sqldb/performance.md from target-spike/*.jsonl (SQ1 Task 1).
# Medians are true medians; p95 is nearest-rank. Times are milliseconds.
# jq and awk programs are single-quoted on purpose.
# shellcheck disable=SC2016
set -euo pipefail
# shellcheck source=lib.sh source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

DOC="${DOC:-$SPIKE_ROOT/docs/sqldb/performance.md}"
J="$SPIKE_OUT"
for f in keyspace coldstart rss regions density; do
  [[ -s "$J/$f.jsonl" ]] || { log "missing $J/$f.jsonl: run the measurement scripts first"; exit 1; }
done

STATS='
def median: sort | if length == 0 then null
  elif length % 2 == 1 then .[length / 2 | floor]
  else (.[length / 2 - 1] + .[length / 2]) / 2 end;
def p95: sort | if length == 0 then null else .[(length * 0.95 | ceil) - 1] end;
def r: if . == null then "–" else (. * 10 | round / 10 | tostring) end;
def mib: . / 1024 | round;
'

{
cat <<HDR
# Loams SQL performance baselines

> Generated by \`scripts/sqldb/spike/report.sh\` from \`target-spike/*.jsonl\` (SQ1 Task 1). Do not edit the tables by hand; rerun the scripts. Rulings drawn from these numbers are R1.x in [the SQ1 plan](../plans/2026-10-08-sq1-loams-sql-tidb.md#rulings-made-during-execution); §47 cites them.

**Setup.**
- Rendered $(date -u +%Y-%m-%d) on a $(nproc)-thread x86_64 host with $(awk '/MemTotal/ { printf "%.0f", $2 / 1048576 }' /proc/meminfo) GiB RAM, **shared with other agents' builds and containers** (swap in use), so absolute numbers are conservative and noisy.
- $(podman --version). One PD and one TiKV (\`deploy/sqldb/spike\`, API v2 with TTL), host networking, all on one host.
- Images by digest from \`release/sqldb-images.toml\`: TiDB, PD and TiKV v8.5.8.
- Container memory limits: PD 1 GiB, TiKV 3 GiB (\`memory-usage-limit = 2GB\`, block cache 512 MB), each TiDB ${TIDB_MEM}.
- Every TiDB runs in keyspace mode (\`keyspace-name\` set), \`lite-init-stats = true\`, log level \`warn\`. The image is already on the host (the "pre-pulled node" case).

HDR

echo '## 1. Keyspace API (PD HTTP)'
echo
echo '| Operation | n | median | p95 | max |'
echo '|---|---:|---:|---:|---:|'
jq -rs "$STATS"'
  map(select(.ms != null and (.op | test("probe") | not)))
  | group_by(.op) | sort_by(.[0].op | {create:0, DISABLED:1, ARCHIVED:2}[.])[]
  | (map(.ms)) as $m
  | "| `\(.[0].op | if . == "create" then "POST /pd/api/v2/keyspaces" else "PUT …/state → " + . end)` | \(length) | \($m | median | r) | \($m | p95 | r) | \($m | max | r) |"' "$J/keyspace.jsonl"
jq -r 'select(.op == "TOMBSTONE_probe") | "\n`ARCHIVED → TOMBSTONE` through the same API: HTTP \(.http)."' "$J/keyspace.jsonl"
echo

cat <<'TXT'
## 2. Cold start: `tidb-server` start to the first `SELECT 1`

Phases: **start** = `podman run -d` returns (container running); **port** = from then until port 24000 accepts TCP; **query** = from then until `mysql -e 'SELECT 1'` answers. **Total** is their sum. *Bootstrap* is a fresh keyspace's first TiDB start (creates the `mysql.*` schema); *warm* restarts a bootstrapped keyspace holding N user tables (20 rows each, all analyzed, so statistics exist to load).

| Case | Tables | force-init-stats | n | start med | port med | port p95 | query med | **total med** | **total p95** | max |
|---|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|
TXT
jq -rs "$STATS"'
  group_by([.phase != "bootstrap", .tables, (.force_init_stats | not)])[]
  | "| \(.[0].phase) | \(.[0].tables) | \(.[0].force_init_stats) | \(length) | \(map(.start_ms) | median | r) | \(map(.port_ms) | median | r) | \(map(.port_ms) | p95 | r) | \(map(.query_ms) | median | r) | **\(map(.total_ms) | median | r)** | **\(map(.total_ms) | p95 | r)** | \(map(.total_ms) | max | r) |"' "$J/coldstart.jsonl"
echo

echo '### TiDB memory'
echo
echo '| When | Driver | RSS (MiB) | peak VmHWM (MiB) | cgroup (`podman stats`, MiB) | Transactions |'
echo '|---|---|---:|---:|---:|---:|'
jq -r "$STATS"'"| \(.at) | \(.driver // "–") | \(.rss_kib | mib) | \(if .hwm_kib then (.hwm_kib | mib) else "–" end) | \(.cgroup_mib | round) | \(if .txns then "\(.txns) in \(.secs) s" else "–" end) |"' "$J/rss.jsonl"
if jq -e 'select(.driver == "mysql-loop")' "$J/rss.jsonl" >/dev/null; then
  echo
  echo 'sysbench was not installed, so the load was the `mysql`-driven fallback: 10 tables × 10 000 rows, 8 clients, each transaction 10 point selects, 1 range sum over 100 rows, 1 update and 1 upsert (`coldstart.sh`). It is not comparable with sysbench `oltp_read_write` throughput; it only drives the TiDB to a busy RSS.'
fi
echo

cat <<'TXT'
## 3. Regions

### 3.1 Regions per empty database

Regions overlapping the keyspace's txn range `[x|id, x|id+1)` (PD `GET /pd/api/v1/regions`, keys decoded as memcomparable hex). Creating a keyspace also splits off one region for its raw range `r|id`, which is not counted here.

| split-table | before bootstrap | after bootstrap | start + bootstrap + stop (ms) |
|---|---:|---:|---:|
TXT
jq -r 'select(.split_table != null) | "| \(.split_table) | \(.regions_before_bootstrap) | \(.regions_after_bootstrap) | \(.bootstrap_ms) |"' "$J/regions.jsonl"
echo
echo '### 3.2 Many keyspaces (split-table = false, bootstrapped one after another)'
echo
jq -rs "$STATS"'map(select(.density_n != null) | .bootstrap_ms) | "Start + bootstrap + graceful stop of each TiDB, over \(length) keyspaces: median \(median | r) ms, p95 \(p95 | r) ms, max \(max | r) ms."' "$J/regions.jsonl"
jq -rs "$STATS"'map(select(.density_n != null) | .bootstrap_ms) | select(length >= 20) | "The first 10 took a median of \(.[0:10] | median | r) ms and the last 10 \(.[-10:] | median | r) ms."' "$J/regions.jsonl"
echo
echo '| Keyspaces | Cluster regions | Hibernated / awake peers | TiKV → PD heartbeats/s | PD region heartbeats ok/s | PD RSS (MiB) | TiKV RSS (MiB) | PD cgroup (MiB) | TiKV cgroup (MiB) |'
echo '|---:|---:|---:|---:|---:|---:|---:|---:|---:|'
jq -r "$STATS"'"| \(.keyspaces) | \(.cluster_regions) | \(.hibernated_peers) / \(.awaken_peers) | \(.tikv_pd_heartbeats_per_s) | \(.pd_region_heartbeats_ok_per_s) | \(.pd_rss_kib | mib) | \(.tikv_rss_kib | mib) | \(.pd_cgroup_mib | round) | \(.tikv_cgroup_mib | round) |"' "$J/density.jsonl"
echo
jq -rs 'map(select(.keyspaces > 0)) | if length >= 2 then
  (.[-1].cluster_regions - .[0].cluster_regions) / (.[-1].keyspaces - .[0].keyspaces)
  | "Marginal cost: **\(. * 100 | round / 100) regions per bootstrapped empty database** (from the first to the last checkpoint). Heartbeat rates are averaged over a \(env.HB_WINDOW // "30") s window after the region count settled."
  else empty end' "$J/density.jsonl"
# SQ1 Task 5: written by the LOAMS_IT_SQLDB test resume_p95_under_5s_on_spike_stack.
if [[ -s "$J/resume-through-gate.jsonl" ]]; then
  echo
  cat <<'TXT'
## 4. Wake on connect through the gate (SQ1 Task 5)

A branch suspended by the lifecycle host (`Lifecycles`, `LocalRuntime` scaled to 0) and woken by a client connecting through `loams-sqlgate`: the time from the client's TCP connect to the first result of `SELECT 1`. It covers the gate's TLS and login, `EnsureRunning`, `scale(branch, 1)`, TiDB's warm start, the resume probe and the upstream login (`resume_p95_under_5s_on_spike_stack`, 20 cycles on one keyspace).

TXT
  jq -rs "$STATS"'map(.connect_to_first_result_ms) | "| Cycles | median (ms) | p95 (ms) | max (ms) |\n|---:|---:|---:|---:|\n| \(length) | \(median | r) | \(p95 | r) | \(max | r) |"' "$J/resume-through-gate.jsonl"
fi
} > "$DOC"
log "wrote $DOC"
