/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this install is and how people sign in */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** First-run setup: create the org and its owner with the setup token */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user, their org and a CSRF token */
        get: operations["getSession"];
        put?: never;
        /** Sign in with email and password */
        post: operations["createSession"];
        /** Sign out */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to an OIDC provider */
        get: operations["startOidcSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The org */
        get: operations["getOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename the org or change its sign-in rules */
        patch: operations["updateOrg"];
        trace?: never;
    };
    "/api/v1/org/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The org's members */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/members/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from the org */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending invitations */
        get: operations["listInvitations"];
        put?: never;
        /** Invite someone by email */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The org's teams */
        get: operations["listTeams"];
        put?: never;
        /** Create a team */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A team, its members and its project roles */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a member to a team */
        post: operations["addTeamMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects the caller can see */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who has which role on a project */
        get: operations["listProjectAccess"];
        put?: never;
        /** Give a team or user a project role */
        post: operations["grantProjectAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A project's environments */
        get: operations["listEnvironments"];
        put?: never;
        /** Create an environment, and with it a namespace */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An environment and its namespace */
        get: operations["getEnvironment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storage, queries and writes over the current period */
        get: operations["getEnvironmentUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A project's agents */
        get: operations["listAgents"];
        put?: never;
        /** Register an agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An agent */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change an agent's policy, TTL cap or limits */
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/api/v1/agents/{agent}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend an agent and revoke its tokens */
        post: operations["suspendAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Let a suspended agent get tokens again */
        post: operations["resumeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An agent's unexpired tokens */
        get: operations["listAgentTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent}/trust-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workload identities that may act as the agent */
        get: operations["listTrustPolicies"];
        put?: never;
        /** Trust a workload identity */
        post: operations["createTrustPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{jti}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one access token */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/service-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A project's service accounts */
        get: operations["listServiceAccounts"];
        put?: never;
        /** Create a service account */
        post: operations["createServiceAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An environment's API keys */
        get: operations["listApiKeys"];
        put?: never;
        /** Create an API key; the secret is returned once */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The audit log, newest first */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Token exchange (RFC 8693), authorization code with PKCE, or refresh */
        post: operations["exchangeToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start user delegation: redirects to the console's consent screen */
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/oauth/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record the signed-in user's consent decision and get the client redirect */
        post: operations["decideConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-protected-resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Protected resource metadata (RFC 9728), for MCP clients */
        get: operations["getProtectedResourceMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth authorization server metadata (RFC 8414) */
        get: operations["getAuthorizationServerMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The public keys that sign access tokens */
        get: operations["getJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The engine's error body: a stable code and a human message. */
        Error: {
            error: string;
            message: string;
        };
        /** @enum {string} */
        Edition: "oss" | "cloud" | "byoc";
        /** @description What this install is and how people sign in. Public: the console reads it before sign-in. */
        Instance: {
            name: string;
            edition: components["schemas"]["Edition"];
            version: string;
            /** @description True until first-run setup has created the org and its owner. */
            setup_required: boolean;
            sign_in: components["schemas"]["SignInMethods"];
            features: {
                billing: boolean;
                multi_org: boolean;
                passkeys: boolean;
            };
        };
        SignInMethods: {
            password: boolean;
            totp: boolean;
            passkeys: boolean;
            oidc: components["schemas"]["OidcProvider"][];
        };
        OidcProvider: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "keycloak" | "okta" | "entra" | "google" | "authentik" | "dex" | "generic";
        };
        SetupRequest: {
            setup_token: string;
            org_name: string;
            name: string;
            email: string;
            password: string;
        };
        LoginRequest: {
            email: string;
            password: string;
            totp_code?: string;
        };
        /** @enum {string} */
        OrgRole: "owner" | "admin" | "member";
        User: {
            id: string;
            name: string;
            email: string;
            avatar_url: string | null;
            two_factor: boolean;
            sso: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at: string | null;
        };
        Session: {
            user: components["schemas"]["User"];
            org: components["schemas"]["Org"];
            role: components["schemas"]["OrgRole"];
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        Org: {
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            created_at: string;
            require_two_factor: boolean;
            allowed_domains: string[];
        };
        OrgUpdate: {
            name?: string;
            require_two_factor?: boolean;
            allowed_domains?: string[];
        };
        Member: {
            user: components["schemas"]["User"];
            role: components["schemas"]["OrgRole"];
            teams: string[];
            /** Format: date-time */
            joined_at: string;
        };
        MemberList: {
            members: components["schemas"]["Member"][];
        };
        Invitation: {
            id: string;
            email: string;
            role: components["schemas"]["OrgRole"];
            teams: string[];
            invited_by: components["schemas"]["SubjectRef"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
        };
        InvitationCreate: {
            email: string;
            role: components["schemas"]["OrgRole"];
            teams?: string[];
        };
        InvitationList: {
            invitations: components["schemas"]["Invitation"][];
        };
        Team: {
            id: string;
            name: string;
            slug: string;
            description: string;
            member_count: number;
            idp_group: string | null;
            /** Format: date-time */
            created_at: string;
        };
        TeamDetail: {
            team: components["schemas"]["Team"];
            members: components["schemas"]["User"][];
            projects: components["schemas"]["ProjectGrantRef"][];
        };
        TeamCreate: {
            name: string;
            description?: string;
            idp_group?: string | null;
        };
        TeamMemberAdd: {
            user: string;
        };
        TeamList: {
            teams: components["schemas"]["Team"][];
        };
        /** @enum {string} */
        SubjectKind: "user" | "team" | "agent" | "service_account" | "system";
        SubjectRef: {
            kind: components["schemas"]["SubjectKind"];
            id: string;
            name: string;
        };
        Project: {
            id: string;
            slug: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            environment_count: number;
            agent_count: number;
        };
        ProjectCreate: {
            name: string;
            slug?: string;
            description?: string;
        };
        ProjectList: {
            projects: components["schemas"]["Project"][];
        };
        /** @enum {string} */
        ProjectRole: "admin" | "developer" | "viewer";
        ProjectGrantRef: {
            project: string;
            role: components["schemas"]["ProjectRole"];
        };
        Grant: {
            id: string;
            subject: components["schemas"]["SubjectRef"];
            role: components["schemas"]["ProjectRole"];
            /** Format: date-time */
            created_at: string;
        };
        GrantCreate: {
            subject: {
                /** @enum {string} */
                kind: "user" | "team";
                id: string;
            };
            role: components["schemas"]["ProjectRole"];
        };
        GrantList: {
            grants: components["schemas"]["Grant"][];
        };
        Environment: {
            id: string;
            slug: string;
            name: string;
            project: string;
            /** @description The engine namespace this environment is (1:1). */
            namespace: string;
            /** @description Destructive actions need the project admin role. */
            protected: boolean;
            region: string;
            bucket: string;
            /** Format: date-time */
            created_at: string;
            stats: components["schemas"]["EnvironmentStats"];
        };
        EnvironmentStats: {
            collections: number;
            documents: number;
            storage_bytes: number;
            queries_24h: number;
            writes_24h: number;
        };
        EnvironmentCreate: {
            name: string;
            slug?: string;
            protected?: boolean;
        };
        EnvironmentList: {
            environments: components["schemas"]["Environment"][];
        };
        Usage: {
            environment: string;
            /** Format: date-time */
            period_start: string;
            /** Format: date-time */
            period_end: string;
            limits: {
                storage_bytes: number;
                queries_month: number;
                writes_month: number;
            } | null;
            series: {
                /** Format: date */
                date: string;
                queries: number;
                writes: number;
                storage_bytes: number;
            }[];
        };
        /** @enum {string} */
        Action: "collections:read" | "collections:write" | "documents:delete" | "query" | "streams:read" | "streams:produce" | "mcp:tools";
        /** @description What a principal may do in one environment; collections null means all. */
        PolicyRule: {
            environment: string;
            actions: components["schemas"]["Action"][];
            collections: string[] | null;
        };
        AgentLimits: {
            requests_per_s: number;
            concurrent_queries: number;
        };
        /** @enum {string} */
        AgentStatus: "active" | "suspended";
        /** @description An AI agent: a principal that only ever holds short-lived tokens (design §19 §5). */
        Agent: {
            id: string;
            name: string;
            description: string;
            project: string;
            owner: components["schemas"]["SubjectRef"];
            status: components["schemas"]["AgentStatus"];
            policy: components["schemas"]["PolicyRule"][];
            max_token_ttl_s: number;
            limits: components["schemas"]["AgentLimits"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_active_at: string | null;
            active_tokens: number;
        };
        AgentCreate: {
            name: string;
            description?: string;
            owner: {
                /** @enum {string} */
                kind: "user" | "team";
                id: string;
            };
            policy: components["schemas"]["PolicyRule"][];
            max_token_ttl_s?: number;
            limits?: components["schemas"]["AgentLimits"];
        };
        AgentUpdate: {
            description?: string;
            policy?: components["schemas"]["PolicyRule"][];
            max_token_ttl_s?: number;
            limits?: components["schemas"]["AgentLimits"];
        };
        AgentList: {
            agents: components["schemas"]["Agent"][];
        };
        /** @enum {string} */
        TokenFlow: "federation" | "delegation" | "vending";
        AgentToken: {
            jti: string;
            agent: string;
            environment: string;
            scopes: components["schemas"]["Action"][];
            flow: components["schemas"]["TokenFlow"];
            /** @description The federated subject (for example repo:acme/search:ref:refs/heads/main), or the delegating user's id. */
            subject: string;
            acting_for: components["schemas"]["SubjectRef"] | null;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at: string;
        };
        AgentTokenList: {
            tokens: components["schemas"]["AgentToken"][];
        };
        /** @description Which external workload identities may exchange their token for this agent's. */
        TrustPolicy: {
            id: string;
            agent: string;
            name: string;
            issuer: string;
            audience: string;
            /** @description Glob over the federated token's sub claim. */
            subject_pattern: string;
            environments: string[];
            /** Format: date-time */
            created_at: string;
        };
        TrustPolicyCreate: {
            name: string;
            issuer: string;
            audience: string;
            subject_pattern: string;
            environments: string[];
        };
        TrustPolicyList: {
            trust_policies: components["schemas"]["TrustPolicy"][];
        };
        ServiceAccount: {
            id: string;
            name: string;
            description: string;
            project: string;
            /** Format: date-time */
            created_at: string;
            key_count: number;
            /** Format: date-time */
            last_active_at: string | null;
        };
        ServiceAccountCreate: {
            name: string;
            description?: string;
        };
        ServiceAccountList: {
            service_accounts: components["schemas"]["ServiceAccount"][];
        };
        ApiKey: {
            id: string;
            name: string;
            /** @description loams_<key_id>, safe to show; the secret is never returned again. */
            prefix: string;
            environment: string;
            principal: components["schemas"]["SubjectRef"];
            scopes: components["schemas"]["Action"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            last_used_at: string | null;
        };
        ApiKeyCreate: {
            name: string;
            service_account?: string | null;
            scopes: components["schemas"]["Action"][];
            expires_in_days?: number;
        };
        ApiKeyCreated: {
            key: components["schemas"]["ApiKey"];
            /** @description The full key, shown once. */
            secret: string;
        };
        ApiKeyList: {
            keys: components["schemas"]["ApiKey"][];
        };
        /** @enum {string} */
        AuditOutcome: "success" | "denied";
        AuditEvent: {
            id: string;
            /** Format: date-time */
            at: string;
            actor: components["schemas"]["SubjectRef"];
            acting_for: components["schemas"]["SubjectRef"] | null;
            /** @description Dotted, for example agent.token.issued or collection.dropped. */
            action: string;
            target: components["schemas"]["SubjectRefOrResource"];
            project: string | null;
            environment: string | null;
            ip: string | null;
            outcome: components["schemas"]["AuditOutcome"];
        };
        SubjectRefOrResource: {
            kind: string;
            id: string;
            name: string;
        };
        AuditPage: {
            events: components["schemas"]["AuditEvent"][];
            next_before: string | null;
        };
        /** @description application/x-www-form-urlencoded, per RFC 8693 and OAuth 2.1. */
        TokenRequest: {
            /** @enum {string} */
            grant_type: "urn:ietf:params:oauth:grant-type:token-exchange" | "authorization_code" | "refresh_token";
            subject_token?: string;
            subject_token_type?: string;
            actor_token?: string;
            actor_token_type?: string;
            /** @description The environment, as <project>/<environment>. */
            audience?: string;
            /** @description Space-separated actions. */
            scope?: string;
            requested_token_type?: string;
            code?: string;
            code_verifier?: string;
            redirect_uri?: string;
            client_id?: string;
            refresh_token?: string;
        };
        TokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            expires_in: number;
            scope: string;
            issued_token_type: string;
        };
        OAuthError: {
            error: string;
            error_description?: string;
        };
        AuthorizationServerMetadata: {
            issuer: string;
            authorization_endpoint: string;
            token_endpoint: string;
            jwks_uri: string;
            grant_types_supported: string[];
            code_challenge_methods_supported: string[];
            token_endpoint_auth_methods_supported: string[];
            scopes_supported: string[];
            response_types_supported: string[];
        };
        /** @description RFC 9728. A 401 from a protected route carries WWW-Authenticate: Bearer resource_metadata="<this document's URL>". */
        ProtectedResourceMetadata: {
            resource: string;
            authorization_servers: string[];
            scopes_supported: string[];
            bearer_methods_supported: string[];
            resource_documentation: string;
        };
        /** @description The signed-in user's answer on the consent screen, carrying the authorize request's parameters. */
        ConsentDecision: {
            /** @enum {string} */
            decision: "allow" | "deny";
            client_id: string;
            redirect_uri: string;
            scope: string;
            audience: string;
            state: string;
            code_challenge: string;
            /** @enum {string} */
            code_challenge_method: "S256";
        };
        ConsentResult: {
            /** @description The client's redirect_uri with code and state, or with error=access_denied. */
            redirect_to: string;
        };
        Jwks: {
            keys: {
                kty: string;
                crv: string;
                x: string;
                kid: string;
                use: string;
                alg: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    startOidcSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description To the provider's authorization endpoint */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The team's id */
                team: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetail"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The team's id */
                team: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamMemberAdd"];
            };
        };
        responses: {
            /** @description Done */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listProjectAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    grantProjectAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grant"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
                /** @description The environment's slug */
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEnvironmentUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
                /** @description The environment's slug */
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent's id */
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent's id */
                agent: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    suspendAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent's id */
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resumeAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent's id */
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAgentTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent's id */
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTokenList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTrustPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent's id */
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustPolicyList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTrustPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent's id */
                agent: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrustPolicyCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustPolicy"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jti: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listServiceAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAccountList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createServiceAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceAccountCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAccount"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
                /** @description The environment's slug */
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project's slug */
                project: string;
                /** @description The environment's slug */
                environment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                project?: string;
                /** @description A principal id */
                actor?: string;
                /** @description An event id, for the next page */
                before?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exchangeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description A token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description An OAuth error (RFC 6749 section 5.2) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    authorize: {
        parameters: {
            query: {
                client_id: string;
                redirect_uri: string;
                response_type: string;
                code_challenge: string;
                code_challenge_method: string;
                scope: string;
                state: string;
                audience: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description To /ui/consent, with the request's parameters */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    decideConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentDecision"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResult"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProtectedResourceMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtectedResourceMetadata"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAuthorizationServerMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationServerMetadata"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getJwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jwks"];
                };
            };
            /** @description A client error: invalid_argument, unauthenticated, permission_denied, not_found, already_exists, rate_limited */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
