# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: loams/instance/v1/instance.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import loams.instance.v1.instance_pb2 as loams_dot_instance_dot_v1_dot_instance__pb2


class InstanceService(Protocol):
    async def get_instance(self, request: loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceRequest, ctx: RequestContext) -> loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def who_am_i(self, request: loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIRequest, ctx: RequestContext) -> loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class InstanceServiceASGIApplication(ConnectASGIApplication[InstanceService]):
    def __init__(self, service: InstanceService | AsyncGenerator[InstanceService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/loams.instance.v1.InstanceService/GetInstance": Endpoint.unary(
                    method=MethodInfo(
                        name="GetInstance",
                        service_name="loams.instance.v1.InstanceService",
                        input=loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceRequest,
                        output=loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_instance,
                ),
                "/loams.instance.v1.InstanceService/WhoAmI": Endpoint.unary(
                    method=MethodInfo(
                        name="WhoAmI",
                        service_name="loams.instance.v1.InstanceService",
                        input=loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIRequest,
                        output=loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.who_am_i,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/loams.instance.v1.InstanceService"


class InstanceServiceClient(ConnectClient):
    async def get_instance(
        self,
        request: loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInstance",
                service_name="loams.instance.v1.InstanceService",
                input=loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceRequest,
                output=loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def who_am_i(
        self,
        request: loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="WhoAmI",
                service_name="loams.instance.v1.InstanceService",
                input=loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIRequest,
                output=loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )


class InstanceServiceSync(Protocol):
    def get_instance(self, request: loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceRequest, ctx: RequestContext) -> loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def who_am_i(self, request: loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIRequest, ctx: RequestContext) -> loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class InstanceServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: InstanceServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/loams.instance.v1.InstanceService/GetInstance": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetInstance",
                        service_name="loams.instance.v1.InstanceService",
                        input=loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceRequest,
                        output=loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_instance,
                ),
                "/loams.instance.v1.InstanceService/WhoAmI": EndpointSync.unary(
                    method=MethodInfo(
                        name="WhoAmI",
                        service_name="loams.instance.v1.InstanceService",
                        input=loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIRequest,
                        output=loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.who_am_i,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/loams.instance.v1.InstanceService"


class InstanceServiceClientSync(ConnectClientSync):
    def get_instance(
        self,
        request: loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInstance",
                service_name="loams.instance.v1.InstanceService",
                input=loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceRequest,
                output=loams_dot_instance_dot_v1_dot_instance__pb2.GetInstanceResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def who_am_i(
        self,
        request: loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="WhoAmI",
                service_name="loams.instance.v1.InstanceService",
                input=loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIRequest,
                output=loams_dot_instance_dot_v1_dot_instance__pb2.WhoAmIResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
