# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: loams/notifications/v1/notifications.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import loams.notifications.v1.notifications_pb2 as loams_dot_notifications_dot_v1_dot_notifications__pb2


class NotificationService(Protocol):
    async def list_notifications(self, request: loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsRequest, ctx: RequestContext) -> loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def watch_notifications(self, request: loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsRequest, ctx: RequestContext) -> AsyncIterator[loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def mark_read(self, request: loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadRequest, ctx: RequestContext) -> loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NotificationServiceASGIApplication(ConnectASGIApplication[NotificationService]):
    def __init__(self, service: NotificationService | AsyncGenerator[NotificationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/loams.notifications.v1.NotificationService/ListNotifications": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNotifications",
                        service_name="loams.notifications.v1.NotificationService",
                        input=loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsRequest,
                        output=loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_notifications,
                ),
                "/loams.notifications.v1.NotificationService/WatchNotifications": Endpoint.server_stream(
                    method=MethodInfo(
                        name="WatchNotifications",
                        service_name="loams.notifications.v1.NotificationService",
                        input=loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsRequest,
                        output=loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch_notifications,
                ),
                "/loams.notifications.v1.NotificationService/MarkRead": Endpoint.unary(
                    method=MethodInfo(
                        name="MarkRead",
                        service_name="loams.notifications.v1.NotificationService",
                        input=loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadRequest,
                        output=loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.mark_read,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/loams.notifications.v1.NotificationService"


class NotificationServiceClient(ConnectClient):
    async def list_notifications(
        self,
        request: loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNotifications",
                service_name="loams.notifications.v1.NotificationService",
                input=loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsRequest,
                output=loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def watch_notifications(
        self,
        request: loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchNotifications",
                service_name="loams.notifications.v1.NotificationService",
                input=loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsRequest,
                output=loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def mark_read(
        self,
        request: loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkRead",
                service_name="loams.notifications.v1.NotificationService",
                input=loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadRequest,
                output=loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class NotificationServiceSync(Protocol):
    def list_notifications(self, request: loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsRequest, ctx: RequestContext) -> loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def watch_notifications(self, request: loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsRequest, ctx: RequestContext) -> Iterator[loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def mark_read(self, request: loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadRequest, ctx: RequestContext) -> loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NotificationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: NotificationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/loams.notifications.v1.NotificationService/ListNotifications": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListNotifications",
                        service_name="loams.notifications.v1.NotificationService",
                        input=loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsRequest,
                        output=loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_notifications,
                ),
                "/loams.notifications.v1.NotificationService/WatchNotifications": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="WatchNotifications",
                        service_name="loams.notifications.v1.NotificationService",
                        input=loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsRequest,
                        output=loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch_notifications,
                ),
                "/loams.notifications.v1.NotificationService/MarkRead": EndpointSync.unary(
                    method=MethodInfo(
                        name="MarkRead",
                        service_name="loams.notifications.v1.NotificationService",
                        input=loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadRequest,
                        output=loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.mark_read,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/loams.notifications.v1.NotificationService"


class NotificationServiceClientSync(ConnectClientSync):
    def list_notifications(
        self,
        request: loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNotifications",
                service_name="loams.notifications.v1.NotificationService",
                input=loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsRequest,
                output=loams_dot_notifications_dot_v1_dot_notifications__pb2.ListNotificationsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def watch_notifications(
        self,
        request: loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchNotifications",
                service_name="loams.notifications.v1.NotificationService",
                input=loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsRequest,
                output=loams_dot_notifications_dot_v1_dot_notifications__pb2.WatchNotificationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def mark_read(
        self,
        request: loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkRead",
                service_name="loams.notifications.v1.NotificationService",
                input=loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadRequest,
                output=loams_dot_notifications_dot_v1_dot_notifications__pb2.MarkReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
