# @generated by protoc-gen-loams-facade from proto/. Do not edit.
#
# The SDK facade of design §44 §7.3: one Protocol per service annotated
# with `loams.options.v1.module`, one method per `loams.options.v1.facade`
# call, and the binding table the hand-written runtime dispatches through.
# Regenerate with `scripts/sdk/gen.sh python`; the drift check in CI fails
# if this file is stale.
# ruff: noqa
# fmt: off

"""The `loams` Python SDK's generated facade."""

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from dataclasses import dataclass
from typing import ClassVar, Final, Literal, Protocol

from loams._runtime.call import CallOptions, LoamsError, ResponseStream
from loams.instance.v1.instance_pb2 import GetInstanceRequest, GetInstanceResponse, WhoAmIRequest, WhoAmIResponse
from loams.instance.v1.instance_connect import InstanceServiceClient, InstanceServiceClientSync
from loams.live.v1.live_pb2 import DeployRequest, DeployResponse, ModifyQuerySetRequest, ModifyQuerySetResponse, MutateRequest, MutateResponse, QueryRequest, QueryResponse, Transition, WatchRequest
from loams.live.v1.live_connect import LiveServiceClient, LiveServiceClientSync

PROTO_REV: Final[str] = "v1"
"""The proto revision this SDK was generated from (`LOAMS_PROTO_REV`,
design §44 §10.3). `loams.system.version()` checks it against the server's
`GetInstance.api_versions`."""

Reason = Literal[
    "approval_expired",
    "approval_already_decided",
    "approval_stale_revision",
    "requester_cannot_approve",
    "decision_proof_invalid",
    "step_up_required",
    "reason_required",
    "invalid_decision",
    "pairing_expired",
    "pairing_used",
    "device_revoked",
    "push_target_unknown",
    "not_implemented",
    "feature_not_in_variant",
    "invalid_argument",
    "not_found",
    "already_exists",
    "permission_denied",
    "token_expired",
    "unauthenticated",
    "failed_precondition",
    "resource_exhausted",
    "unavailable",
    "deadline_exceeded",
    "aborted",
    "internal",
]
"""A stable, machine-readable cause of a failed RPC.

Within an API major version a reason is never renamed and never removed, so
this literal only grows.
"""

REASONS: Final[tuple[Reason, ...]] = (
    "approval_expired",
    "approval_already_decided",
    "approval_stale_revision",
    "requester_cannot_approve",
    "decision_proof_invalid",
    "step_up_required",
    "reason_required",
    "invalid_decision",
    "pairing_expired",
    "pairing_used",
    "device_revoked",
    "push_target_unknown",
    "not_implemented",
    "feature_not_in_variant",
    "invalid_argument",
    "not_found",
    "already_exists",
    "permission_denied",
    "token_expired",
    "unauthenticated",
    "failed_precondition",
    "resource_exhausted",
    "unavailable",
    "deadline_exceeded",
    "aborted",
    "internal",
)

#: The Connect code each reason is raised under, from the same registry.
REASON_CODES: Final[dict[Reason, str]] = {
    "approval_expired": "failed_precondition",
    "approval_already_decided": "failed_precondition",
    "approval_stale_revision": "failed_precondition",
    "requester_cannot_approve": "permission_denied",
    "decision_proof_invalid": "permission_denied",
    "step_up_required": "unauthenticated",
    "reason_required": "invalid_argument",
    "invalid_decision": "invalid_argument",
    "pairing_expired": "failed_precondition",
    "pairing_used": "failed_precondition",
    "device_revoked": "unauthenticated",
    "push_target_unknown": "not_found",
    "not_implemented": "unimplemented",
    "feature_not_in_variant": "unimplemented",
    "invalid_argument": "invalid_argument",
    "not_found": "not_found",
    "already_exists": "already_exists",
    "permission_denied": "permission_denied",
    "token_expired": "unauthenticated",
    "unauthenticated": "unauthenticated",
    "failed_precondition": "failed_precondition",
    "resource_exhausted": "resource_exhausted",
    "unavailable": "unavailable",
    "deadline_exceeded": "deadline_exceeded",
    "aborted": "aborted",
    "internal": "internal",
}

#: The reason a package the build variant does not carry answers with
#: (design §44 §4, D600). Every RPC of such a package refuses with it and
#: names the variant in `metadata.variant`; the runtime turns that refusal
#: into a `FeatureNotInVariantError`, so `loams.system.available()` answers
#: the same question from `GetInstance.services[]` without a failing call.
FEATURE_NOT_IN_VARIANT: Final[Reason] = "feature_not_in_variant"

Idempotency = Literal["no_side_effects", "idempotent", "none"]
Retry = Literal["safe", "manual"]
Streaming = Literal["unary", "server"]

PROTO_PACKAGES: Final[tuple[str, ...]] = (
    "google.protobuf",
    "loams.approvals.v1",
    "loams.devices.v1",
    "loams.errors.v1",
    "loams.instance.v1",
    "loams.live.v1",
    "loams.notifications.v1",
    "loams.operations.v1",
    "loams.options.v1",
)

@dataclass(frozen=True, slots=True)
class Pagination:
    """AIP-158 paging, named by `FacadeOptions.pagination`."""

    items: str
    next_page_token: str


@dataclass(frozen=True, slots=True)
class CallBinding:
    """One facade call, as the runtime dispatches it."""

    #: The module the call is exposed on.
    module: str
    #: The call's name, in `snake_case`.
    name: str
    #: The name `FacadeOptions` gave it, in `snake_case`.
    proto_name: str
    #: The method that backs the call.
    method: str
    #: The RPC, as `package.Service/Method`, which is the path curl and grpcurl use.
    rpc: str
    service: str
    package: str
    idempotency: Idempotency
    retry: Retry
    streaming: Streaming
    pagination: Pagination | None


@dataclass(frozen=True, slots=True)
class ModuleBinding:
    """One SDK module and its calls."""

    name: str
    summary: str
    service: str
    package: str
    unstable: bool
    #: True for a second facade name for the same RPCs, which has no summary of its own.
    derived: bool
    calls: tuple[CallBinding, ...]


#: Every annotated service, as the module catalogue. Order is by module name.
MODULES: Final[tuple[ModuleBinding, ...]] = (
    ModuleBinding(
        name="instance",
        summary="What this instance is, and who the caller is on it.",
        service="loams.instance.v1.InstanceService",
        package="loams.instance.v1",
        unstable=False,
        derived=False,
        calls=(
            CallBinding(
                module="instance",
                name="get_instance",
                proto_name="getInstance",
                method="GetInstance",
                rpc="loams.instance.v1.InstanceService/GetInstance",
                service="loams.instance.v1.InstanceService",
                package="loams.instance.v1",
                idempotency="no_side_effects",
                retry="safe",
                streaming="unary",
                pagination=None,
            ),
            CallBinding(
                module="instance",
                name="who_am_i",
                proto_name="whoAmI",
                method="WhoAmI",
                rpc="loams.instance.v1.InstanceService/WhoAmI",
                service="loams.instance.v1.InstanceService",
                package="loams.instance.v1",
                idempotency="no_side_effects",
                retry="safe",
                streaming="unary",
                pagination=None,
            ),
        ),
    ),
    ModuleBinding(
        name="live",
        summary="Live sync: watch a query set over a server stream.",
        service="loams.live.v1.LiveService",
        package="loams.live.v1",
        unstable=True,
        derived=False,
        calls=(
            CallBinding(
                module="live",
                name="modify_query_set",
                proto_name="modifyQuerySet",
                method="ModifyQuerySet",
                rpc="loams.live.v1.LiveService/ModifyQuerySet",
                service="loams.live.v1.LiveService",
                package="loams.live.v1",
                idempotency="none",
                retry="manual",
                streaming="unary",
                pagination=None,
            ),
            CallBinding(
                module="live",
                name="watch",
                proto_name="watch",
                method="Watch",
                rpc="loams.live.v1.LiveService/Watch",
                service="loams.live.v1.LiveService",
                package="loams.live.v1",
                idempotency="none",
                retry="manual",
                streaming="server",
                pagination=None,
            ),
        ),
    ),
    ModuleBinding(
        name="tables",
        summary="",
        service="loams.live.v1.LiveService",
        package="loams.live.v1",
        unstable=True,
        derived=True,
        calls=(
            CallBinding(
                module="tables",
                name="deploy",
                proto_name="deploy",
                method="Deploy",
                rpc="loams.live.v1.LiveService/Deploy",
                service="loams.live.v1.LiveService",
                package="loams.live.v1",
                idempotency="none",
                retry="manual",
                streaming="unary",
                pagination=None,
            ),
            CallBinding(
                module="tables",
                name="mutate",
                proto_name="mutate",
                method="Mutate",
                rpc="loams.live.v1.LiveService/Mutate",
                service="loams.live.v1.LiveService",
                package="loams.live.v1",
                idempotency="none",
                retry="manual",
                streaming="unary",
                pagination=None,
            ),
            CallBinding(
                module="tables",
                name="query",
                proto_name="query",
                method="Query",
                rpc="loams.live.v1.LiveService/Query",
                service="loams.live.v1.LiveService",
                package="loams.live.v1",
                idempotency="none",
                retry="manual",
                streaming="unary",
                pagination=None,
            ),
        ),
    ),
)

class InstanceModule(Protocol):
    """`loams.instance` — What this instance is, and who the caller is on it.

    Wraps `loams.instance.v1.InstanceService`.
    """

    module: ClassVar[Literal["instance"]]
    service: ClassVar[Literal["loams.instance.v1.InstanceService"]]
    unstable: ClassVar[Literal[False]]
    """`loams.instance.v1.InstanceService/GetInstance`, retried: safe.
    """
    async def get_instance(
        self,
        request: loams.instance.v1.instance_pb2.GetInstanceRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.instance.v1.instance_pb2.GetInstanceResponse:
        ...

    """`loams.instance.v1.InstanceService/WhoAmI`, retried: safe.
    """
    async def who_am_i(
        self,
        request: loams.instance.v1.instance_pb2.WhoAmIRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.instance.v1.instance_pb2.WhoAmIResponse:
        ...



class InstanceModuleSync(Protocol):
    """`loams.instance` — What this instance is, and who the caller is on it.

    Wraps `loams.instance.v1.InstanceService`.
    """

    module: ClassVar[Literal["instance"]]
    service: ClassVar[Literal["loams.instance.v1.InstanceService"]]
    unstable: ClassVar[Literal[False]]
    """`loams.instance.v1.InstanceService/GetInstance`, retried: safe.
    """
    def get_instance(
        self,
        request: loams.instance.v1.instance_pb2.GetInstanceRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.instance.v1.instance_pb2.GetInstanceResponse:
        ...

    """`loams.instance.v1.InstanceService/WhoAmI`, retried: safe.
    """
    def who_am_i(
        self,
        request: loams.instance.v1.instance_pb2.WhoAmIRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.instance.v1.instance_pb2.WhoAmIResponse:
        ...



class LiveModule(Protocol):
    """`loams.live` — Live sync: watch a query set over a server stream.

    Wraps `loams.live.v1.LiveService`. Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3).
    """

    module: ClassVar[Literal["live"]]
    service: ClassVar[Literal["loams.live.v1.LiveService"]]
    unstable: ClassVar[Literal[True]]
    """`loams.live.v1.LiveService/ModifyQuerySet`, retried: manual.
    """
    async def modify_query_set(
        self,
        request: loams.live.v1.live_pb2.ModifyQuerySetRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.live.v1.live_pb2.ModifyQuerySetResponse:
        ...

    """`loams.live.v1.LiveService/Watch`, retried: manual.
    """
    def watch(
        self,
        request: loams.live.v1.live_pb2.WatchRequest,
        *,
        options: CallOptions | None = None,
    ) -> AsyncIterator[loams.live.v1.live_pb2.Transition]:
        ...



class LiveModuleSync(Protocol):
    """`loams.live` — Live sync: watch a query set over a server stream.

    Wraps `loams.live.v1.LiveService`. Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3).
    """

    module: ClassVar[Literal["live"]]
    service: ClassVar[Literal["loams.live.v1.LiveService"]]
    unstable: ClassVar[Literal[True]]
    """`loams.live.v1.LiveService/ModifyQuerySet`, retried: manual.
    """
    def modify_query_set(
        self,
        request: loams.live.v1.live_pb2.ModifyQuerySetRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.live.v1.live_pb2.ModifyQuerySetResponse:
        ...

    """`loams.live.v1.LiveService/Watch`, retried: manual.
    """
    def watch(
        self,
        request: loams.live.v1.live_pb2.WatchRequest,
        *,
        options: CallOptions | None = None,
    ) -> Iterator[loams.live.v1.live_pb2.Transition]:
        ...



class TablesModule(Protocol):
    """A second facade name for the same RPCs, exposed as `loams.tables`.

    Wraps `loams.live.v1.LiveService`. Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3).
    """

    module: ClassVar[Literal["tables"]]
    service: ClassVar[Literal["loams.live.v1.LiveService"]]
    unstable: ClassVar[Literal[True]]
    """`loams.live.v1.LiveService/Deploy`, retried: manual.
    """
    async def deploy(
        self,
        request: loams.live.v1.live_pb2.DeployRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.live.v1.live_pb2.DeployResponse:
        ...

    """`loams.live.v1.LiveService/Mutate`, retried: manual.
    """
    async def mutate(
        self,
        request: loams.live.v1.live_pb2.MutateRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.live.v1.live_pb2.MutateResponse:
        ...

    """`loams.live.v1.LiveService/Query`, retried: manual.
    """
    async def query(
        self,
        request: loams.live.v1.live_pb2.QueryRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.live.v1.live_pb2.QueryResponse:
        ...



class TablesModuleSync(Protocol):
    """A second facade name for the same RPCs, exposed as `loams.tables`.

    Wraps `loams.live.v1.LiveService`. Its wire contract may still change, so `buf breaking` skips it and an SDK marks it experimental (§44 §10.3).
    """

    module: ClassVar[Literal["tables"]]
    service: ClassVar[Literal["loams.live.v1.LiveService"]]
    unstable: ClassVar[Literal[True]]
    """`loams.live.v1.LiveService/Deploy`, retried: manual.
    """
    def deploy(
        self,
        request: loams.live.v1.live_pb2.DeployRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.live.v1.live_pb2.DeployResponse:
        ...

    """`loams.live.v1.LiveService/Mutate`, retried: manual.
    """
    def mutate(
        self,
        request: loams.live.v1.live_pb2.MutateRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.live.v1.live_pb2.MutateResponse:
        ...

    """`loams.live.v1.LiveService/Query`, retried: manual.
    """
    def query(
        self,
        request: loams.live.v1.live_pb2.QueryRequest,
        *,
        options: CallOptions | None = None,
    ) -> loams.live.v1.live_pb2.QueryResponse:
        ...



