# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loams/live/v1/catalog.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'loams/live/v1/catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bloams/live/v1/catalog.proto\x12\rloams.live.v1\"\x9d\x01\n\x08TableDef\x12\x16\n\x06\x66ormat\x18\x01 \x01(\rR\x06\x66ormat\x12\x0e\n\x02id\x18\x02 \x01(\rR\x02id\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x31\n\x07indexes\x18\x04 \x03(\x0b\x32\x17.loams.live.v1.IndexDefR\x07indexes\x12\"\n\rnext_index_id\x18\x05 \x01(\rR\x0bnextIndexId\"F\n\x08IndexDef\x12\x0e\n\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n\x06\x66ields\x18\x03 \x03(\tR\x06\x66ields\"G\n\x06\x41ppDef\x12\x16\n\x06\x66ormat\x18\x01 \x01(\rR\x06\x66ormat\x12%\n\x0ejournal_shards\x18\x02 \x01(\rR\rjournalShardsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loams.live.v1.catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TABLEDEF']._serialized_start=47
  _globals['_TABLEDEF']._serialized_end=204
  _globals['_INDEXDEF']._serialized_start=206
  _globals['_INDEXDEF']._serialized_end=276
  _globals['_APPDEF']._serialized_start=278
  _globals['_APPDEF']._serialized_end=349
# @@protoc_insertion_point(module_scope)
