# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loams/live/v1/journal.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'loams/live/v1/journal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bloams/live/v1/journal.proto\x12\rloams.live.v1\"\xa3\x01\n\x0cJournalEntry\x12$\n\x0e\x63ommit_hint_ms\x18\x01 \x01(\x04R\x0c\x63ommitHintMs\x12\x32\n\x06writes\x18\x02 \x03(\x0b\x32\x1a.loams.live.v1.WriteRecordR\x06writes\x12\x1a\n\x08\x66unction\x18\x03 \x01(\tR\x08\x66unction\x12\x1d\n\nrequest_id\x18\x04 \x01(\tR\trequestId\"\xc5\x01\n\x0bWriteRecord\x12\x19\n\x08table_id\x18\x01 \x01(\rR\x07tableId\x12\x15\n\x06\x64oc_id\x18\x02 \x01(\x0cR\x05\x64ocId\x12,\n\x04kind\x18\x03 \x01(\x0e\x32\x18.loams.live.v1.WriteKindR\x04kind\x12,\n\x12index_keys_removed\x18\x04 \x03(\x0cR\x10indexKeysRemoved\x12(\n\x10index_keys_added\x18\x05 \x03(\x0cR\x0eindexKeysAdded*m\n\tWriteKind\x12\x1a\n\x16WRITE_KIND_UNSPECIFIED\x10\x00\x12\x15\n\x11WRITE_KIND_INSERT\x10\x01\x12\x16\n\x12WRITE_KIND_REPLACE\x10\x02\x12\x15\n\x11WRITE_KIND_DELETE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loams.live.v1.journal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEKIND']._serialized_start=412
  _globals['_WRITEKIND']._serialized_end=521
  _globals['_JOURNALENTRY']._serialized_start=47
  _globals['_JOURNALENTRY']._serialized_end=210
  _globals['_WRITERECORD']._serialized_start=213
  _globals['_WRITERECORD']._serialized_end=410
# @@protoc_insertion_point(module_scope)
