# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loams/live/v1/value.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'loams/live/v1/value.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19loams/live/v1/value.proto\x12\rloams.live.v1\"\xeb\x02\n\x05Value\x12\x34\n\nnull_value\x18\x01 \x01(\x0b\x32\x13.loams.live.v1.NullH\x00R\tnullValue\x12!\n\x0bint64_value\x18\x02 \x01(\x03H\x00R\nint64Value\x12#\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00R\x0b\x64oubleValue\x12\x1f\n\nbool_value\x18\x04 \x01(\x08H\x00R\tboolValue\x12#\n\x0cstring_value\x18\x05 \x01(\tH\x00R\x0bstringValue\x12!\n\x0b\x62ytes_value\x18\x06 \x01(\x0cH\x00R\nbytesValue\x12\x37\n\x0b\x61rray_value\x18\x07 \x01(\x0b\x32\x14.loams.live.v1.ArrayH\x00R\narrayValue\x12:\n\x0cobject_value\x18\x08 \x01(\x0b\x32\x15.loams.live.v1.ObjectH\x00R\x0bobjectValueB\x06\n\x04kind\"\x06\n\x04Null\"5\n\x05\x41rray\x12,\n\x06values\x18\x01 \x03(\x0b\x32\x14.loams.live.v1.ValueR\x06values\"\x94\x01\n\x06Object\x12\x39\n\x06\x66ields\x18\x01 \x03(\x0b\x32!.loams.live.v1.Object.FieldsEntryR\x06\x66ields\x1aO\n\x0b\x46ieldsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x14.loams.live.v1.ValueR\x05value:\x02\x38\x01\"\xdd\x01\n\x0e\x44ocumentRecord\x12\x16\n\x06\x66ormat\x18\x01 \x01(\rR\x06\x66ormat\x12\x1f\n\x0b\x63reation_ms\x18\x02 \x01(\x04R\ncreationMs\x12\x41\n\x06\x66ields\x18\x03 \x03(\x0b\x32).loams.live.v1.DocumentRecord.FieldsEntryR\x06\x66ields\x1aO\n\x0b\x46ieldsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x14.loams.live.v1.ValueR\x05value:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loams.live.v1.value_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECT_FIELDSENTRY']._loaded_options = None
  _globals['_OBJECT_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_DOCUMENTRECORD_FIELDSENTRY']._loaded_options = None
  _globals['_DOCUMENTRECORD_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_VALUE']._serialized_start=45
  _globals['_VALUE']._serialized_end=408
  _globals['_NULL']._serialized_start=410
  _globals['_NULL']._serialized_end=416
  _globals['_ARRAY']._serialized_start=418
  _globals['_ARRAY']._serialized_end=471
  _globals['_OBJECT']._serialized_start=474
  _globals['_OBJECT']._serialized_end=622
  _globals['_OBJECT_FIELDSENTRY']._serialized_start=543
  _globals['_OBJECT_FIELDSENTRY']._serialized_end=622
  _globals['_DOCUMENTRECORD']._serialized_start=625
  _globals['_DOCUMENTRECORD']._serialized_end=846
  _globals['_DOCUMENTRECORD_FIELDSENTRY']._serialized_start=543
  _globals['_DOCUMENTRECORD_FIELDSENTRY']._serialized_end=622
# @@protoc_insertion_point(module_scope)
